### ISSUE TITLE
Boolean attributes appended without a space in custom tag

### ISSUE THREAD

**Issue by wezm** [luckyframework/lucky#1001]
Perhaps there's a better way to achieve this, but anyway... I was supplied the following markup to use for my web statistics:

```html
<script data-goatcounter="https://readrust.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
```

Which after a few different attempts, I translated to:

```crystal
tag "script", "async", data_goatcounter: "https://readrust.goatcounter.com/count", src: "//gc.zgo.at/count.js" do
end
```

However when that's rendered it comes out as:

```html
<script data-goatcounter="https://readrust.goatcounter.com/count" src="//gc.zgo.at/count.js"async>
```

Note that `async` is joined to the `src`.

The issue seems to be in:

https://github.com/luckyframework/lucky/blob/e866dd93cff3e4aeafcd47fc3c6219aba87dd36b/src/lucky/tags/custom_tags.cr#L32

where it appends the `boolean_attrs` to the `tag_attrs` without a space in between.

**Comment by jwoertink** [comment]
I thought we made that an array 🤔 

Can you try this?

```crystal
script(src: "//gc.zgo.at/count.js", attrs: [:async], data_goatcounter: "https://readrust.goatcounter.com/count")
```

We should still fix this [here](https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/custom_tags.cr#L35), but I need to go back and think about why there's an overload that takes a string

**Comment by wezm** [comment]
Yep that works, and is definitely nicer :smile: Thanks.
