### ISSUE TITLE
Allow specifying columns for gen.model

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1007]
A few times already I tried generating a model with columns. Something like:

```
lucky gen.model Address street:String number:String postcode:String city:String
```

But unlike `gen.resource.browser`, they are ignored. Is this intentionally? Because it feels a bit inconsistent.

**Comment by paulcsmith** [comment]
Thanks for opening the issue  This is definitely not intentional. Just hasn’t been the biggest priority but would love it if this were supported like in the other generator!

**Comment by wout** [comment]
I will have a look at it one of these days. I guess the whole columns part can be moved to a mixin so we can include it in both `Gen::Model` and `Gen::Resource::Browser`.

**Comment by paulcsmith** [comment]
@wout Yeah I think that would work!
