### ISSUE TITLE
Running gen.model multiple times, generates multiple migrations.

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1008]
I would expect `gen.model` to check if the model, query, operation and migration already exist. Now, running the same command twice will generate the model, query and operation files the first time, but will not overwrite nor warn the second time. Migrations, on the other hand, are generated every time with a new timestamp.

**Comment by jwoertink** [comment]
I think this should just rails an error if the model already exists.

```
lucky gen.model User
... makes stuff
lucky gen.model User
Error: You tried to generate a User model, but already have one. If you need to update the table, gen.migration etc....
```

**Comment by paulcsmith** [comment]
I like that idea @jwoertink. It is hard to check for a migration since the timestamp is different every time, but checking if a model exists should be fairly easy 👍
