### ISSUE TITLE
Update Cry

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#1011]
When trying to update or install new shards, Lucky uses an internal version of [cry](https://github.com/luckyframework/cry). Cry used to use `Time.now` which was removed in [crystal 0.33.0](https://crystal-lang.org/2020/02/14/crystal-0.33.0-released.html#standard-library). It's since been updated but lucky needs to point to a that new version (and I think a new cry version has to be released or we could just point to a commit hash).

The error I'm seeing btw is when I try to `shards update`

```
$ shards update
~~ snip ~~

Building: lucky.exec
Error target lucky.exec failed to compile:
Showing last frame. Use --error-trace for full trace.

In lib/cry/src/cry/code_runner.cr:3:49

 3 | private getter filename_seed : Int64 = Time.now.to_unix_ms
                                                 ^--
Error: undefined method 'now' for Time.class

Did you mean 'new'?
```

**Comment by paulcsmith** [comment]
I think it’d be good to get out new releases of everything. I’m busy this weekend but hopefully earlier in the week I can help out. 

Or if you or @jwoertink want to start in some release PRs that’d be great, but no pressure ;)

**Comment by edwardloveall** [comment]
Here's cry: https://github.com/luckyframework/cry/pull/5

**Comment by jwoertink** [comment]
I think this is solved now, right?

**Comment by paulcsmith** [comment]
Yep should be good to go!
