### ISSUE TITLE
needs doesn't handle Metaclass

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1017]
```crystal
needs x : String.class
```

This throws an error saying `undefined method resolve for Metaclass` which is here:

https://github.com/luckyframework/lucky/blob/2327ebdcad5ada30bea3fac19c29c49f1e56ef46/src/lucky/html_builder.cr#L49

I think we can just sort metaclasses first.... unless it's possible for them to be nilable?

```crystal
dec.type.is_a?(Metaclass) || dec.type.resolve.nilable? || ....
```

**Comment by paulcsmith** [comment]
I think that would work unless there is `String.class?` Then you might need some other kind of check

Thanks for documenting it and providing ideas. I think we can get this figured out!
