### ISSUE TITLE
Missing a radio input form helper method

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1023]
We have [checkbox](https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/input_helpers.cr#L59) but no `radio` input helper method...

Now, this might not be as simple as just copying what `checkbox` is doing because we have to consider a UI like this:

<img width="232" alt="Screen Shot 2020-03-04 at 1 27 24 PM" src="https://user-images.githubusercontent.com/2391/75924501-ec4fc480-5e1b-11ea-9c06-3ad488476c73.png">

This is taken from a quiz where these are radio fields. A check box can be a single value, but radio is a little trickier.

**Comment by paulcsmith** [comment]
Good idea! Can you add this to the “expect to have” in the Lucky 1.0 roadmap?
