### ISSUE TITLE
Add 'previous_url' helper

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1025]
> This depends on other work I still need to document, so please don't start it yet :)

This links to the path in the referer header or uses a fallback path.

```crystal
link_to_back "Go back", fallback: Users::Index
```

**Comment by matthewmcgarvey** [comment]
I knew I had seen this before. I believe this functionality was added here: https://github.com/luckyframework/lucky/commit/6a8132dc999945440a17850d55731cffb83308a3

It's `redirect_back` instead of `link_to_back`

**Comment by jwoertink** [comment]
The `link_to_back` would be different. This would generate `<a>` tag that goes to maybe `history.goback()` or whatever that thing is, or maybe whatever the referrer was. It would be used in pages. The `redirect_back` would be used in Actions.

**Comment by paulcsmith** [comment]
Yeah it'd prob use the referrer and require a fallback. I've changed my mind on the API. I don't want a million link helpers. Also this is a lot less felxible because maybe you want a URL that goes back that will be used in a button or a JS handler?

So here is my new proposal:

```crystal
a "Back", href: previous_url(fallback: Users::Index)
```

So `previous_url` uses the referrer (pretty much just like `redirect_back` and requires a `fallback` argument. It just returns a String so can be used pretty much anywhere.

This can be added now since the page has access to `context` by default.

Thoughts? I think this would be super helpful and the API is a lot more flexible and super easy to implement (just one method!)

**Comment by jwoertink** [comment]
Oh, I think I like that much better. You're right about the JS stuff.
