### ISSUE TITLE
Add a new select_prompt method

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1027]
If you're using `select_tag` and rending all your options, there's no easy way to currently set your prompt. It would be neat to have a `select_prompt` method so we don't just bloat the current `options_for_select` with options.

```crystal
select(op.opts) do
  select_prompt("Select your option")
  options_for_select(op.opts, my_options)
end
```

My thought is this method would only generate:

```html
<option value="">Select your option</option>
```

If your prompt option is first, then it will display that, unless you have a selected option. The selected option would get set from your `options_for_select`, and then it would default to that.

Another way could be to pass in the attribute so you could not render the field if there's a value, but then you'd never be able to "unselect" your value.... 

```crystal
select_prompt(op.opts, "Select your option")
```

**Comment by paulcsmith** [comment]
Thank you for creating this! I think both options should be available. The one that removes the option if a value was selected is nice when select a blank value is invalid, so it should only show “Select your option” for brand new records.

**Comment by jwoertink** [comment]
ah! Yeah, I guess that's true too. You might not want someone to select a blank value if the record already exists. Good thinking!

**Comment by bdtomlin** [comment]
This would be nice. I frequently use multiple `options_for_select`s. 

This took me some time to figure out initially because I was expecting a `prompt` argument or something similar. It might not hurt to mention this way in the docs for when there are more complex requirements.

```crystal
options_for_select @save_user.manager_id, [{"", ""}]
options_for_select @save_user.manager_id, @manager_options
```
