### ISSUE TITLE
Proposal to drop `link to: String`.

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1033]
Right now our `link` helper method has a ton of overloads. [These 3](https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/link_helpers.cr#L38-L50) allow you to just pass a plain string. 

I'm not sure if this is actually useful though, and could lead to possible errors if not used properly.

Consider this:

```crystal
link "Hello", to: "/hello", class: "hello"
# vs
a "Hello", href: "/hello", class: "hello"
```

The second way is actually 1 character smaller 😅 . The benefit you get from the `link` helper method is that you can pass an action right in, and if that action isn't a GET, you'll auto get a `data-method="whatever"` added. This is gives you some safety, and extra help.

When using just the string, you could accidentally do `link to: "/ hello"`. This would compile, but not work, so you never gained any benefit from it. Yeah, this would be the same issue with `a()`, but I think it's assumed that if you go with the HTML basics, you're left to your own code. 

I propose that we deprecate those, or just raise some compile time errors telling you to just use `a()` if you're going to use a string directly.

### Downsides

The route helper method `path` returns a string, so this would no longer work

```crystal
link to: Home::Index.path
```

That is a bummer, but in this case, I'd say `link to: Home::Index` is a better option anyway.

**Comment by paulcsmith** [comment]
Totally agree. Great writeup. This might also fix https://github.com/luckyframework/lucky/issues/1026!

I think we should move forward with this since plain string should be discouraged and if you need it you can just use `a` like you said! 👍
