### ISSUE TITLE
Allow empty text for `link`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#104]
Sometimes the content is purely style with CSS so you don't need anything inside the link tag

**Comment by azbshiri** [comment]
Could you explain more? I decided to resolve this issue for tomorrow 🗡

**Comment by paulcsmith** [comment]
Yep! Right now you can't do this

```crystal
# Should be able to do this
link to: "/somewhere", class: "link-without-text"

# But instead you must give it empty text
link to: "/somewhere", class: "link-without-text"
```

This is useful because sometimes links don't have any text and instead have a background image or something where you don't need the text

**Comment by azbshiri** [comment]
```
  it "renders a link tag with an action" do
    view.link("Test", to: LinkHelpers::Index).to_s.should contain <<-HTML
    <a href="/link_helpers">Test</a>
    HTML

    link = view.link(to: LinkHelpers::Index, class: "link") { }

    link.to_s.should contain <<-HTML
    <a href="/link_helpers" class="link"></a>
    HTML
  end
```
Here you did what's been discussed I think !?

**Comment by paulcsmith** [comment]
Thanks for double checking. That has a block passed at the end: `{}`. I'd like it if people didn't need to pass an empty block at the end

**Comment by azbshiri** [comment]
@paulcsmith Alright then.

**Comment by azbshiri** [comment]
@paulcsmith where's the definition of the method which gets a block?

**Comment by paulcsmith** [comment]
@azbshiri These two methods: https://github.com/luckyframework/web/blob/master/src/lucky_web/tags/link_helpers.cr#L10-L20 

There may be another for handling a regular string with a block as well in that same file :) Thanks for taking a look at this
