### ISSUE TITLE
Add 'd' shortcut method for generating a div with a class

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1048]
Creating divs with a class is extremely common. To make this simpler we should consider adding a `d` shortcut method:

```crystal
# Instead of:
div class: "my-class" do
end

# This:
d "my-class" do
end

# Can also add other html attrs
d "my-class", flow_id: "my-id" do
end
```

Thoughts? Maybe better for a separate shard?

**Comment by jwoertink** [comment]
hmm... I could see something like this end up getting mixed between an app that has half `div` and half `d` all over. The better solution is using `div` less 😛  hahah

**Comment by paulcsmith** [comment]
@jwoertink Yeah I think that's a dang good point. And honestly I don't feel the pain much from using `div`. Someone mentioned it awhile back though so thought I'd get some feedback

I'm thinking if we do this it should be a shard so people can use it if they want, but we don't have it in the docs or anything

**Comment by wout** [comment]
Unless it's something like `internationalization`, I don't mind writing a few extra characters. So either `d` or `div` is perfectly fine with me. Using one option definitely brings more clarity, and I am leaning slightly towards `div`.

**Comment by paulcsmith** [comment]
Gonna go ahead and close this. I think we can stick with `div`. Thanks for all the input
