### ISSUE TITLE
Add option to only log 'before/after' pipes if the pipe halts

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1054]
Sometimes you don't really need to show which pipe is running and you only care if it halts. For example the protect_from_forgery pipe and test_backdoor pipe.

Would love to do this:

```crystal
before require_admin # Log when it halts and when it continues
before protect_from_forgery, only_log_when_halted: true
before test_backdoor, only_log_on_halt: true
```

Really unsure of a good name for this option though. I want it to be clear since it won't be used that much, but also don't want it to be so long you fall asleep halfway through reading the line

**Comment by paulcsmith** [comment]
cc @jwoertink @edwardloveall thoughts on what this option should be called?

**Comment by edwardloveall** [comment]
`log_on_failure`?

**Comment by paulcsmith** [comment]
I'm not quite sure it is a failure since `halt` would still be a valid use case. Like `require_sign_in` halting would be because of a redirect so not really a failure.

It also needs to somehow convey that it will not log that it runs, but *just* when it halts...which is kind of hard to do. I had a thought for `, log: :on_halt`? With just 3 options `:on_halt`, `:all` (default), `:never`. Where `never` is pretty much never used but may come in handy I guess??

**Comment by edwardloveall** [comment]
`log: :on_halt` is good. I'd recommend saying `always` instead of `all` though.

**Comment by paulcsmith** [comment]
Great idea! Yeah that fits better with the other options! Thanks for the feedback Edward. You're very good at coming up with names 🍀

![high five](https://user-images.githubusercontent.com/22394/77165710-3de98780-6a89-11ea-89b6-90ea7492a00e.gif)

**Comment by paulcsmith** [comment]
Actually I was implementing this I realized logging only on halt should probably be the normal behavior. It is only rarely useful to see all the before/after that are running. 

However I thnk it *can* be useful to see all pipes that have run so I'm thinking of doing something like we do with Avram where we set a default log level of `nil` for logging before/after, but you can set it to `debug` or `info` if you want to see every pipe that ran

Gonna go ahead with that for now, but if you've got thoughts/concerns LMK!

**Comment by edwardloveall** [comment]
That makes a lot of sense! 👍 I think it would be rare that I want _one_ pipe to be logged. Might put you on a wild goose chase too.
