### ISSUE TITLE
Missing AppClient methods for testing

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1063]
The `AppClient` proxies to the Crystal [HTTP Client](https://crystal-lang.org/api/0.33.0/HTTP/Client.html), so we should also add `:delete`, `:head`, and `:options` to this list.

https://github.com/luckyframework/lucky/blob/5d207b26620da1c0ccb230b75331020c7c39fe40/src/lucky/base_http_client.cr#L15

We also need to add to this list, but note that we don't add `exec` here because we catch that method manually. 

https://github.com/luckyframework/lucky/blob/5d207b26620da1c0ccb230b75331020c7c39fe40/src/lucky/base_http_client.cr#L93

**Comment by paulcsmith** [comment]
Sounds like a plan 👍

**Comment by rnice01** [comment]
I’d like to work on this if possible. Should I add a spec as well?

**Comment by jwoertink** [comment]
Yeah! That'd be awesome @rnice01. The specs I believe are in https://github.com/luckyframework/lucky/blob/master/spec/lucky/base_http_client_spec.cr

**Comment by paulcsmith** [comment]
Thanks @rnice01!
