### ISSUE TITLE
Support for email development

### ISSUE THREAD

**Issue by wontruefree** [luckyframework/lucky#1068]
Right now with the carbon development adapter you cannot see the contents of an email without changing code.  It would be nice to see anything from the email in the dev environment.

I think it would be nice to write out email to the `/tmp/email` dir.

**Comment by jwoertink** [comment]
This would be similar to Rails' [ActionMailer::Preview](https://dev.mikamai.com/2017/03/30/setting-an-environment-for-previewing-email-in-rails/) ?

**Comment by paulcsmith** [comment]
This is a good idea. We've got a similar issue in Carbon https://github.com/luckyframework/carbon/issues/3 that will cover this :D So I'm going to close this.

Maybe we start simple and log it like you said, but long/medium term I'd like to have a UI where you can inspect email, requests, etc.
