### ISSUE TITLE
Memoizing JsonBodyParser

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1075]
In https://github.com/luckyframework/lucky/pull/1061 there was a change made where [memoize was added here](https://github.com/luckyframework/lucky/pull/1061/files#diff-d633a5eeaf04a8d42861bcc3614b84bfR480). I think we can also add it [here](https://github.com/luckyframework/lucky/blob/master/src/lucky/json_body_parser.cr#L18) to just match those up. Probably a super small performance boost since `body` would be called twice if there's json to be parsed.

**Comment by wontruefree** [comment]
I was looking into this a bit.  I don't see the JSON parser being called more then once I think we might need to write a benchmark so show this memorization would improve performance.

**Comment by jwoertink** [comment]
`body` is called once here https://github.com/luckyframework/lucky/blob/master/src/lucky/json_body_parser.cr#L9 then again here https://github.com/luckyframework/lucky/blob/master/src/lucky/json_body_parser.cr#L12. 

Now, I'm sure if we did benchmark this, it would be almost no difference. It's just so small. This more came up because I saw the other thing updated, and I figure we might as well make these the same.
