### ISSUE TITLE
Add `route_prefix` macro for prefixing/namespacing routes

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1087]
https://github.com/luckyframework/lucky/discussions/834#discussioncomment-3323

```crystal
abstract class ApiAction < Lucky::Action
  route_prefix "/api/v1"
end
```

Would prefix routes that inherit from this class with `/api/v1` so you don't have to do it for every single route

**Comment by wout** [comment]
That would be perfect! Will param interpolation work there as well?

```crystal
abstract class ShopAction < Lucky::Action
  route_prefix "/shops/:handle"
end
```

**Comment by paulcsmith** [comment]
@wout yes! It’ll basically copy paste the prefix as is. So anything you’d do in get/post/etc would work in route prefix

**Comment by rnice01** [comment]
I'd like to work on this, should this macro go in the routable module?

**Comment by jwoertink** [comment]
@rnice01 Yeah, I think that's what I'd probably put it. That module is included in all of the actions already.

**Comment by paulcsmith** [comment]
@rnice01 Thanks for contributing! This will almost certainly require some macros. They can be a bit tricky to work with so if you need any help feel free to ping me

**Comment by rnice01** [comment]
Hey @paulcsmith , I'm a bit stuck on this one :sweat_smile: . So I'm not sure the best way to accomplish this but here's what I have so far. I'm trying to define a method that will return the prefix if the `prefix_path` macro is called. Not sure if this is the best way to do it. Where I'm stuck is trying to call the method in the[ `add_route` macro](https://github.com/luckyframework/lucky/blob/master/src/lucky/routable.cr#L163).

`# Returns the route prefix
  # set from the route_prefix macro
  def prefix_for_path()
  end

  # Defines the prefix for all
  # of the action's methods
  macro prefix_path(prefix)
    def prefix_for_path()
      prefix
    end
  end`

**Comment by rnice01** [comment]
@paulcsmith Yes that was very helpful, thank you! I did however notice that other actions were getting prefixed as well. It appears as though the problem comes from the constant not being overridden by subclasses. This behavior appears to be intentional as noted in [this issue](https://github.com/crystal-lang/crystal/issues/3241).

I tried using the syntax suggested in the thread and was having some difficulty getting it to compile. I'll work on it some more this weekend to see if I can get it working properly.

**Comment by paulcsmith** [comment]
@rnice01 Oh that is a great point If you look in other spots of the codebase you can see how we "inherited" constants by coping them.

https://github.com/luckyframework/lucky/blob/522b207bccd07a4ab20e4eb7a302f99ae115e5a8/src/lucky/exposable.cr#L2-L17

Maybe that helps! And feel free to post back here or in Gitter if you wanna chat. This stuff is triiicky!
