### ISSUE TITLE
Error: undefined constant Settings::Index

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1091]
After upgrading to 0.20.0, I am getting the following error:

```
There was a problem expanding macro 'add_route'

Code in macro 'infer_route'

 1 | add_route :get,
     ^
Called macro defined in lib/lucky/src/lucky/routable.cr:163:3

 163 | macro add_route(method, path, action)

Which expanded to:

 > 1 | Lucky::Router.add(:get, "/settings", Settings::Index)
                                            ^--------------
Error: undefined constant Settings::Index
```

It's also reproducible with a brand new 0.20.0 app by adding a new browser action:

```
lucky gen.action.browser Settings::Index
``` 

Also, the error goes away after deleting all `Settings::*` actions. So for the time being, I'll go with `Preferences` instead.

**Comment by paulcsmith** [comment]
Just to make sure I understand, this was working in 0.19.0, but broke in 0.20.0?

**Comment by wout** [comment]
Yes, I was on 0.19 and after upgrading it stopped working. Haven't had the time to look further than creating a new 0.20.0 app to verify it's not something else.

**Comment by paulcsmith** [comment]
@wout Gotcha! Thanks for the bug report!

**Comment by matthewmcgarvey** [comment]
@jwoertink I think this issue is fixed since you made this change right? https://github.com/luckyframework/habitat/commit/5642f391fde987327d3c71638f2bca4607fa92d0

**Comment by jwoertink** [comment]
Yup! Good catch @matthewmcgarvey. This issue will be fixed in the next release if it's not already.
