### ISSUE TITLE
Bug in password reset token

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1092]
I've been testing our password reset flow and ran into a few 500 errors. At first, I thought it was on my side, but it turns out there is a bug caused by the generated tokens.

If a token contains a `+`, it is interpreted as whitespace. Here is an example:

```
GSSuuPIePHZIDu4fx/ugiIcVX3jQratcnG6V0MBgJ5M=--xm02SWDRKUUIzaf8P+fPub95NWo=

---------------------------------------------------------------^
```

At the error page, it shows the token without the `+`:

![lucky-error](https://user-images.githubusercontent.com/107324/79004309-66c2e100-7b4c-11ea-94b8-6512e818b5fd.png)

**Comment by jwoertink** [comment]
Oh interesting. We will need to check for a url_safe option for this just to be sure.

**Comment by wout** [comment]
Yeah, it's probably an easy fix in authentic.

**Comment by paulcsmith** [comment]
Ah nice. URL safe or probably encode with Base64 should likely fix it too

**Comment by wout** [comment]
@paulcsmith 

So, `Base64.strict_encode` the token before usage and `Base64.decode_string` before comparison? I can create a PR for that...

**Comment by jwoertink** [comment]
I think we'd want [urlsafe_encode](https://crystal-lang.org/api/0.34.0/Base64.html#urlsafe_encode(data,io:IO)-instance-method) which will replace `+` with `-`.

**Comment by wout** [comment]
Ok, that sounds more reasonable. A good one to know. 🤓️
