### ISSUE TITLE
Extract route inference macros to a shard

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1099]
Part of https://github.com/luckyframework/lucky/discussions/789#discussioncomment-3296 so people can continue to use route inference if they prefer that

**Comment by matthewmcgarvey** [comment]
@paulcsmith I believe I have done this. https://github.com/matthewmcgarvey/lucky_legacy_routing

I don't personally find the inferred routing very helpful but if it gets the framework closer to 1.0, I'm happy to maintain it.

I've tested it locally after making a lucky branch without the macros and everything seemed to work fine.

**Comment by paulcsmith** [comment]
@matthewmcgarvey That looks great!

Are you ok leaving it on yours? We'd be happy to move it to the lucky org and help maintain it if that'd help. Either way I'll mark this as closed. Thanks for doing that!
