### ISSUE TITLE
Add checks for route inconsistencies

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1101]
Similar to #1100 

We should check for similar routes and raise/warn/something

From https://github.com/luckyframework/lucky/discussions/789#discussioncomment-2858

> And I think we could add a task for checking route consistency so it can find "similar" paths that are off by a character or 2 so you can fix them if you want.

Maybe we also check rest routes by default. Like `Users::Index` should be `/users/:user_id` but can be skipped. Prob requires a bit of thought

**Comment by jwoertink** [comment]
This is actually being done now between https://github.com/luckyframework/lucky/pull/1538 and https://github.com/luckyframework/lucky/pull/1536
