### ISSUE TITLE
Posting JSON with wrong structure gives unhelpful 500

### ISSUE THREAD

**Issue by KCErb** [luckyframework/lucky#1111]
Hi folks, long time no see! So glad to see this project going strong!

I learned today that the correct JSON to post (on sign_in from a new JSONAPI+Authentication app) is
```json
{
  "user": {
    "email": "test-email-1@example.com",
    "password": "password"
  }
}
```

and if you instead POST

```json
{
  "email": "test-email-1@example.com",
  "password": "password"
}
```

you get

```
POST /api/sign_ins
 ▸ Handled by Api::SignIns::Create
 ▸ Exception cast from String to Hash(K, V) failed, at /usr/share/crystal/src/json/any.cr:244:5:244 (TypeCastError)
  from /usr/share/crystal/src/json/any.cr:243:3 in 'as_h'
  from lib/lucky/src/lucky/params.cr:834:5 in 'nested_json_params'
  from lib/lucky/src/lucky/params.cr:189:7 in 'nested?'
  from lib/lucky/src/lucky/params.cr:166:5 in 'nested'
  from src/operations/sign_in_user.cr:6:3 in 'email_param'
  from src/operations/sign_in_user.cr:6:3 in '_email'
  from src/operations/sign_in_user.cr:6:3 in 'email'
  from src/operations/mixins/user_from_email.cr:3:5 in 'user_from_email'
  from src/actions/api/sign_ins/create.cr:11:5 in 'call'
  from lib/lucky/src/lucky/renderable.cr:97:16 in 'perform_action'
  from lib/lucky/src/lucky/route_handler.cr:10:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/lucky/src/lucky/remote_ip_handler.cr:15:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/lucky/src/lucky/error_handler.cr:15:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/lucky/src/lucky/log_handler.cr:17:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/lucky/src/lucky/http_method_override_handler.cr:11:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/lucky/src/lucky/force_ssl_handler.cr:37:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:48:11 in 'process'
  from /usr/share/crystal/src/http/server/request_processor.cr:22:3 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:464:13 in '->'
  from /usr/share/crystal/src/fiber.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???

 ▸ Sent 500 (212.36ms)
```

**Comment by jwoertink** [comment]
Hey @KCErb! Welcome back. That's an interesting error. Thanks for reporting! You got it all working once you did the correct params?

**Comment by KCErb** [comment]
Yes, works as expected otherwise :)

**Comment by matthewmcgarvey** [comment]
So I'm wondering if this specific error has been fixed since this was reported.

I generated a brand new app with json and authentication, made a `POST` request to `localhost:3001/api/sign_ups` with a body of

```json
{
  "email": "test-email-1@example.com",
  "password": "password"
}
```

and got back a `400` response with a json body of

```json
{
  "message": "Missing param key: 'user'",
  "param": null,
  "details": null
}
```

One thing I did see was that it would fail kind of like as reported if I provided the expected key but as a different type than a nested hash. So with a body of

```json
{
  "email": "test-email-1@example.com",
  "password": "password",
  "user": "NOT A NESTED HASH"
}
```

I got a 500 response with this printed in the console

<img width="977" alt="CleanShot 2020-12-07 at 18 00 26@2x" src="https://user-images.githubusercontent.com/17329408/101419847-80245480-38b6-11eb-8b59-7f1e9e39194c.png">

**Comment by matthewmcgarvey** [comment]
Maybe an old version of lucky was used? I could see this error occurring if using a version of lucky from before this commit https://github.com/luckyframework/lucky/commit/c29f3368646febef3c6a49e87792db00a2f2d68d

I think this issue is fixed now, though.

**Comment by KCErb** [comment]
Makes sense to me @matthewmcgarvey I've played with the json error handling a bit more since then and I agree that this shouldn't be the case. If you just tested this I'm happy for you to close it. I'm away from my computer at the moment but I could also double check next chance if you'd rather I confirmed before closing.

**Comment by jwoertink** [comment]
Let's keep this open until after this next release. We will test on that when it's out, and if it's good we can close then if that's cool with y'all 😄

**Comment by jwoertink** [comment]
Looks like this is resolved now, but if anyone comes across the issue again, feel free to let me know and we can reopen.

**Comment by defido** [comment]
This happens in Lucky 0.30.0

```
{
    "message": "Missing param key: 'user'",
    "param": null,
    "details": null
}
```
<img width="566" alt="Screen Shot 2022-06-19 at 6 56 43 pm" src="https://user-images.githubusercontent.com/95591037/174473381-f0e13c7f-38c3-46c3-bdf7-2514bdb3b3e5.png">

**Comment by jwoertink** [comment]
@defido that error you showed is actually the correct error. If you don't send over the params with the proper param key, then you'll get the missing param key error. The original error was that you'd get "cast from String to Hash failed". 

In your case, you would need to nest the params within the `user` key:

```
user:email=test@gmail.com&user:password=testtest
```
or for JSON data

```
{ user: { email: "test@gmail.com", password: "testtest" } }
```

**Comment by defido** [comment]
> 

Appreciate it, that did the trick.
