### ISSUE TITLE
Directory Listing is enabled by default

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1117]
The StaticFileHandler is built-in to the std-lib for Crystal, and Lucky just piggybacks off that. When we generate a new app, we leave the default to `true` for the DirectoryListing https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/src/app_server.cr.ecr#L22

This means that all production Lucky (browser) apps you can go to `/assets/` and browse all of the static files in the public/assets directory. I think we should disable this by default. Just add a third argument of `false`.

**Comment by paulcsmith** [comment]
Yeah let’s do it!
