### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by wnederhof** [luckyframework/lucky#1130]
Just installed Lucky on my machine (Macbook Air), and tried to run `lucky init.custom my_app` when I got this error:

```
Unhandled exception: Error while changing directory: 'my_app': No such file or directory (File::NotFoundError)
  from Crystal::System::Dir::current=<String>:String
  from Dir::cd<String>:String
  from LuckyCli::Generators::Web@LuckyCli::GeneratorHelpers#append_text<String, String>:Nil
  from LuckyCli::Generators::Web#add_deps_to_shard_file:Nil
  from LuckyCli::Generators::Web#run:Nil
  from LuckyCli::Generators::Web::run:project_name:api_only:generate_auth:project_directory<String, Bool, Bool, String>:Nil
  from LuckyCli::CustomInit#generate_project<LuckyCli::ProjectName>:Nil
  from LuckyCli::CustomInit#run:Nil
  from LuckyCli::CustomInit@LuckyCli::Init::run:Nil
  from __crystal_main
  from Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil
  from Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32
  from main
```

Crystal version: 0.34.0
Lucky version: 0.21.0

Any ideas? Would love to try it out!

**Comment by jwoertink** [comment]
Hey! Welcome to Lucky. 

I just gave it a shot too and it worked....

```
[15:23PM] jeremywoertink$ cd Sites
[15:23PM] Sites$ lucky init.custom testbox
Done generating your Lucky project

  ▸ cd into testbox
  ▸ check database settings in config/database.cr
  ▸ run script/setup
  ▸ run lucky dev to start the server
[15:23PM] Sites$ lucky init.custom my_app
Done generating your Lucky project

  ▸ cd into my_app
  ▸ check database settings in config/database.cr
  ▸ run script/setup
  ▸ run lucky dev to start the server
```

I wonder what's different here? 🤔  How did you install your crystal and lucky versions? homebrew? or hand build? Also, can you try just running `lucky init`, and see if the wizard lets you build an app?

**Comment by jwoertink** [comment]
One other thing to try if you can.

CD in to some other directory like your home or whatever, and pass in whatever directory you normally put your projects in (e.g. Projects)

```
cd ~
lucky init.custom my_app --dir ~/Projects/
cd Projects/my_app
```

I'm wondering if this is a bug with the init.custom specifically, or if there's another issue going on.

**Comment by wnederhof** [comment]
Sorry! Should have been more specific.

I followed the guide at

```
https://luckyframework.org/guides/getting-started/installing
```

Added OpenSSL for ZSH using

```
echo 'export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig' >>~/.zshrc
```

Installed ASDF

```
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
asdf plugin-add crystal https://github.com/asdf-community/asdf-crystal.git
```
Added to the .zshrc:
```
. $(brew --prefix asdf)/asdf.sh
```
And ran:
```
echo -e "\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash" >> ~/.bash_profile
```
Now, I deviated a little bit from the tutorial, because it couldn't find `crystal` when I ran `./crystal -v`, even after restarting the terminal. So I ran:
```
asdf install crystal latest
```
(Perhaps that's where it went wrong? Not sure... I do have version Crystal 0.34.0...).
Then I ran
```
echo "legacy_version_file = yes" >>~/.asdfrc
```
And `crystal -v` responded with `0.34.0`. Finally, I installed lucky using Homebrew and ran both `lucky init` and the command above. Both didn't work unfortunately.

**Comment by wnederhof** [comment]
```
cd ~
lucky init.custom my_app --dir ~/Projects/
cd Projects/my_app
```
Also throws the same exception unfortunately.

**Comment by paulcsmith** [comment]
Sorry you're having trouble! I hope we can figure this out for you

Could you:

 * Try using regular `init` and see if that works?
* Let us know what directory you're in when running lucky init.custom?

**Comment by wnederhof** [comment]
So I tried init as well, same error.

In both cases I'm either in ~/hobby or ~.

**Comment by paulcsmith** [comment]
@wnederhof Yeah me too! This is definitely a first.

What if you try to create a crystal project manually? `crystal init app my_app`?

**Comment by wnederhof** [comment]
Hmm, apparently I wrongly configured `asdf` (I program Kotlin in my day-to-day work, so I am not familiar with these tools). When I ran `echo crystal 0.34.0>>.tool-versions`, it started to work. Thank for the help and apologies for the inconvenience! I'm going to try programming some Crystal and Lucky today! :-)

**Comment by paulcsmith** [comment]
Woo hoo! Glad you got it working! Feel free to hop on our chatroom if you run into anything. We're all happy to help https://gitter.im/luckyframework/Lobby

**Comment by jwoertink** [comment]
Glad to see you got it working @wnederhof 🎉  Let us know if you have questions 😄
