### ISSUE TITLE
Lucky::RequestTypeHelpers#ajax? always false

### ISSUE THREAD

**Issue by skojin** [luckyframework/lucky#1131]
enable :js format in action: ```accepted_formats [:js]```
do remote request with rjs
[```ajax?```](https://github.com/luckyframework/lucky/blob/master/src/lucky/request_type_helpers.cr#L67) returns false because ```clients_desired_format == :js```

This happen because accept_header checked before X-Requested-With
https://github.com/luckyframework/lucky/blob/b59d48d23ee7f17d491c6f9003b7363b391e65e1/src/lucky/mime_type.cr#L54-L57

**Comment by paulcsmith** [comment]
Ohh that makes sense. Would you mind writing a PR with a spec that catches this and then put `ajax?` ahead of the `usable_accept_header?`

**Comment by skojin** [comment]
Ok,

But the question is why they are exclusive? I can make xhr request and it will be both :js and :ajax

I can't just move line just ahead of ```usable_accept_header```, that will give page format :ajax instead of :js

I suggest remove this spec https://github.com/luckyframework/lucky/blob/b59d48d23ee7f17d491c6f9003b7363b391e65e1/spec/lucky/mime_type_spec.cr#L27-L30

and make request_type_helpers.cr#ajax? just check XMLHttpRequest, same as rails xhr?

**Comment by paulcsmith** [comment]
@skojin You are totally right. Removing that spec and making `ajax?` just check the header sounds perfect. I imagine it'd still be nice to combine "accepts" and "ajax" together and your proposed approach makes that easy 👍
