### ISSUE TITLE
gen.model unsupported column type error should be more descriptive

### ISSUE THREAD

**Issue by rnice01** [luckyframework/lucky#1138]
Lucky: 0.21.0
Crystal: 0.34.0
- lucky init
- full support
- using auth

Just created a new Lucky app, ran the setup script, and was trying the model generator with the following command:
`lucky gen.model Vehicle make:String model:String year:String type:Integer thumbnail:string`
I received the following error:
```
Must provide a supported column type for the model: lucky gen.model Vehicle name:String

Other complex types can be added manually. See https://luckyframework.org/guides/database/migrations#add-column for more details.
```
I think it would be helpful if the error gave details as to which columns passed in the arguments are not supported. In the case it would be the `type:Integer` and `thumbnail:string`

Something to the effect of:
```
Unable to generate model {model_name}, the following columns do not have supported column types:
type:Integer
thumbnail:string

Please refer to {link to docs} for supported column types.
```

**Comment by rnice01** [comment]
I'd also like to work on this!

**Comment by jwoertink** [comment]
Sure thing! That error is here https://github.com/luckyframework/lucky/blob/master/tasks/gen/mixins/migration_with_columns.cr#L64

**Comment by paulcsmith** [comment]
This is a great idea!

**Comment by rnice01** [comment]
@paulcsmith @jwoertink 
So I'm noticing some inconsistencies between the gen.model and gen.resource.browser.
Examples:

- gen.model doesn't allow numeric values in the name but gen.resource.browser does
- gen.model will generate a model without any column arguments, gen.resource.browser requires at least one column to be passed in the arguments
- gen.model checks for existing models, gen.resource.browser does not

There's also some code duplication in the resource name validations and tests. I'm proposing a resource name validation class to be used in the model and browser generators. Then moving all the specs regarding the resource name into that new class's spec file.

This could remove duplication, clarify the API, and improve consistency.

**Comment by jwoertink** [comment]
Yeah, there's a few things that can be cleaned up. After the next release, we will have the native CLI args in place where we can refactor all of the generators to use those properly. That's going to clean up a ton of code. I think we should hold off until after the next release before tackling that just so we don't go refactoring, and then doing a secondary refactor anyway. 

I do like your suggestions for these refactors though. That also makes me think... the new CLI args do have a `format` option which is basically just a regex... but that could also be updated to take a class that implements a method to handle.. 🤔  maybe overkill? dunno, just thinking aloud here.

**Comment by paulcsmith** [comment]
@jwoertink I would love it if you could pass a class: `validate_with: ModelNameValidator`
