### ISSUE TITLE
bind_tcp ignore ENV or server config

### ISSUE THREAD

**Issue by confact** [luckyframework/lucky#1146]
When running  Lucky in production the bind_tcp in app_server.cr ignore the host:
```crystal
  def listen
    # Learn about bind_tcp: https://tinyurl.com/bind-tcp-docs
    server.bind_tcp(host, port, reuse_port: false)
    server.listen
  end
```
I added a puts there to print out the address:
```crystal
  def listen
    # Learn about bind_tcp: https://tinyurl.com/bind-tcp-docs
    address = server.bind_tcp(host, port, reuse_port: false)
    puts "Listening on http://#{address}"
    server.listen
  end
```
this prints out:
```bash
Listening on http://127.0.0.1:5000
```
and set environment variables HOST to `0.0.0.0` and LUCKY_ENV to `production`
it says:
```bash
Listening on http://127.0.0.1:5000
```
I change the host for production in `config/server.cr`
it says:
```bash
Listening on http://127.0.0.1:5000
```

If I force it and type this:
```crystal
  def listen
    # Learn about bind_tcp: https://tinyurl.com/bind-tcp-docs
    address = server.bind_tcp("0.0.0.0", port, reuse_port: false)
    puts "Listening on http://#{address}"
    server.listen
  end
```
it says:
```bash
Listening on http://0.0.0.0:5000
```

What I want it to happen:
* That if I set ENV["HOST"] that it will be set.
* Maybe have listening on puts like above for fast debugging even on production.

My environment variables:
- LUCKY_ENV=production
- HOST=0.0.0.0
- PORT=5000
- SECRET_KEY_BASE=afasgfadsfsafasfas (fake)
- APP_DOMAIN=http://kindmetrics.io

**Comment by paulcsmith** [comment]
The issue was `LUCKY_ENV` was set to `"production\n"`. This will be improved by https://github.com/luckyframework/lucky_cli/issues/512
