### ISSUE TITLE
Add redirect_back

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1158]
Similar to Rail's `redirect_back`. Should require a `fallback` argument in case there is no previous page.

Example:

```crystal
redirect_back(fallback: Home::Index)
redirect_back(fallback: "/string/path")
```

**Comment by matthewmcgarvey** [comment]
The link to Rails source for `redirect_back` for future reference https://github.com/rails/rails/blob/97c3a5605bacd62e5a01872dfe5e5976cd982115/actionpack/lib/action_controller/metal/redirecting.rb#L90
