### ISSUE TITLE
Add optional_param macro to actions

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#116]
This will make it so you can declare that a query param is optional. This would be used for things like `page` for paginating.

```crystal
class Users::Index < BrowserAction
  optional_param page
end
```

When you declare this it should also created a method for the param

```crystal
def page
  params.get!(:page)
end
```

And it should add an optional argument to the route and path methods that are generated for the action

**Comment by citizen428** [comment]
So the macro should roughly start like this:

```crystal
  macro optional_param(param)
    def {{ param }}
      params.get!(:{{ param }})
    end
  end
```

Since it will modify the route and  path, should we add it to `LuckWeb::Routeable` or would you prefer a new module? Also: any hints on adding the optional argument to the route/path programmatically? I'm not that familiar with the Lucky codebase yet.

**Comment by paulcsmith** [comment]
Yep that is roughly what it would look like, but it would use `params.get?` since the param might be nil.

I think `LuckyWeb::Routeable` is a good place to put it for now.

For generating the list of optional params you'll probably want to do something like this:

Check out [`LuckyWeb::Exposable`](https://github.com/luckyframework/web/blob/master/src/lucky_web/exposable.cr) to see how the constants work.

* Add a constant to `Routeable` (similar to `LuckyWeb::Exposable`) to hold the list of optional params `OPTIONAL_PARAMS = [] of Symbol`.
* Add a macro for `optional_param` that does what you listed above AND adds to the constant `{% OPTIONAL_PARAMS << param.id %}`
* In the `route` and `path` methods, loop over the optional params. Something like this:

```crystal
# https://github.com/luckyframework/web/blob/master/src/lucky_web/routeable.cr#L65-L69
# Add as params to generated route and path methods
{% for param in OPTIONAL_PARAMS %}
  {{ param.id }} : String? = nil,
{% end %}
```

Then in the body of the method you'll need to do add the query params to the generated path. There is probably something in the standard lib for this. I'm not sure though. You may have to play around with it a bit. Feel free to ping me if you get stuck on that part

The macros for generating paths/routes are a bit hairy so feel free to refactor. Using macros in this way is fairly hard so if you need help LMK. It took me awhile to figure out how to do it.

**Comment by paulcsmith** [comment]
Also, feel free to hop on https://gitter.im/luckyframework/Lobby and we can chat there if it's easier

**Comment by citizen428** [comment]
Yeah, I was on lurking on Gitter, but I’m on ICT, which is not a good time
zone to talk to the US. Going on 1am here...

Anyway, thanks for the detailed explanation, I’ll try to get this done over
the next few days.

**Comment by paulcsmith** [comment]
@citizen428 Makes sense! Good luck :)
