### ISSUE TITLE
Flash messages are not maintained with multiple redirects.

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1162]
In continuation of [#1160](https://github.com/luckyframework/lucky/pull/1160#issuecomment-636313797).

**Comment by wout** [comment]
Ok, I've located the issue and found an easy fix but before I make a PR, I would like to discuss the changes.

Let's say we have the following setup:
- `SignIns::Create` redirects to `Home::Index` and sets a `flash.success = "Yay!"`
- `Home::Index` redirects to `Dashboard::Index` and does not set a flash

The `Home::Index` action does not consume the flash, so when you arrive at `Dashboard::Index`, the flash has been lost. An easy fix is to recycle the flash on redirects. That's something we can easily add in `Lucky::Redirectable`:

```cr
module Lucky::Redirectable
  # ...
  def redirect(to path : String, status : Int32 = 302) : Lucky::TextResponse
    flash.recycle
    # ...
  end
  # ...
end
```

Its functionality would be:

```cr
class Lucky::FlashStore
  # ...
  def recycle
    @next = @now
  end
  # ...
end
```

What do you think?

**Comment by confact** [comment]
I had the same issue myself. Good catch @wout! 

I think that sounds good, but maybe some setting/param to disable the flash on redirect if you want to for some reason.

**Comment by wout** [comment]
@confact I've also been thinking about that. But if you don't want the flash messages to be recycled, you could always explicitly `clear` the flash:

```cr
class Home::Index < BrowserAction
  get "/home" do
    flash.clear
    redirect Home::Show
  end
end
```

I found that to be convenient enough. :)

**Comment by confact** [comment]
A yeah. That's even better :)

**Comment by paulcsmith** [comment]
Love it! I think `flash.recycle` in the `redirect` helper is perfect, and clearing the flash should work great if you no longer want it.

The only suggestion I have (which shouldn't stop a PR) is to call it `Flash#reuse`. but maybe that's worse. Either way not a big deal since will likely only be used internally by Lucky 👍
