### ISSUE TITLE
Add favicon_tag method

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1175]
This could be used for dynamic favicons.

```crystal
def favicon_tag(path : String)
  empty_tag("link", rel: "shortcut icon", href: path)
end

favicon_tag(dynamic_asset("images/#{current_site}.ico"))
```

Maybe we could expand the method a bit to also include things like those apple icons and such?

**Comment by wout** [comment]
That would be great! There are quite a lot though...

**Comment by jwoertink** [comment]
Yeah, I figure there's not too many reasons you'd use the `<link>` tag, so if we make helpers for the most common ones like this and the canonical one, then that should cover the 90% case

**Comment by wout** [comment]
Ok, so just now I generated the most common favicons plus their related meta tag and ended up with this:

```cr
private def favicon_tags
  "0.1.0".tap do |version|
    empty_tag "link", rel: "apple-touch-icon", sizes: "180x180",
      href: "/apple-touch-icon.png?v=#{version}"
    empty_tag "link", rel: "icon", type: "image/png", sizes: "32x32",
      href: "/favicon-32x32.png?v=#{version}"
    empty_tag "link", rel: "icon", type: "image/png", sizes: "16x16",
      href: "/favicon-16x16.png?v=#{version}"
    empty_tag "link", rel: "manifest",
      href: "/site.webmanifest?v=#{version}"
    empty_tag "link", rel: "mask-icon", color: "#2a2a2a",
      href: "/safari-pinned-tab.svg?v=#{version}"
    empty_tag "link", rel: "shortcut icon",
      href: "/favicon.ico?v=#{version}"
    meta name: "apple-mobile-web-app-title", content: "TiLiShop"
    meta name: "application-name", content: "TiLiShop"
    meta name: "msapplication-TileColor", content: "#00aba9"
    meta name: "theme-color", content: "#ffffff"
  end
end
```

So I'm thinking now, do we really add all those tags out of the box or should the go in a shard? 

In any case, the above could look like this if you want to write it full-out:

```cr
private def favicon_tags
  apple_touch_icon_tag
  favicon_tags(%w[16x16 32x32])
  site_webmanifest_tag
  mask_icon_tag("#2a2a2a")
  application_name_tags("TiLiShop")
  meta name: "msapplication-TileColor", content: "#00aba9"
  meta name: "theme-color", content: "#ffffff"
end
```

We can also add a macro to make it even more compact:

```cr
icon_package_tags({
  app_name: "TiLiShop",
  favicon_sizes: %w[16x16 32x32],
  mask_icon_color: "#2a2a2a",
  ms_tile_color: "#00aba9",
  theme_color: "#ffffff"
})
```

The macro can check presence of the required files and generate the tags accordingly. That way we can log warnings at compilation time to notify the user about missing files.

The escape hatch would be to not use the `icon_package_tags` macro and just write out the shortcut tags by hand (`apple_touch_icon_tag`, `favicon_tags`, ...).

I deliberately left out file path options because of the following (from the [Real Favicon Generator](https://realfavicongenerator.net) site):
 
> When generating a favicon with RealFaviconGenerator, the instructions ask you to place all files at the root of your web site. You may want to place them in a sub-directory, for example in http://mywebsite.com/icons/, just to make things clearer. However, there are three drawbacks with this approach:
> 
> - Internet Explorer looks for favicon.ico at the root of the web site. Granted: this is because we ask you to not declare favicon.ico.
> - iOS devices look for files such as apple-touch-icon-144x144.png at the root of the web site, as described by Apple. This issue can be mitigated by declaring the icons in the HTML code (this is necessary for Android anyway), but following Apple conventions is probably the best move.
> - By default, Internet Explorer 11 looks for browserconfig.xml at the root of the web site.
> - Several services, such as Yandex, look for favicon.ico in the root directory.

But we can always give the option to configure the icon base path for those who prefer to have them elsewhere:

```cr
apple_touch_icon_tag(dir: "images")
```

Or 

```cr
icon_package_tags({
  dir: "images",
  app_name: "TiLiShop",
  # ...
})
```

What do you think?

**Comment by jwoertink** [comment]
wow... that's crazy. What has happened to our web?! 😂  I was originally thinking just the main one. I've never really used anything else, so I don't know much about them. My main thing is for our app being multitenant, we have multiple sites that each get their own favicon. So we have to generate dynamic assets for those. I don't think we should make a single method that generates all of those because we don't know if someone wants all of them, so maybe having them as individual methods, and then another methods that would add all of them if you wanted? 

Maybe we do make a separate shard for this? It would be a simple shard and easy to maintain, but someone could include it pretty easy.

**Comment by wout** [comment]
What shall we do with these? Do we add some or all of these to Lucky? Or is it too much clutter and shall I make a shard for it?

**Comment by paulcsmith** [comment]
Hmm this is tricky. It may be too much for Lucky core, but maybe not. 

What if you start with a shard and then if people seem to be using it a lot we can bring it into core?

I think we can also document it in our guides even if it is a shard. Something like "favicon tags. See @wout's shard"

**Comment by wout** [comment]
> Hmm this is tricky. It may be too much for Lucky core, but maybe not.

Yeah, exactly my feeling. It's a lot. I'll pour it into a shard and add some useful instructions about how and where to generate the icons. And I was thinking about doing the same for `og`/`twitter` tags.

So we'll have two shards then, called `lucky_icon_tags` and `lucky_social_tags`. But it would also make sense to add everything in one shard, called `lucky_head_tags` or something. I'll have to think about that.

**Comment by wout** [comment]
Better late than never. Here it is:

https://github.com/wout/lucky_favicon.

**Comment by wout** [comment]
@jwoertink shall I include this one in the docs as well?

**Comment by jwoertink** [comment]
I think this is already on https://luckyframework.org/awesome however, rosetta isn't :wink:

**Comment by wout** [comment]
You're right, forgot about that. :blush: 

I'll add Rosetta there as well. Thanks!

**Comment by jwoertink** [comment]
I'm gonna close this out in favor of using the `lucky_favicon` shard. There's just too many options here 😅 The shard covers all of this for us. Thanks @wout!
