### ISSUE TITLE
Add caching to Lucky

### ISSUE THREAD

**Issue by sevensidedmarble** [luckyframework/lucky#1177]
Lucky is making amazing progress but one of the biggest problems yet to be tackled is caching. I don't know if this is a problem that just gets tackled late in a web frameworks lifespan, but none of the major Crystal web frameworks have good application level caching yet. If Lucky can be the first it'll be a big win.

I suggest roughly basing Lucky's approach somewhat on the current situation in Rails 6.

Info on that: https://guides.rubyonrails.org/caching_with_rails.html

## Caching methods that should be supported
- memcached (has crystal bindings)
- redis (has crystal bindings)

I think file system caches and in-database caches are so rarely used the project doesn't need them. I'd also argue that redis is more popular then memcached, so initial implementation could focus just on redis, just like the Lucky project does with postgres.

Native in-memory stores (in this case a crystal hash) are also common implementations.

### Fragment cache

This is in the view layer. They'd be on pages in Crystal.

They look like this in rails:

```ruby
<% @products.each do |product| %>
  <% cache product do %>
    <%= render product %>
  <% end %>
<% end %>
```

So in Lucky I'd expect a syntax like:

```crystal
def render
  products.each do |product|
    cache product do
      render_product
    end
  end
end
```

This would cache the result of the HTML block based on whether or not the updated_at timestamp of the model has changed.

# Low level cache

This example from the Rails docs explains it mostly:

```ruby
 cache_key = "products_v1"
 
 def competing_price
    Rails.cache.fetch("#{cache_key}/competing_price", expires_in: 12.hours) do
      // Do something with model
    end
  end
```
This syntax is just to give you granular control over how you expire caches.

# SQL cache

This is built in to active record, is it built in to Avram?

**Comment by paulcsmith** [comment]
Great suggestions! Luckily with Lucky we would only need the "low-level" cache. Since Lucky pages are just regular Crystal you can use the same syntax in your pages.

For SQL, we have an issue open for that in Avram so it has a per-request query cache: https://github.com/luckyframework/avram/issues/63

I think redis, and in-memory would be great to start. But we can set it up so people can make their own adapters for whatever else they want (like postgres, memcached, etc.)

**Comment by jwoertink** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

So maybe just for an extra level of difficulty, we make this thing a separate shard.... What do we call it? 🤯

**Comment by paulcsmith** [comment]
Yeah separate shard makes sense! It doesn't really need anything for Lucky to use it.

My thought is: CacheMoney

**Comment by jwoertink** [comment]
At my work, anytime someone writes "cache" in slack, a slack bot will automatically return a gif with money 🤑

**Comment by Sevensidedmarble** [comment]
I definitely agree, there should be an implementation of the caching methods themselves that someone can plug different backends into (redis, memcached, whatever).

I would love to try and put together some initial attempts, but I'm still learning a lot about Lucky's internals. The implementation is rather simple, you just need to get the HTML rendered from a block in Lucky's DSL, and do some checking about whether its in the cache or not, if not put it in, if so take it out, etc., but I don't quite see yet how to actually grab the result of the HTML helpers.

**Comment by Sevensidedmarble** [comment]
I have a good bit of stuff working that I can open a PR for soon.

I also found this, which is awesome: https://github.com/crystal-community/kiwi/blob/master/README.md

It's an API to basically every major key value store out there. If we leveraged this there'd be no major work to support multiple kinds of backend stores.

**Comment by Sevensidedmarble** [comment]
Just an update, I'm getting really good time savings even with the tiniest of cached html. I would post some numbers but I also get a lot of fluctuations on page load of around ~10ms on a simple page, so it's hard to say, but there's definitely some good time savings.

**Comment by jwoertink** [comment]
I wonder if there's a way we can do this without modifying any of the HTML methods 🤔

**Comment by Sevensidedmarble** [comment]
I think the answer is no... The tag methods just append strings onto a `view` variable on every page, so there's no way to get more granular bits of html out of the page.

I wanted to change the tags from returning nil to returning their contents as a string, as that would mean the actual cache implementation then didn't even need to be in the tags file at all, but that would involve changing a lot more. If that's acceptable to the project I think that implementation would be cleaner though.

But otherwise yeah, I don't see any other way to get more granular bits of the HTML out of a page as it stands right now without making some changes, unless someone knows something I don't about how it works.

**Comment by paulcsmith** [comment]
Here is what I think could work that would not require changing the HTML methods

```crystal
def cache(key)
  cached_html = get_cached_html(key)
  if cached_html
    raw(cached_html)
  else
    original_view = @view
    # Temporarily override the view
    @view = IO::Memory.new

    yield # This will write to our temporary @view object

    html_fragment = @view.to_s
    save_cached_html(key, html_fragment)
    # Set instance var back to original view
    @view = original_view
    # Write fragment to original view
    raw(html_fragment)
  end
end

# in a page
cache("user-row-#{@user.id}) do
  text @user.name
end
```

I think this should work and keep the HTML tags untouched

**Comment by matthewmcgarvey** [comment]
This library looks like it does all the integration and base interface for us https://github.com/mamantoha/cache

**Comment by matthewmcgarvey** [comment]
Being able to generate a cache key with `Avram::Model`'s seems like it would be a normal want with this and I've been looking into how Rails' does it and it turns out to be fairly complicated. Here's a blog post about it https://bigbinary.com/blog/activerecord-relation-cache-key

**Comment by matthewmcgarvey** [comment]
I made this repo https://github.com/matthewmcgarvey/lucky_cache

It integrates the [cache shard](https://github.com/mamantoha/cache) with our HTML code.

I feel like it really needs to be able to convert `Avram::Model`s into cache keys but looking at how Rails does it seems fairly complicated.

**Comment by Sevensidedmarble** [comment]
https://github.com/crystal-community/kiwi Is another one I would recommend trying out. It had support for googles very performant LevelDB. (https://github.com/google/leveldb)

**Comment by jwoertink** [comment]
This is done now with https://github.com/luckyframework/lucky_cache/ being added in. We still need to document how to use it https://github.com/luckyframework/website/issues/894 but we at least have something started. We can now start building it up, and fix issues along the way.

I'm going to close this, but if anyone feels there's more we can do related, we can always re-open.
