### ISSUE TITLE
Support namespaces on model generator

### ISSUE THREAD

**Issue by fernandes** [luckyframework/lucky#1184]
Right now (on version 0.21) if we use the generator for a namespaced model, we get an error like this:

> $ lucky gen.model Blog::Post title:String
> Model name should only contain letters. Example: lucky gen.model BlogPost

so the idea is to support the namespace

**Comment by wout** [comment]
I'm also namespacing some models and I put them in in a sub dir. For example:

```cr
# src/models/product.cr
class Product < BaseModel
  # ...
end

# src/models/events/product_event.cr
class Events::ProductEvent < BaseEvent
  # ...
end
```

So I'm wondering, do we follow that pattern?
