### ISSUE TITLE
crystal 0.34.0 + lucky 0.21 broken due to dependency changes for crystal 0.35.0 support

### ISSUE THREAD

**Issue by jonbeebe** [luckyframework/lucky#1185]
lucky 0.21 generated project specifies jwt dependency `~> 1.4.0` and also has an indirect dependency of bindata which will download and install jwt 1.4.2 and bindata 1.5.4:

https://github.com/crystal-community/jwt/releases/tag/v1.4.2
https://github.com/spider-gazelle/bindata/releases/tag/v1.5.4

The above includes a changes to be compatible with the newly released crystal 0.35.0. The issue can be reproduced by creating a new lucky project and running `lucky dev` (compile fails).

The dependency should be pinned to 1.4.1 until lucky is made to be compatible with crystal 0.35.0:

Changing: `~> 1.4.0` to `<= 1.4.1` under `jwt` dependency fixes the issue in lucky 0.21

However, build still fails because an indirect dependency (bindata) is also incompatible due to a recent 1.5.4 release that includes a breaking crystal 0.35.0 change.

Making the above change to jwt dependency and adding bindata as a direct dependency pinned to 1.5.3 allows `lucky dev` to compile and run successfully:

```
bindata:
  github: spider-gazelle/bindata
  version: <= 1.5.3
```

**Comment by paulcsmith** [comment]
Thanks for reporting this! A new release of Lucky is out. You should be able to use the UPGRADE_NOTES here and use Lucky 0.22 with Crystal 0.35.0

https://github.com/luckyframework/lucky/pull/1190/files
