### ISSUE TITLE
Dependencies broken in master

### ISSUE THREAD

**Issue by bcardiff** [luckyframework/lucky#1196]
shard.yml in master states that:

```
  lucky_cli:
    github: luckyframework/lucky_cli
    branch: pcs/crystal-0.35
```

But that branch does not exist. Should 5d790738a2d3acfcbe457258d7bee690cebd6e57 be cherry-picked?

Also, what does `pcs/` stands for?

**Comment by jwoertink** [comment]
Yeah, I'm working on fixing that. `PCS` is @paulcsmith initials. Paul C Smith 😄 
We are doing another release that's going to have a ton of new features and stuff 😁

**Comment by jwoertink** [comment]
@bcardiff I just merged in a few things if you want to give it a shot with your code.

**Comment by bcardiff** [comment]
Yeap, things are working for me now. Thanks!

**Comment by jwoertink** [comment]
sweet!

**Comment by bcardiff** [comment]
Sorry, 1 more https://github.com/luckyframework/lucky_cli/blob/a818f3ae264d04cef2891006ca0aa721bb2070b2/src/generators/web.cr#L159 🙈

**Comment by jwoertink** [comment]
oops! 😅  Sorry about that.

**Comment by jwoertink** [comment]
@bcardiff I pushed up this PR https://github.com/luckyframework/lucky_cli/pull/525 to fix some versions and stuff, but I think our specs are breaking. For now, if you generate a new app off master, you should be able to just update that in the shard.yml file to point to `~> 0.22.0` and try it out. That release is Crystal 0.35 compatible. I'll try to get this update out soon though.

**Comment by bcardiff** [comment]
No worries. It's just a heads up. On minor releases I usually patch all dependencies, but for a minor release I was avoiding that. But I wanted to notify about non existing branches as dependencies no master. I am not blocked.

**Comment by jwoertink** [comment]
oh good. Yeah, I just wanted to make sure you weren't being held up. 👍
