### ISSUE TITLE
Allow override for displaying default parameters in path URL?

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/lucky#1201]
> Note from maintainers. The behavior should be that the query parameters are shown in the path if they are explicitly passed to the path generators, otherwise they remain off the path as it is today

Currently, if you link to an action with default parameters and your `with` params are the same as the defaults, it won't be rendered in the URL. Here's where that's defined:
https://github.com/luckyframework/lucky/blob/master/src/lucky/routable.cr#L257

This works great for something like pagination, where I don't want to show `page=1` on every page, even if I `link to: Home::Index.with(page: 1)` from another page.

However, I'd posit the idea that the URL is, in fact, part of the user interface, and that Lucky users should be able to decide whether or not those parameters are stripped.

For example, take [LuckyDiff](https://luckydiff.com).
Visiting ^ that URL takes you to the URL "luckydiff.com", when the intention is really that the parameters `from` and `to` are always populated. This would make it more intuitive to share links between people, and allow URL-savvy users to change versions directly in the URL more intuitively.
Clicking the "Compare" button with the **same** versions, however, **will** generate the parameters in the URL.

Here's some code:
- the Homepage action of LuckyDiff [here](https://github.com/stephendolan/lucky_diff/blob/master/src/actions/home/index.cr)
- the NavBar link that **doesn't** generate params in the URL [here](https://github.com/stephendolan/lucky_diff/blob/master/src/components/shared/navbar.cr)
- the form that does show default params in the URL [here](https://github.com/stephendolan/lucky_diff/blob/master/src/pages/versions/compare_page.cr)

All that provided, I guess it boils down to three questions:

1. Should the behavior to ignore default parameters from showing in the URL be "off" or "on" by default?
1. Should users be able to override this default, or is that even possible to do intuitively in `with` or within an action itself?
1. If nothing changes, should the behavior be consistent between `with` and `get` forms to the same URL with the same parameters?

**Comment by paulcsmith** [comment]
Ah I think I get it now. This code `Home::Index.with(from: default_from, to: default_to)` is ignoring the `from/to` since the query params match the defaults. 

If that is the case, then I would consider that a bug. If the user explicitly provides a param value it should be in the generated path/URL even if it matches the defaults

**Comment by paulcsmith** [comment]
Also worth noting that the paginator has its own logic for not adding `page=1` https://github.com/luckyframework/lucky/blob/071eb1075cddf53156a3afebe9042f61f3ce69d4/src/lucky/paginator/paginator.cr#L64-L80. So changing this should not affect anything negatively. To me it is expected that if you pass a value to the query param it should show up (like it does for the form) 👍
