### ISSUE TITLE
Add support for multi-file uploads in Lucky::Params

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1208]
## The problem
As it is right now, `Lucky::Params` can only deal with single-file uploads. In other words, one file per file input in a form. But file inputs have a `multiple` attribute, which allows the user to select more than one file for a single input. Currently there is no way to access those files from `Lucky::Params`.

## Proposal
There are already the `many_nested` and `many_nested?` methods to deal with arrays of parameters. My proposal is to add `many_nested_files` and `many_nested_files?` as well, which return `Array(Hash(String, Lucky::UploadedFile))`. Most of the patterns are already there in `nested_file` and `many_nested`, so it won't be too hard to implement. Once that's done, I can update Avram accordingly so it can cast an array of file hashes.

For me personally it's crucial to have this because two large Lucky projects we're working on revolve heavily around file uploads. I can work on it today and tomorrow, if necessary, and submit a PR this week.

**Comment by jwoertink** [comment]
This exists now. https://github.com/luckyframework/lucky/blob/de058b2e827385eb5c45d55bc85823c3fdca5554/src/lucky/params.cr#L327

The only real parts to this that are missing is using it in an Avram::Operation, and using it in an HTML form. You'd have to manually build out your HTML, and then manually pull it out from the Operation side to use it. I think we can close this out though as the other parts are sort of different issues.

**Comment by wout** [comment]
Yes, this is done. The other parts you mention are something I'm still figuring out. I'd like to implement `Shrine::Attachment` in shrine.cr, so we can implement the Lucky equivalent of this Rails example:

```
class Photo < ActiveRecord::Base # has `image_data` column 
  include ImageUploader::Attachment(:image) # adds methods, callbacks & validations 
end
```

That's something for January.
