### ISSUE TITLE
send_text_response returns a 100 by default which can break some apps

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1213]
https://github.com/luckyframework/lucky/blob/master/src/lucky/renderable.cr#L215

This got updated to set the default to 100, but should just be set to `nil` like before. Unless anyone can think of a specific reason why a 100 default makes more sense? 

/cc. @wout

**Comment by wout** [comment]
Not sure how that came there, but I recall finding `100` odd being there. I'll fix it unless anyone else disagrees of course.

**Comment by jwoertink** [comment]
Ok, cool. As long as you didn't have a specific reason it needed to be there. We can just set it back to nil 👍
