### ISSUE TITLE
Rename `m` to `mount`, but keep signature

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1221]
https://github.com/luckyframework/lucky/issues/1049#issuecomment-653904514
https://github.com/luckyframework/lucky/issues/1215#issuecomment-661930262

**Comment by stephendolan** [comment]
@paulcsmith / @jwoertink Were one of you already working on this in a branch, or could I take a swing at it if I find some time this weekend?

**Comment by jwoertink** [comment]
I'm not. Feel free to have at it!

**Comment by paulcsmith** [comment]
@stephendolan that'd be great! Thanks!
