### ISSUE TITLE
Add Travis config

### ISSUE THREAD

**Issue by igor-alexandrov** [luckyframework/lucky#1225]
Why don't Lucky have a Travis CI config?

I believe we should build all Lucky components after each commit as well as have a periodical builds against latest stable and nightly Crystal versions.

What do you think?

**Comment by igor-alexandrov** [comment]
Just understood, what Lucky has GitHub Actions configured. Is there a Badge that can be added to the Readme?

**Comment by paulcsmith** [comment]
@igor-alexandrov I'm not sure if there is a badge, but in general we don't add CI badges to readme so I think we're ok without it.

I'll go ahead and close this for now since we have CI setup and moved from Travis

**Comment by igor-alexandrov** [comment]
Got it. Thanks.
