### ISSUE TITLE
Attempting to use dashes in path variable naming produces unhelpful error

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky#1235]
Say I try to define a route like:

```ruby
get "/users/:user-id" do
  ...
end
```

It currently produces an error like:

```
There was a problem expanding macro 'add_route'

Code in macro 'match'

 5 | add_route(:get, "/users/:user-id", Users::Show)
     ^
Called macro defined in src/lucky/routable.cr:191:3

 191 | macro add_route(method, path, action)

Which expanded to:

 >  7 |     
 >  8 |       
 >  9 |       def user-id : String
                      ^
Error: unexpected token: -1
```

It would be more helpful for users to check the path variable's format before trying to generate the methods and produce a descriptive error if they stray down this path.

**Comment by paulcsmith** [comment]
Nice! Thanks for opening this. I totally agree we should check for that and raise a better error
