### ISSUE TITLE
Flash messages are not kept with a specific redirect method

### ISSUE THREAD

**Issue by confact** [luckyframework/lucky#1248]
I notice this when I did redirect and forgot to add `to:` to the method. It won't keep the flash messages and they will disappear.

Example on failing code:
```crystal
flash.keep
flash.info = "Test message"
redirect Users::Show
``` 

If I use `to:` param in the method, it will work:
```crystal
flash.keep
flash.info = "Test message"
redirect to: Users::Show
```

These must be overloaded methods and been missed when adding these flash improvements :)

**Comment by jwoertink** [comment]
It looks like they both call the same method https://github.com/luckyframework/lucky/blob/master/src/lucky/redirectable.cr#L101, and `redirect` calls `flash.keep` already https://github.com/luckyframework/lucky/blob/master/src/lucky/redirectable.cr#L124 ... Does this work if you don't call `flash.keep` manually? 🤔

**Comment by stephendolan** [comment]
I've found this to be a bit inconsistent, as well. I had trouble digging through the source specifically, but there have been times where I write a flash message without `flash.keep`, and neither `redirect #{PATH}` nor `redirect to: #{PATH}` will maintain the flash messages.

Latest example was one I ran into with adding email confirmations in Lucky Jumpstart:
https://github.com/stephendolan/lucky_jumpstart/blob/user-email-confirmation/src/actions/sign_up_confirmation_requests/create.cr#L14

**Comment by matthewmcgarvey** [comment]
I believe this problem should be fixed. We shipped some major changes to how flashes work in Lucky 0.26 that addressed a couple problems
