### ISSUE TITLE
include Lucky::Memoizable in Object so it usable everywhere 

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1253]
https://github.com/luckyframework/lucky/blob/master/src/lucky/memoizable.cr is only included in actions but we should add it o an `object_extensions` charm instead https://github.com/luckyframework/lucky/blob/master/src/charms/object.cr

**Comment by jwoertink** [comment]
😂  https://github.com/luckyframework/lucky/issues/1095

**Comment by paulcsmith** [comment]
Whoops!
