### ISSUE TITLE
JsonBodyParser should use body string from Params class

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky#1257]
`Lucky::JsonBodyParser` current has its own [body method](https://github.com/luckyframework/lucky/blob/face632c8adcb700a4fc2eeff13931eb4547b380/src/lucky/json_body_parser.cr#L18-L20). It is not memoized so that method is run twice. That is twice more than is needed. If it took in the body it could utilize the memoized body method found in `Lucky::Params`.

There are also several methods in the Params class that are using the old form of memoization.

**Comment by jwoertink** [comment]
https://github.com/luckyframework/lucky/issues/1075
