### ISSUE TITLE
Let HTML tags support hash as parameter without block

### ISSUE THREAD

**Issue by confact** [luckyframework/lucky#1263]
Hi

I have big issues with dynamic parameters when rendering HTML tags - I thought I was forced to use NamedTuple which doesn't work as It is very static and I can't set parameters for div tags based on params or parameters in components. It just won't let me.

I tried using a macro to generate NamedTuple, obviously in vain as it doesn't work:
https://gist.github.com/confact/0b07cd259a6fdfadd41008a5ffb72d02

So I wrote in Crystal gitter and we figured div and HTML tags support hash as parameter IF block is added.

so this won't work:
```
div a_hash_var
```
but this will work:
```
div a_hash_var do
end
```

I thought hash was not supported as I didn't try with a block.
This would be nice to be fixed and documented :)

**Comment by jwoertink** [comment]
I have a feeling you could also do `div "", a_hash_var` and that would work. It looks like we just don't have an overload for that one. We would need [this](https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/base_tags.cr#L42) but without the block
