### ISSUE TITLE
Security bug: HSTS header is sent over HTTP and not HTTPS

### ISSUE THREAD

**Issue by ZimbiX** [luckyframework/lucky#1267]
Lucky's [`ForceSSLHandler` class](https://github.com/luckyframework/lucky/blob/master/src/lucky/force_ssl_handler.cr) adds the HTTP Strict Transport Security (HSTS) header to HTTP requests only, when it needs to instead add it to HTTP**S** requests only.

---

I discovered this after enabling the force TLS redirect and HSTS settings as documented in the generated [`config/server.cr`](https://github.com/luckyframework/lucky_cli/blob/3258f543b8ca91a2815cac5ca75dcee72228598d/src/web_app_skeleton/config/server.cr.ecr#L38-L47), using:

```crystal
Lucky::ForceSSLHandler.configure do |settings|
  settings.enabled = Lucky::Env.production?
  settings.strict_transport_security = {max_age: 1.year, include_subdomains: true}
end
```

I was looking into submitting my site for the HSTS preload list (so that on supported browsers, an insecure request doesn't need to be made at all), when I found my site was ineligible. The [result](https://hstspreload.org/?domain=luckyframework.org) is the same for Lucky's site:

![Screenshot from 2020-09-22 20-12-21](https://user-images.githubusercontent.com/2916331/93870026-fbdb2000-fd0f-11ea-9f0a-14ecb088cc6a.png)

The information provided in that message and the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#Description:~:text=Note%3A%20The%20Strict%2DTransport%2DSecurity%20header%20is%20ignored,and%20will%20honor%20the%20Strict%2DTransport%2DSecurity%20header.) (which are linked to [from the Lucky docs, ironically](https://luckyframework.org/guides/http-and-routing/security-headers#forcing-ssl-and-hsts)) says that the HSTS header needs to be provided when the site is requested over HTTPS only. Which makes sense, as an HTTP request could be tampered with to remove the header.

I checked what the current behaviour is:

```
➜ curl -I luckyframework.org         
HTTP/1.1 308 Permanent Redirect
Server: Cowboy
Date: Tue, 22 Sep 2020 09:55:19 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31104000; includeSubDomains
Location: https://luckyframework.org/
Content-Length: 0
Via: 1.1 vegur

➜ curl -I https://luckyframework.org
HTTP/1.1 200 OK
Server: Cowboy
Date: Tue, 22 Sep 2020 09:55:25 GMT
Connection: keep-alive
Content-Type: text/html
Transfer-Encoding: chunked
Set-Cookie: _website_v2_session=bHVja3k%3D%0A--epgdvfAmkR4kgescH8frKE05vnnMfTKAob1Q5VYO%2FX2EnmB6QuJh54pQudlnpzw%2BS8DRPIdpwBtsYloC5zk8b4%2FRmQWCDGQNeZOyMd1eyZEb7eBdukOZoEbb4IkH%2Fi8z; path=/; Secure; HttpOnly; SameSite=Lax
Via: 1.1 vegur
```

And yes, the `Strict-Transport-Security` was present in the wrong response.

Fixing it should be relatively simple, even for a Crystal-newbie like myself, so I'll start on a PR now.

btw, you folks really should provide info on somewhere to report security vulnerabilities =P e.g. https://securitytxt.org/

Cheers for the awesome framework!

---

CC @jwoertink - just a heads up since you implemented it in https://github.com/luckyframework/lucky/pull/734 ;)

**Comment by jwoertink** [comment]
😅  figures I'd miss something lol. Thanks for catching this!
