### ISSUE TITLE
Cookie is getting set if raising "LuckyNotFoundError" even if disable_cookies are set

### ISSUE THREAD

**Issue by confact** [luckyframework/lucky#1272]
I am building an API and noticed if I throw NotFoundError on entity not found as usual it is setting a cookie even if `disable_cookies` is set in that action.

my ApiAction:
```
# Include modules and add methods that are for all API requests
abstract class ApiAction < Lucky::Action
  disable_cookies
  accepted_formats [:json]

  include Api::Auth::Helpers

  # By default all actions require sign in.
  # Add 'include Api::Auth::SkipRequireAuthToken' to your actions to allow all requests.
  include Api::Auth::RequireAuthToken
end
```
I would call this a security/privacy issue.

**Comment by confact** [comment]
Found out that it can be fixed by adding `disable_cookies` to Errors::Show action

Maybe a better solution would be to let it take settings from the action the exception was thrown from?
disable_cookies should work fine like this but for other settings (subdomain etc) later it would be nice.

You can close this if you feel this is fixed.

**Comment by jwoertink** [comment]
Yeah, that makes sense since the ApiAction and the ErrorAction are two different classes. I guess you'd have to know to disable in both which we would need to document. Is there a better way to handle it? Maybe up higher at the middleware handler stage?

**Comment by paulcsmith** [comment]
I think we should keep this as-is and add some info to the `disable_cookies` parts of docs and guides that says you'll need to do it in Errors::Show as well. Alternatively we could disable cookies by default in Errors::Show but I think that is probably a surprising default. 

So I think adding to docs, and maybe adding some comments in LuckyCLI so the generated Errors::Show has it commented out with a brief explanation. Similar to https://github.com/luckyframework/lucky_cli/blob/0efe5e465fb22555fa3b92c5dcb8d0eebd30fe62/src/web_app_skeleton/src/actions/api_action.cr.ecr#L3-L5

How does that sound?

**Comment by dammer** [comment]
> I think we should keep this as-is and add some info to the `disable_cookies` parts of docs and guides that says you'll need to do it in Errors::Show as well. Alternatively we could disable cookies by default in Errors::Show but I think that is probably a surprising default.
> 
> So I think adding to docs, and maybe adding some comments in LuckyCLI so the generated Errors::Show has it commented out with a brief explanation. Similar to https://github.com/luckyframework/lucky_cli/blob/0efe5e465fb22555fa3b92c5dcb8d0eebd30fe62/src/web_app_skeleton/src/actions/api_action.cr.ecr#L3-L5
> 
> How does that sound?

Adding `disable_cookies` to Errors::Show does not work in develepment mode because ```settings.show_debug_output ``` enabled by default, and ```Lucky::TextResponse``` in ```render_exception_page``` not use ```enable_cookies: enable_cookies?```.
```  
def render_exception_page(error : Exception, status : Int) : Lucky::Response
    Lucky::TextResponse.new(
      context: context,
      status: status,
      content_type: "text/html",
      body: Lucky::ExceptionPage.for_runtime_exception(context, error).to_s
    )
  end
 ```
This is a small problem, but it's better to write it down in the documentation and save someone some time on a cup of coffee)
