### ISSUE TITLE
Make `watch` task Alpine / BusyBox friendly

### ISSUE THREAD

**Issue by KCErb** [luckyframework/lucky#1274]
Turns out the `watch` task won't run on Linux Alpine (i.e. common Docker base) due to:

1. The `lsof` command is too simple. So the browsersync detection, which looks for an empty string. Doesn't work:
https://github.com/luckyframework/lucky/blob/8ca0211fba3fbf88598edeb16aabd7ca9ffdaaed/tasks/watch.cr#L69-L70

2. `ps` doesn't have a `-p` option when trying to report the above error:
https://github.com/luckyframework/lucky/blob/8ca0211fba3fbf88598edeb16aabd7ca9ffdaaed/tasks/watch.cr#L78

There are a couple of options to address this.

One is to use something busybox friendly like `netstat` and generally use tools like `grep` instead of nice features that come with full-featured `ps`, `lsof` and friends.

Another is to permit some kind of `Docker` flag that basically says "You're in an isolated environment that has to be pre-engineered for Lucky anyways, let's just skip these checks".

I lean towards option 2 since I'm also skipping the `system check` line in my procfile anyways. For now, I'm probably going to add `apk add lsof` to the Dockerfile and consider it a hard dependency.

I'll update this issue with any other BusyBox issues I find.

**Comment by matthewmcgarvey** [comment]
Different command but related issue https://github.com/luckyframework/lucky/issues/1255

**Comment by KCErb** [comment]
Actually, I think it's the same issue and the same command. Should've tried another search term besides Docker 😊  

I'll close but please let me know if you'd rather it was open.
