### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by benchmarktoday** [luckyframework/lucky#1277]
Sorry for ask a general question in this repo as I don't like to discuss in Discord, I found Lucky web framework is on the last row of all ranks (Position 191 out of 191) and right below Laravel.

I like to learn in what ways it's fast or assume the configuration might have been wrong configured? Should be somewhere near Amber web framework?

https://github.com/the-benchmarker/web-frameworks

Filed this as question on "performance issues" since your readme indicates "...forget about most performance issues..."

**Comment by jwoertink** [comment]
Hey! Welcome to Lucky. You are correct, we're in last place. (or first, if you look at it in reverse order).... That's intentional. Because in last place, we're easily recognizable 😉 

Joking aside, Lucky is definitely fast, and a lot faster than that benchmark repo shows. If you look at all of the examples in there, it benchmarks time to return a head response or just return plain text. It's not a very strong benchmark because it doesn't account for any database queries, or rendering HTML. It doesn't really account for going through a standard middleware stack, or how responding with JSON might be. So essentially it's just benchmarking routing. 

I'd love for you to give lucky a shot, and build a simple "Hello world" that's rendered to an HTML page, and then benchmark that. Run `wrk -t 2 -c 10 http://localhost:5000` and see how many req/sec you get. Feel free to post those results here even. From that number, you will be able to see how fast Lucky actually is 😄

**Comment by benchmarktoday** [comment]
Sure! I love to post benchmark solely at your invitation and intend to post my Go language. While a big gap between non-web framework and web framework (lots of layers) can be found in benchmarks, is not authoritative by any means or indicates which is faster. I have not tried Crystal web framework for years but I still have a basic knowledge on Crystal language.

Pop_OS! Ubuntu, optimize for gaming and pleasant desktop experience
Macbook Pro early 2015
Intel Core 2.70GHz
8.0GB Memory RAM

To set up Lucky web framework and installing Crystal development tools took me some 30 mins.

Using Lucky Project
:> lucky init.custom my_app --no-auth

:> crystal build --release src/start_server.cr

:> LUCKY_ENV=production SECRET_KEY_BASE=e...= DB_URL=a PORT=9090 HOST=localhost SEND_GRID_KEY=a APP_DOMAIN=localhost ./start_server &

reuse_port set to true and launch 8's start_server instances
Commented all middleware except Lucky::RouteHandler.new
Modified index route to: plain_text "Hello World!"
Output on web page: Hello World!

Crystal release 0.35.1 (Latest release) with LLVM 8.0.0
Lucky release 0.24 (Latest release)
```
wrk -t 4 -c 100 --latency http://localhost:9090
Running 10s test @ http://localhost:9090
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    45.28ms  147.01ms   1.84s    92.39%
    Req/Sec    14.41k     4.56k   25.00k    67.50%
  Latency Distribution
     50%  797.00us
     75%    7.16ms
     90%  111.02ms
     99%  726.07ms
  573890 requests in 10.01s, 164.19MB read
Requests/sec:  57327.14
Transfer/sec:     16.40MB
```
I think there're rooms for more throughput? :thinking:

Reuse_port set to false, only one start_server instance is running:
```
Running 10s test @ http://localhost:9090
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.71ms  480.72us  14.32ms   76.02%
    Req/Sec     6.76k   411.69     7.63k    66.00%
  Latency Distribution
     50%    3.66ms
     75%    4.01ms
     90%    4.26ms
     99%    4.71ms
  269225 requests in 10.00s, 77.03MB read
Requests/sec:  26915.44
Transfer/sec:      7.70MB
```

Took me around 5 mins to install and copy web server code from Go website:
Golang 1.15.2 on Linux
Use net/http, other HTTP library should give higher throughput.
Output on web page: Hello World!
```
./wrk -t 4 -c 100 --latency http://localhost:8080/world
Running 10s test @ http://localhost:8080/world
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.48ms    1.95ms  32.15ms   89.18%
    Req/Sec    23.45k     4.69k   36.14k    70.25%
  Latency Distribution
     50%  793.00us
     75%    2.05ms
     90%    3.57ms
     99%    9.42ms
  938699 requests in 10.08s, 116.38MB read
Requests/sec:  93125.22
Transfer/sec:     11.55MB
```

Thanks @jwoertink

**Comment by jwoertink** [comment]
That's awesome! I'd say 57k req/sec is pretty darn fast! And considering Crystal or Lucky hasn't hit 1.0 yet, we have plenty of optimizing we can do to get even better. Thanks for giving that a shot and posting those numbers! I'll close this ticket out, but if you have any more questions feel free to open it back up, or ping me!

**Comment by benchmarktoday** [comment]
The ideal optimization is to get rid of LLVM and OpenSSL, both are essential for Crystal and are widely used. It's a problem to have as far as I know some of folks have build solutions with Crystal for their clients/businesses and it's workable. It's tedious to build for a simple and fast moving projects. Probably why it took so long for Crystal to move towards 1.0 at slow pace.

Writing elegant code like Crystal should have been easier to build, I guess the core team already sail to far into the uncharted territory, build a new island is worth considering.
