### ISSUE TITLE
No way to modify the Content-Type header to include charset

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky#1278]
Since my issue is connected to rendering HTML, I will be using that content type but all of them should be accessible

Right now the content type header is set in an inconvenient place to allow for customizing
https://github.com/luckyframework/lucky/blob/8ca0211fba3fbf88598edeb16aabd7ca9ffdaaed/src/lucky/renderable.cr#L85

When I call `html Users::Index`, it returns a response with a `content-type` header of `text/html` but I need it to be `text/html; charset=utf-8`.  Is there any way we could expose this for customizing or provide a way of setting a charset?

**Comment by jwoertink** [comment]
We could probably add an extra argument or something, but the `html` method is a bit unique. The other ones you'd normally just `send_text_reponse` and do your custom content-type. In this case, you can actually override it in an `after` pipe.

```crystal
after set_new_content_type

private def set_new_content_type
  response.headers["Content-Type"] = "text/html; charset=utf-8"
  continue
end
```

What if we just made it always return the charset? Then had that globally configurable? So even json would return `application/json; charset=utf-8`? I've seen that done before. Then you wouldn't need to change anything, and if you needed your app to be in latin encoding, you'd just configure that at the server level.... 🤔

**Comment by matthewmcgarvey** [comment]
Good call on the after pipe. I monkey-patched TextResponse to get it working 🙈

**Comment by matthewmcgarvey** [comment]
For the record, the after pipe doesn't work because the content type is set in `Lucky::TextResponse` after after pipes are run https://github.com/luckyframework/lucky/blob/8ca0211fba3fbf88598edeb16aabd7ca9ffdaaed/src/lucky/text_response.cr#L23-L33

and there's no way to access the result of the TextResponse to update the content type in there.

**Comment by jwoertink** [comment]
😅  oops! Ok, that's definitely an issue then. You should be able to override response headers before sending out the final bit. We may need to move some stuff around a bit to make that better. I'm not completely sold on just adding an argument to the method, but maybe we can rethink the whole flow? 🤔

**Comment by paulcsmith** [comment]
I'm thinking we add a method to Lucky::Action called `html_content_type`. It can then be overriden in the base action and it'll be applied for all actions. Or can be overridden per-action.

Also I think we should change the default to be utf-8 charset anyway right? Seems like that might make more sense and avoid issues with utf-8 characters

**Comment by jwoertink** [comment]
Closing in favor of https://github.com/luckyframework/lucky/issues/1580
