### ISSUE TITLE
Remove unnecessary header parsing

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1302]
We are parsing this data to get some information like `filename`
https://github.com/luckyframework/lucky/blob/c094df34b1a5c79e846081c453e5a7ac37072313/src/lucky/uploaded_file.cr#L19-L20

but `part` actually gives us all of this data already.
https://github.com/crystal-lang/crystal/blob/5999ae29beacf4cfd54e232ca83c1a46b79f26a5/src/http/formdata/part.cr#L3-L11

We should just make `part` an instance variable, then delegate all these methods to it. I'm not sure how "slow" that parsing is, but there's no reason to do it twice per upload.

**Comment by matthewmcgarvey** [comment]
It might make sense to remove metadata and add the missing methods from part to this file. But Avram would need to be updated first.
