### ISSUE TITLE
No way to expose predicate methods

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1304]
**Describe the bug**

```crystal
class BrowserAction < Lucky::Action

  expose logged_in?

  def logged_in?
    !!current_user?
  end
end

class MainLayout
  # this throws an error because needs can't end in question mark
  # since we generate this for bools for you
  needs logged_in? : Bool

  # this throws an error that `logged_in` isn't being exposed
  needs logged_in : Bool
end
```

**Workaround**

```crystal
class BrowserAction < Lucky::Action
  expose logged_in

  def logged_in
    !!current_user?
  end
end
```

**Comment by matthewmcgarvey** [comment]
The difficulty with this is that the action is that the page/layout is not actually "calling" those methods. Any defined `needs` are expected to come in through the `initialize` method. The `expose` macro is adding type declaration of things it will pass into the `new` call on the page.

**Comment by jwoertink** [comment]
Yeah, we may just go the route of saying that you don't expose predicate methods so calling `expose logged_in?` would raise a compile-time error saying to not do that, and how to accomplish what you need.
