### ISSUE TITLE
Multiline headers don't work

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#1310]
The Content Security Policy header "Report-To" is usually multiline. Examples are [here]( https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to), one is:
```
Report-To: { "group": "csp-endpoint",
             "max_age": 10886400,
             "endpoints": [
               { "url": "https://example.com/csp-reports" }
             ] },
           { "group": "hpkp-endpoint",
             "max_age": 10886400,
             "endpoints": [
               { "url": "https://example.com/hpkp-reports" }
             ] }
Content-Security-Policy: ...; report-to csp-endpoint
```

So, I tried to code this as:

```crystal
policy = <<-END
<multi-line content>
END
request.headers.add("Report-To", policy)
```
 And I get this complaint:
```
GET /dynamic/en-US/edit/page/1?_csrf=
 ▸ Handled by Action::Edit::Page::Edit
 ▸  ArgumentError 

     Header content contains invalid character '\n'

    Backtrace 

     ../../../../../usr/share/crystal/src/http/headers.cr:337:7 in 'check_invalid_header_content'
     ../../../../../usr/share/crystal/src/http/headers.cr:122:5 in 'add'
```

**Comment by jwoertink** [comment]
This is actually an issue directly in Crystal https://play.crystal-lang.org/#/r/9ylv We just use the built-in `HTTP::Headers`. Would you mind opening an issue on the main crystal repo? 

For the time being, your JSON value doesn't have to contain newlines. That's just for readability purposes. You can still set it in one line as a valid header.

```crystal
headers["Report-To"] = {group: "csp-endpoint", max_age: 10886400}.to_json
```

**Comment by BrucePerens** [comment]
Moved to https://github.com/crystal-lang/crystal/issues/9961
