### ISSUE TITLE
lucky gen.model missing datatypes

### ISSUE THREAD

**Issue by watzon** [luckyframework/lucky#1311]
Don't know if this belongs here or in Avram, feel free to move it. When running `lucky gen.model Media asset_data:JSON::Any` I get the error:

```
Unable to generate model Media, the following columns are using types not supported by the generator:

  asset_data:JSON::Any


The supported types are Bool, Float64, Int16, Int32, Int64, String, Time, UUID

For more complex types that can be added to your migrations manually, see https://luckyframework.org/guides/database/migrations#add-column for more details.
```

When visiting the link though it clearly shows `JSON::Any` as an acceptable type

**Comment by jwoertink** [comment]
This is a tricky one. Originally that task couldn't support generating `JSON::Any`, so we had a special error to catch that https://github.com/luckyframework/lucky/blob/master/spec/tasks/gen/model_spec.cr#L80 but then we added this new error to catch for some other things. Now I think we may be able to support JSON::Any in the generator, and it just needs to be added here https://github.com/luckyframework/lucky/blob/master/tasks/gen/mixins/migration_with_columns.cr#L2... 🤔
