### ISSUE TITLE
Missing macros for some html tags

### ISSUE THREAD

**Issue by rmarronnier** [luckyframework/lucky#1316]
It seems `<blockquote>` and `<cite>` don't have their respective macros. Should we give them some magic love ?

**Comment by jwoertink** [comment]
Yup. Just need to add them here https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/base_tags.cr#L3 thanks for catching that!

**Comment by rmarronnier** [comment]
Nice ! I'll try to make a PR.
