### ISSUE TITLE
Unable to use :ajax as an accepted format

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1320]
**Describe the bug**
 In your Actions, you could respond to different formats based on the accepted format. Normally it might just be `html`, but you may have something that looks like:

```crystal
get "/me" do
  if ajax?
    json({email: current_user.email})
  else
    html ShowPage
  end
end
```

**To Reproduce**

```crystal
accepted_formats [:html, :ajax], default: :html
```

**Temp Fix**
You can add a temp fix by creating a `config/mime_type.cr` file

```crystal
# config/mime_types.cr
Lucky::MimeType.register "text/plain", :ajax
```

But we should add it here https://github.com/luckyframework/lucky/blob/b6f68bdc78b0b6831e801cac3ba0c97f83159e81/src/lucky/mime_type.cr#L7-L22

From search around the internet, ajax requests don't seem to have a specific content type, so `text/plain` should be fine unless anyone has something specific they know of?

**Comment by oivoodoo** [comment]
Hi @jwoertink . I am new in crystal and lucky but it looks weird `text/plain` register as an ajax request. Probably you do any kind of the requests you can respond with something depends on content-type:

```
accepted_formats [:html, :json], default: :html

 get "/me" do
  if json?
    json({email: current_user.email})
  else
    html ShowPage
  end
end
```

or even it could be like rails does:

```
respond_to do |format|
format.json do
end

format.html do
end
end
```

not sure if it expected behaviour anyway.

**Comment by jwoertink** [comment]
Hey @oivoodoo Welcome to Lucky! 

Yeah, the code example you wrote already works as is. If you're doing making an API call from your javascript and sending json, you'd use `:json` as your accepted format. If you're sending xml, you could use `:xml` as your accepted format (provided you're also sending the correct content-type). However, if you're not doing one of those or some other structured format, then you may want to use `:ajax`. I think @fernandes ran in to this issue which is why it was added. We had talked about it just being plain text, but maybe he can expand on why that one?

With that said, my little research didn't give me too many solid answers. Maybe `ajax` just works as an alias to `json`? 🤔  🤷‍♂️

**Comment by fernandes** [comment]
hello!

first we need to be aware that these are two kind of requests, JSON requests, set by `content-type` as `application/json` and AJAX requests (`XMLHttpRequest`, that sets HTTP Header  `X-Requested-With` as `XMLHttpRequest`

the second one can return XML, JSON or even HTML (that's why the mime type is set as `plain/text` as default), while the first only JSON

even rails differentiate on `respond_to` with `format.json` for JSON requests and `format.js` for `XMLHttpRequest`

does it makes sense?

**Comment by oivoodoo** [comment]
@fernandes everything sounds reasonable. now it's clear why it would require to `ajax`.

**Comment by fernandes** [comment]
@oivoodoo great :)

**Comment by yummyweb** [comment]
<button>Hey</button>

**Comment by yummyweb** [comment]
<button onclick="alert('yo')">Hey</button>
