### ISSUE TITLE
Handle Ajax form submission with Turbolinks

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#133]
https://github.com/turbolinks/turbolinks#redirecting-after-a-form-submission
https://m.patrikonrails.com/how-to-make-ajax-calls-the-rails-way-20174715d176

**Comment by bentranter** [comment]
I can probs tackle this with the approach taken in [bentranter/turbolinks](https://github.com/bentranter/turbolinks), though it's still missing support for some of the `rails-ujs` features. I'll look into this over the next few days.

**Comment by paulcsmith** [comment]
@bentranter Thanks Ben! Some of the Rails UJS stuff is handled because Lucky is bundled with the Rails UJS npm package. So you can do `data_remote: true` on a form and it submits with AJAX. So I think it just needs the turbolinks specific stuff like you did in your Turbolinks handler
