### ISSUE TITLE
No overload matches '...#tag' with type Hash(String, String)

### ISSUE THREAD

**Issue by bcardiff** [luckyframework/lucky#1392]
In CustomTags there are two invocations to `tag(Hash)`. And they seem to be unused. In Crystal ~0.36.0 these invocations are causing the custom_tags_spec to fail to compile.

https://github.com/luckyframework/lucky/blob/ec55fc1ee7bb8e423608a31096c63878ab0caf9e/src/lucky/tags/custom_tags.cr#L19-L29

Actually, since the [first commit]( https://github.com/luckyframework/lucky/commit/1367320d91f0deafb92b9fb899d7dd34ab6513a3) of CustomTags is unclear to me if this was working. 

The only definitions of tag methods I can find are in CustomTags and all of them require a tag_name.

**Comment by jwoertink** [comment]
lol 😆  I wonder why that's never been caught before 🤔
