### ISSUE TITLE
Failing spec on crystal 0.36

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1399]
https://github.com/luckyframework/lucky/pull/1398#issuecomment-767103072

I left some notes on that issue. Just need to remove the space at the end of this https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/base_tags.cr#L75

**Comment by robacarp** [comment]
Is the proper fix to change the test to look for a space, or to change the template code to remove the space? A single space between tags in HTML often changes the way things work/look, so this could be a breaking change if we change the tag method generation.

**Comment by jwoertink** [comment]
Good question. Since these are self-closing tags, the space won't matter. Like `<br /> <br /> ` will look the same as `<br /><br />`. Plus any space used for rendering should be on the user, I think. So for this change, we can just remove the space in the code.

**Comment by 96RadhikaJadhav** [comment]
@jwoertink  Can I create a PR for this issue?

**Comment by matthewmcgarvey** [comment]
@96RadhikaJadhav  That'd be great!

**Comment by matthewmcgarvey** [comment]
Completed by https://github.com/luckyframework/lucky/pull/1400
