### ISSUE TITLE
Missing use case when params passed in the URL

### ISSUE THREAD

**Issue by brunto** [luckyframework/lucky#1412]
**Describe the bug**
With some queries like: `http://localhost:5000/smtg?q[name]=bruno`
Before lucky 0.25 I had the possibility to use `params.nested?(:q)` to retrieve a `Hash(String, String)` of my params.
With Lucky 0.25 (not tried with the 0.26 version) this doesn't work, it returns a nil value.

**Expected behavior**
We should have the ability to retrieve a Hash of the given params in the URL.

**Versions:**
 - Lucky version: 0.25.0
 - Crystal version: 0.35.1
 - OS: MACOS

**Comment by matthewmcgarvey** [comment]
The correct formatting for nested query params is `?q:name=bruno`

We have specs with examples here: https://github.com/luckyframework/lucky/blob/42e9b7b43356b729bf2b055b3ee9af5f2b92d768/spec/lucky/params_spec.cr#L402-L407

**Comment by brunto** [comment]
I saw that, but when you migrate an old API made on another framework and that you don't have the possibility to update the frontend, it'll be great to keep this behavior.

**Comment by matthewmcgarvey** [comment]
Hmm, maybe you can find where we did this by looking in the lib folder for your project but it seems like we've used the `q:name` formatting since nested query params were added https://github.com/luckyframework/lucky/commit/8fcc6eeece8e6e64404a5582789c071daac4809e

**Comment by jwoertink** [comment]
I don't remember us having the `q[name]` syntax in params 🤔  Maybe you can do `params.get_raw("q[name]")` to get that value? I haven't tried that, but if that works, then that could be a good escape hatch if you're not able to change how the params are passed in.

**Comment by robacarp** [comment]
It sounds like the situation is that the backend was built in eg rails and the front end is a different project. Rewriting the backend into lucky without rewriting the frontend requires a different parameter parsing scheme than lucky provides natively. 

I've run into this myself because the parameter scheme is different from other project, but I had the ability to tweak the frontend to match.

**Comment by brunto** [comment]
@robacarp You're right, I rewrite an old Rails app but @jwoertink here is my code working on Lucky 0.25:
```
    search_params = params.nested?(:q)
    if search_params
      users.first_name.ilike("%#{search_params["first_name"]}%") if search_params.dig?("first_name")
```

**Comment by brunto** [comment]
My bad, I used the wrong endpoint, you're right guys lucky never works with this kind of syntax.
I can close this issue.
