### ISSUE TITLE
link lets you pass href as well

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1415]
This code gives you a weird side effect:

```crystal
# This code
link "users", to: Users::Index, href: "#"

# Generates
# <a href="#">users</a>
```

Normally you wouldn't ever write this, but I had an anchor as a placeholder that had 150k tailwind classes, so I didn't see the end of the method 😂  so it was like `link to: Thing, class: ".... forever ...", href: "#"` and I couldn't figure out why it wouldn't render the link properly. 

I think if you use `link`, you shouldn't be able to add the `href` property. If you want to, just use `a()`.

**Comment by stephendolan** [comment]
This has bit me before when pulling in Tailwind UI components as well!
