### ISSUE TITLE
Custom tags don't support Hash

### ISSUE THREAD

**Issue by confact** [luckyframework/lucky#1418]
**Describe the bug**
custom tags don't support Hash as params, but divs and others do. This makes it hard to make custom tags work with flexible data.

**To Reproduce**
make a normal `Hash(String, String)` called `params` with variables.
make a code like: 
```
tag "turbo-frame", params do
  text "test"
end
``` 

If you make it with div like:
```
div params do
  text "test"
end
``` 
It will work.

**Expected behavior**
Have the same consistent behavior everywhere. Make custom tags work as standard tags.

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.26
 - Crystal version (`crystal --version`): 0.36.1
 - OS: Linux

**Comment by jwoertink** [comment]
Does it work if you do this?

```crystal
tag "turbo-frame", options: params do
  text "test"
end
```

**Comment by confact** [comment]
@jwoertink yea, that worked. ^^ - Is that supposed to work like that? Would nice that they work the same as the others or is it something that makes it harder?

**Comment by jwoertink** [comment]
It works because the second argument is for the valueless args like if you were writing some Vuejs `tag "turbo-frame", [:v_bind]`, and the third arg is the html opts. So this should also work

```crystal
tag "turbo-frame", [] of Symbol, params do
  text "test"
end
```

Maybe we can use an outer variable for that? Or possible swap those, but not sure how much damage that might cause 🤔

**Comment by robacarp** [comment]
@jwoertink does it make sense to provide an overload of the tag method which takes the params hash as the second parameter? Going too far down that road might make things confusing but maybe this isn't a step too far?

**Comment by jwoertink** [comment]
Yeah. It looks like this current overload is to match the base ones https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/base_tags.cr#L54 but we seem to be missing this variant https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/base_tags.cr#L46 (without the attrs). I think if we add that in, then it should work.
