### ISSUE TITLE
Making the watcher less greedy?

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1421]
The current `lucky watch` task runs [this loop](https://github.com/luckyframework/lucky/blob/b6f68bdc78b0b6831e801cac3ba0c97f83159e81/tasks/watch.cr#L222) that looks for the modification time to change on the files, and once it sees one that changes, it kicks off a compilation.

In some cases, you might have 2 or more crystal files open in your editor, and you need to save all of them. Right now your options are to save (kick off compile), save file 2 (kick off second compile), and save file 3 (kick off third compile)... or you just kill your whole running dev server to save all your files, and then wait for the reboot of lucky and the asset stuff (plus workers in my case).

This may be a long shot, but what would be cool is if we had a way to detect that a compile was happening, and if we try to kick off another compile, we kill the first one where it stands. Another option could be to wait like 2 seconds before starting the compile... though, I'm not big on that idea because in a normal app case, that slows down your compile turn-around.

**Comment by nolyoi** [comment]
I like the first idea, a way to cancel the current compile if another save is detected before compile finishes. The 2nd idea seems like it could just slow down development in a lot of situations.
