### ISSUE TITLE
Can't parse string body

### ISSUE THREAD

**Issue by huuhait** [luckyframework/lucky#1425]
Hi i have some problem in body parse

when i try with body string:

> `"{\"payload\":\"eyJleHAiOjE2MTQ4MDE5ODgsImRhdGEiOnsiZW1haWwiOiJnYXhvajM3MzI2QG5ldGpvb2suY29tIn19\",\"signatures\":[{\"protected\":\"eyJhbGciOiJSUzI1NiJ9\",\"header\":{\"kid\":\"applogic\"},\"signature\":\"AWLKRr6WIRvsUzANMb9lEqGoAZp_9ywiJhWuttVLa5YU-CUAIgPfhu2S5fAeUMn5AO0UHh-Oz0Z7mAj7SLR7hsiqD0qDsNWPw6sTjdtsXvB5-N_Ix7XYXKApsz-7j1laNIAAe3eQOGfzpKabv_E9QHSfnbbO3jhUOnQGOiY5fOUXtX5EaHvoaXIjUdV2GD4IJmnC3w5tllBvfgWBHd9XZ72ybbACPcBrQfn8j-ptltUfljd5tO-fvQB2eqDzmZMpXoGH63kb1h01dyNlJM-wQc5bLDJ_B19YcKjQLvhLUcNzFSSHKuI0edMazzJFywk7agS0K19A6-vOEZa1m5aabw\"}]}"`

then i got:
![image](https://user-images.githubusercontent.com/40519768/109868848-bba6a300-7c9a-11eb-989b-1d6b56e5525e.png)

but if i tested with another string like "something" or "nothing..."
it'll be working good :|

Do you have a way to fix this?
Anyway, tks for help!

**Comment by huuhait** [comment]
fixed wrong json format
sorry

**Comment by jwoertink** [comment]
@huuhait Glad you got it figured out. I'll go ahead and close this, but if you see another issue, feel free to open it back up.
