### ISSUE TITLE
Tags for Question must be preloaded with 'preload_tags' while trying to edit a users role? Makes no sense

### ISSUE THREAD

**Issue by nolyoi** [luckyframework/lucky#1426]
**Describe the bug**
I've been constructing my project pretty normally. However when trying to edit a user I'm being presented with a failure stating:
> Error 500 at POST /admin/users/3
tags for Question must be preloaded with 'preload_tags'
See raw message
tags for Question must be preloaded with 'preload_tags'

I have no idea how this relates to change a role of a user.

My /pages shortened
**Admin**
- Users
- Tags
- Questions
- Answers

**Pages**
- Users
- Questions
- - Answers
etc.

**To Reproduce**
Use structure above.

Heres an example error (this is located in /pages/questions/edit_page.cr). It's located here because that form is a quickly reply box so a user can submit an answer to a question on the answers view page.

Oddly, there are no errors showing in the terminal either? Which seems very odd.

**Expected behavior**
I should be able to keep these to edit the users role from my admin panel.

**Screenshots/code**
![image](https://user-images.githubusercontent.com/59351042/110273174-98793d80-7f91-11eb-82a2-d40ecb7b1a3f.png)

Here is the code fore my pages/admin/users/edit.cr and update.cr. makes no sense where these questions and tags query problems are coming from. tags are preloaded by default on question queries.

/actions/admin/users/edit.cr
```crystal
class Admin::Users::Edit < AdminAction
  get "/admin/users/:user_id/edit" do
    user = UserQuery.new.preload_questions(QuestionQuery.new).preload_answers(AnswerQuery.new).find(user_id)
    html Admin::Users::EditPage,
      operation: SaveUser.new(user),
      user: user
  end
end
```
/actions/admin/users/update.cr
```crystal
class Admin::Users::Update < AdminAction
  post "/admin/users/:user_id" do
    user = UserQuery.new.preload_questions(QuestionQuery.new.preload_tags).find(user_id)
    SaveUser.update(user, params) do |operation, user|
      if operation.saved?
        flash.keep
        flash.success = "Profile successfully updated."
        redirect Admin::Users::Index
      else
        flash.failure = "It looks like the form is not valid"
        html Admin::Users::EditPage, operation: operation, user: current_user
      end
    end
  end
end
```

Here's the form in /pages/admin/users/edit_page.cr
```crystal
form_for Admin::Users::Update.with(user.id), multipart: true do
              div class: "grid grid-cols-1 sm:grid-cols-1 gap-6 mt-4" do
                div do
                  mount ::Shared::Field, attribute: op.username, &.text_input(autofocus: "true", append_class: "mt-2 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded py-2 px-4 block w-full focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring", attrs: [:disabled])
                end
                div do
                  mount ::Shared::Field, attribute: op.email, &.email_input(autofocus: "true", append_class: "mt-2 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded py-2 px-4 block w-full focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring")
                end
                div do
                  mount ::Shared::Field, op.role do |input_html|
                    input_html.select_input(required: true, replace_class: "form-select block w-full pl-3 pr-10 py-2 text-base leading-6 border rounded border-gray-300 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 sm:text-sm sm:leading-5") do
                      options_for_select op.role, User::ROLES
                    end
                  end
                end
                div do
                  div class: "h-20 w-20 mb-4" do
                    if !user.profile_picture_path.nil?
                      img alt: "avatar", class: "h-full w-full object-cover", src: current_user.profile_picture_path.not_nil!
                    else
                      img alt: "avatar", class: "h-full w-full object-cover", src: "https://lh3.googleusercontent.com/a-/AOh14Gi0DgItGDTATTFV6lPiVrqtja6RZ_qrY91zg42o-g"
                    end
                  end
                  mount ::Shared::Field, op.profile_picture, label_text: "Avatar", &.file_input(append_class: "mt-2 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded py-2 px-4 block w-full focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring")
                end
              end
              div class: "flex justify-end mt-6" do
                submit "Update", class: "bg-gray-700 text-white py-2 px-4 rounded hover:bg-gray-500 hover:text-white focus:outline-none focus:bg-gray-500 focus:text-white"
              end
            end
```

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.26.0 with Avram 0.20 override.
 - Crystal version (`crystal --version`): 0.36.1
 - OS: MacOS

_**EDIT:**_
Here is the repo currently affected with my latest code up there: https://github.com/nolyoi/ask.cr/tree/feature-add-admin-questions-sections/src

Any possible ideas whats going on here? Any help would be GREATLY appreciated.

**Comment by matthewmcgarvey** [comment]
Didn't go any further than this but looks like tags on questions are being accessed but not loaded https://github.com/nolyoi/ask.cr/blob/7095509300754a920b83529ba80416eeebd8757c/src/pages/admin/users/edit_page.cr#L34

Your update action doesn't preload the question's tags

**Comment by nolyoi** [comment]
> Didn't go any further than this but looks like tags on questions are being accessed but not loaded https://github.com/nolyoi/ask.cr/blob/7095509300754a920b83529ba80416eeebd8757c/src/pages/admin/users/edit_page.cr#L34
> 
> Your update action doesn't preload the question's tags

It does bt default, not sure why it's causing this issue only when updating a user.

```crystal
class QuestionQuery < Question::BaseQuery
  include Avram::SoftDelete::Query
  
  def initialize
    defaults &.preload_author.preload_tags
  end
end
```

**Comment by nolyoi** [comment]
Close this, my bad. The problem was a validate_password_size from a previous pw

**Comment by nolyoi** [comment]
> Didn't go any further than this but looks like tags on questions are being accessed but not loaded https://github.com/nolyoi/ask.cr/blob/7095509300754a920b83529ba80416eeebd8757c/src/pages/admin/users/edit_page.cr#L34
> 
> Your update action doesn't preload the question's tags

Tags a preloaded w every question by default
