### ISSUE TITLE
New mount override for a component instance

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1427]
We currently have `mount SomeComponent`, but it would be cool if we also added `mount SomeComponent.new` as an override. The idea here being that maybe you're passing a component through a Proc, or have an array of components. In this case you wouldn't be able to mount it, and your only option is to call `my_component.view(view).to_s` or something like that 😂 

I think the override would just take a `Lucky::BaseComponent` and no other arguments needed.

```crystal
mount MyComponent.new(whatever: "here")
```

Ref: https://github.com/luckyframework/breeze/pull/2#discussion_r589513825

**EDIT**

Because this is starting to come up more, lets roll with `mount_instance`. It's a bit verbose, but at least gives us something for now. Worst case is we deprecate that name, and rename it later. It's probably an edge case that it will be used anyway.

**Comment by matthewmcgarvey** [comment]
That was a thing but was removed/deprecated starting with this PR https://github.com/luckyframework/lucky/pull/1151

**Comment by jwoertink** [comment]
I feel like we had a reason for getting rid of it... I just don't remember why, but I can't think of a reason why not have it. I think the preferred method should be to pass in the class, but have this as an escape.

I guess the main downside here might be the lack of consistency apps may get from things like

```crystal
# on one page by one dev
mount PaginationNav

# on some other page by another dev
mount PaginationNav.new
```

Then a third dev comes along and is like "well, which way do we use?"

**Comment by stephendolan** [comment]
I can already see myself getting confused with that exact scenario ^

Is there some way we could designate it as an escape hatch without making it as interchangeable, or would that just be even messier?

```crystal
mount PaginationNav

mount nil, custom_instance: PaginationNav.new
```

That's not necessarily an API I'm in favor of, but the general idea of avoiding two ways to do the same thing is something I'm fully on board with.

**Comment by jwoertink** [comment]
Well.. Maybe we don't need to have the `mount` in that case. I guess we could try to solve the original issue since no one else has really asked for this. I think @paulcsmith was mainly asking because in Breeze, for that customization, we want to make it easier on people to add in without needing to know they have to mount their component. So the idea is that we have this array of components, and then I iterate over that array and render them out. Right now with a component instance, I don't have a simple way to render that out. 

What about if we just had this? 
```crystal
PaginationNav.new.render_to_view
```

**Comment by paulcsmith** [comment]
Yeah I think we removed it to avoid confusion, but it also makes it less flexible. I like the idea of making it more of an escape hatch instead. Either by `render_to_view(@view)` or another method like `mount_instance`. I personally lean toward `mount_instance`. I think that is fairly clear and we can say in the docs that it should be rarely used and to prefer `mount`

**Comment by jwoertink** [comment]
Added a new `mount_instance` method.
