### ISSUE TITLE
`lucky gen.secret_key - not found`

### ISSUE THREAD

**Issue by nolyoi** [luckyframework/lucky#1431]
**Describe the bug**
When trying to generate a secret key I get an error saying it cannot be found

**To Reproduce**
run `lucky gen.secret_key1

**Expected behavior**
To generate a key 

**Screenshots/code**
```crystal
⋊> ~/C/p/ask_cr on master ◦ lucky gen.secret_key                                                                                            14:49:36
Task gen.secret_key not found.
```
Here is the `lucky -h1 command which only shows gen.migrations as the only gen command.
```crystal
⋊> ~/C/p/ask_cr on master ◦ lucky -h                                                                                                        14:50:10
Usage: lucky name.of.task [options]

Available tasks:

  ▸ change_user_role          Enable or disable an existing user as an admin.
  ▸ count_questions_in_tags   Recounts the amount of questions that belong to each tag.
  ▸ db.console                Access PostgreSQL console
  ▸ db.create                 Create the database
  ▸ db.create_required_seeds  Add database records required for the app to work
  ▸ db.create_sample_seeds    Add sample database records helpful for development
  ▸ db.drop                   Drop the database
  ▸ db.migrate                Run any pending migrations
  ▸ db.migrate.one            Run just the next pending migration
  ▸ db.migrations.status      Print the current status of migrations
  ▸ db.redo                   Rollback and run just the last migration
  ▸ db.reset                  Drop, recreate, and run migrations.
  ▸ db.rollback               Rollback the last migration
  ▸ db.rollback_all           Rollback all migrations
  ▸ db.rollback_to            Rollback to a specific migration
  ▸ db.schema.dump            Export database schema to a sql file
  ▸ db.schema.restore         Restore database from a sql dump file
  ▸ db.setup                  Runs a few tasks for setting up your database
  ▸ db.verify_connection      Verify connection to postgres
  ▸ gen.migration             Generate a new migration
```

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.26
 - Crystal version (`crystal --version`): 0.36.1
 - OS: MacOS

**Comment by matthewmcgarvey** [comment]
Your `tasks.cr` file is missing the require for lucky's tasks https://github.com/nolyoi/ask.cr/blob/1a9dadacd1ec761df99fe506d75a737b37a43828/tasks.cr#L17

You need to add `require "lucky/tasks/**"`

**Comment by nolyoi** [comment]
That's diff than what's on line 12?

Seems like all other tasks show up fine. Why the separation of them?

Sincerely,

Nolan Mayersky - Software Engineer
+1(219)777-0475
https://nolanm.dev/

On March 13, 2021, Github Notification ***@***.***> wrote:
> Your tasks.cr file is missing the require for lucky's tasks
> <https://github.com/nolyoi/ask.cr/blob/1a9dadacd1ec761df99fe506d75a737b37a43828/tasks.cr#L17>
>
> You need to add require "lucky/tasks/**"
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luckyframework/lucky/issues/1431#issuecomment-
798830880>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOE2AATHXRPDRTBB5E3N5XDTDQUKNANCNFSM4ZEGH6XQ>.

**Comment by matthewmcgarvey** [comment]
Line 12 is for loading project specific tasks. This is for tasks that come with lucky like generating models/resources/components/etc. One of those tasks is the missing `gen.secret_key`
