### ISSUE TITLE
Issue with editing legacy projects.

### ISSUE THREAD

**Issue by nolyoi** [luckyframework/lucky#1434]
**Describe the bug**
I've been woking on a Lucky 0.26 and Crysrtak 0.36.1
But now I'm wanting to edit another project that runs luck 0.35.
Is there a tool where we can set the luck-cli version locally?

> Example:

> 1. Generate a Lucky project '...'
> 2. Follow dokku deoploy instructions.

**Screenshots/code**
```crystal
⋊> ~/C/w/cattle-finder lucky dev                                                                                                            13:33:57
overmind: open Procfile.dev: no such file or directory
⋊> ~/C/w/cattle-finder lucky dev                                                                                                            13:36:12
overmind: open Procfile.dev: no such file or directory
⋊> ~/C/w/cattle-finder lucky dev                                                                                                            13:36:36
overmind: open Procfile.dev: no such file or directory
⋊> ~/C/w/cattle-finder lucky dev   
```

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.26/0.25
 - Crystal version (`crystal --version`): 0.36.1, 0.35
 - OS: Mac OS

Outputting lucky -h:
```crystal
⋊> ~/C/w/cattle-finder lucky --help                                                                                                         13:40:53

You are not in a Lucky project

Try this...

  ▸ Run lucky init to create a Lucky project.
  ▸ Change your project's root directory to see what tasks are available.

  ▸ Run lucky init to create a Lucky project.
  ```
**Additional context**
Right now Im assuming the only option is to reinstall shards and lucky cli v0.25? Or is there another way around this?

**Comment by stephendolan** [comment]
Closing this in favor of the result of https://github.com/luckyframework/lucky/discussions/1436, when that discussion is complete! Right now this kind of behavior isn't intended to be possible, but we'd love to make it work as a feature in the future.
