### ISSUE TITLE
Incompatible with Crystal 1.0 (with workaround)

### ISSUE THREAD

**Issue by haarts** [luckyframework/lucky#1440]
**Describe the bug**
Building Lucky with the latest Crystal 1.x version fails with:

```
root@5b0d57ba4fef:/tmp/lucky_cli# shards install
Resolving dependencies
Fetching https://github.com/luckyframework/teeplate.git
Fetching https://github.com/crystal-ameba/ameba.git
Fetching https://github.com/crystal-community/future.cr.git
Unable to satisfy the following requirements:

- `crystal (~> 0.35, >= 0.35.0)` required by `teeplate 0.8.2`
- `crystal (>= 0.35.0)` required by `ameba 0.14.1`
- `crystal (~> 0.34, >= 0.34.0)` required by `future 0.1.0`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.
```

**To Reproduce**
Follow the install instructions as described [here](https://luckyframework.org/guides/getting-started/installing).

**Expected behavior**
Frankly I *would* expect this to fail.

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.26.0
 - Crystal version (`crystal --version`): Crystal 1.0.0 [dd40a2442] (2021-03-22)
 - OS: The [Crystal docker image](https://hub.docker.com/r/crystallang/crystal)

**Additional context**
The project dependencies can be successfully added with; `shards --ignore-crystal-version install`.

Merely updating the Crystal version in the `shards.yml` file does not work since the dependencies (teeplate/ameba) are pinnen to incompatible Crystal versions.

**Comment by jwoertink** [comment]
Hey @haarts thanks for the report!

Yeah, right now Lucky isn't compatible with Crystal 1.0. We recommend sticking with Crystal 0.36.1 with the latest Lucky release (0.26.0). We are currently working on the next release which will be compatible, but that might not be out for a few weeks. 

I'll go ahead and keep this open for now so others coming here will see the notes and suggestions.

**Comment by stephendolan** [comment]
As of Lucky 0.27, we're fully compatible with Crystal 1.0! 🥳 

Closing this one out.

**Comment by Xosmond** [comment]
> As of Lucky 0.27, we're fully compatible with Crystal 1.0! 🥳
> 
> Closing this one out.

Hi @stephendolan On the web guide says "< 1.0.0" that is outdated right?

**Comment by stephendolan** [comment]
@Xosmond can you provide a link so that I can correct it? Everything should say <= 1.0.0 like it does here, which is correct:
https://www.luckyframework.org/guides/getting-started/installing#crystal-version

**Comment by Xosmond** [comment]
> @Xosmond can you provide a link so that I can correct it? Everything should say <= 1.0.0 like it does here, which is correct:
> https://www.luckyframework.org/guides/getting-started/installing#crystal-version

My bad, I didn't saw the `=` 👍
