### ISSUE TITLE
Parsing Lucky::Params twice per request

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky#1473]
**Describe the bug**

We affect performance by parsing the Lucky::Params twice

https://github.com/luckyframework/lucky/blob/79e7108a807ccd8573b5ead3b7bd418051c05c72/src/lucky/http_method_override_handler.cr#L19

https://github.com/luckyframework/lucky/blob/79e7108a807ccd8573b5ead3b7bd418051c05c72/src/lucky/param_helpers.cr#L5

**Expected behavior**

Should this be added to our context extensions? https://github.com/luckyframework/lucky/blob/master/src/lucky/context_extensions.cr

**Comment by matthewmcgarvey** [comment]
If this is updated, could also update this line to be `context.request.method == "POST"` as well https://github.com/luckyframework/lucky/blob/79e7108a807ccd8573b5ead3b7bd418051c05c72/src/lucky/http_method_override_handler.cr#L15

**Comment by jwoertink** [comment]
Taking a look at this, it seems that it's not the initialization that's really the performance hit. It's the data lookup when calling `get?()`. The issue I see here is that the first one has no references to `@route_params`, as where the second one does.

I'm not sure how we could do this... If we store a reference to params in context on the first one, then calling `get?` later would need to know that the route_params may or may not have been updated. The `route_params` comes from LuckyRouter, and gets set in the route_handler which happens later than the http_method_override_handler..

Maybe I can do something like `context.params = Lucky::Params.new`, then later `context.params.route_params = @route_params`? 

As for your second suggestion...

```
   use_equal 528.87M (  1.89ns) (± 2.90%)    0.0B/op           fastest
use_includes  33.92k ( 29.48µs) (± 2.57%)  46.9kB/op  15590.48× slower
```

I think we can do that 😂
