### ISSUE TITLE
Error page lucky svg cut off

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky#1475]
**Describe the bug**

<img width="114" alt="CleanShot 2021-04-18 at 15 32 16@2x" src="https://user-images.githubusercontent.com/17329408/115158254-4715a100-a05b-11eb-99c0-0222c443adb4.png">

This could be something that doesn't happen on chrome but on firefox the svg is cut off on the left side.

Increasing the exception-logo class width to 68px seems to fix it but [since it's a different repo](https://github.com/crystal-loot/exception_page/blob/b3d1db7515bd6a29ffbbcbc7b65786b095f95b75/src/exception_page/exception_page.ecr#L104) I don't think that's something we can/should do. Seems like the best thing to do would be to resize [our svg](https://github.com/luckyframework/lucky/blob/79e7108a807ccd8573b5ead3b7bd418051c05c72/src/lucky/exception_page.cr#L15).

**Comment by jwoertink** [comment]
Related: https://github.com/crystal-loot/exception_page/issues/24
