### ISSUE TITLE
Confusing `validate_uniqueness_of` experience

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/lucky#1482]
I was referencing this guide:
https://luckyframework.org/guides/database/validating-saving#using-validations

I have a data model where a `Filter` has many `FilterPlaceholder`s, and I wanted to make sure that each `FilterPlaceholder.name` value was unique for the same `filter_id`.

I was attempting to use the `query` parameter to make sure that I'm doing that like this:
```crystal
    validate_uniqueness_of name, query: FilterPlaceholderQuery.new.filter_id(filter.id)
```

However, that yielded this compiler error:
```
web          | In src/operations/save_filter_placeholder.cr:7:5
web          | 
web          |  7 | validate_uniqueness_of(name, query: FilterPlaceholderQuery.new.filter_id(filter.id))
web          |      ^---------------------
web          | Error: no overload matches 'SaveFilterPlaceholder#validate_uniqueness_of' with types Avram::PermittedAttribute(String), query: FilterPlaceholderQuery
web          | 
web          | Overloads are:
web          |  - Avram::DatabaseValidations(T)#validate_uniqueness_of(attribute : Avram::Attribute, query : Avram::Criteria, message : String = "is already taken")
web          |  - Avram::DatabaseValidations(T)#validate_uniqueness_of(attribute : Avram::Attribute, message : Avram::Attribute::ErrorMessage = "is already taken")
```

I looked for "Criteria" in the guides and `CHANGELOG.md` to try and figure out what was wrong, and it took me wayyyyyy too long to realize that it seems like the way you get an `Avram::Criteria` is to make sure you select the column you're validating:
```crystal
    validate_uniqueness_of name, query: FilterPlaceholderQuery.new.filter_id(filter.id).name
```

We could/should maybe resolve this in the docs, but I think there's an opportunity for a much friendlier compiler error as well if we can create an override that takes the base class of an Avram Query. In retrospect, the guides **do** make this distinction, but it's not called out so the single-column select kind of faded into background noise for me initially.

**Comment by matthewmcgarvey** [comment]
This is connected to https://github.com/luckyframework/avram/issues/368

The gist is that we want to update this validation to accept a query or a criteria

**Comment by stephendolan** [comment]
Thanks, @matthewmcgarvey, I hadn't seen that!
