### ISSUE TITLE
The generated delete action should use a DeleteOperation

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1487]
When you generate a new browser resource, you'll get this action

https://github.com/luckyframework/lucky/blob/master/tasks/gen/templates/resource/actions/%7B%7Bfolder_name%7D%7D/delete.cr.ecr

It should use the `DeleteOperation` by default.

**Comment by nodeMD** [comment]
Hello 😃 
I've prepared a small PR to address that issue: https://github.com/luckyframework/lucky/pull/1497
Please take a look and review when you will have a moment 🙂
