### ISSUE TITLE
Add time_from_now_in_words Time helper

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1491]
We have `time_ago_in_words` which takes a time, and compares how long ago since `Time.utc` it was. https://github.com/luckyframework/lucky/blob/master/src/lucky/page_helpers/time_helpers.cr 

But if you put in a time that's in the future, you'll get some output like "almost 0 years". In this case, you need to use `distance_of_time_in_words(Time.utc, future_date)`. It would be cool if we just had the helper to handle it for us.

**Comment by nodeMD** [comment]
Hello 😃 
Thanks to that issue I have made my first steps with Crystal programming language.
I've opened a PR to address that issue: https://github.com/luckyframework/lucky/pull/1493 
Please take a look and review when you will have time.

**Comment by jwoertink** [comment]
Thanks for the contribution @nodeMD! Perfect for a first contribution. Welcome to Lucky!

**Comment by matthewmcgarvey** [comment]
Completed by https://github.com/luckyframework/lucky/pull/1493
