### ISSUE TITLE
Add new multipart? request helper

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1494]
We have a list of these helper methods that can be used in your Actions like `html?` or `ajax?`. While working on Breeze I came up with a use case for `multipart?` which should return true if the `"Content-Type"` header is `multipart/form-data;`. 

This could be used in before action pipes to do specific things if you're doing a multipart POST.

https://github.com/luckyframework/lucky/blob/master/src/lucky/request_type_helpers.cr

**Comment by nodeMD** [comment]
Hello 😃 
I've created a PR to address that issue: https://github.com/luckyframework/lucky/pull/1495
Please take a look and review when you will have a moment 🙂
