### ISSUE TITLE
Outdated doc links

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1498]
There's a few places in our code where we link to the website guides. Here's one I found https://github.com/luckyframework/lucky/blob/master/tasks/gen/templates/resource/operations/%7B%7Boperation_filename%7D%7D.cr.ecr#L3 but there may be others. These need to be looked over and ensure they're pointing to the latest URL.

**Comment by nodeMD** [comment]
Hello 😃 
What does it mean: `latest URL`? 
How can I be sure that the URL in the code is the latests one? 
For example that one: https://github.com/luckyframework/lucky/blob/master/tasks/gen/templates/resource/operations/%7B%7Boperation_filename%7D%7D.cr.ecr#L3 If the URL in the code opens a lucky framework guide for version 0.27.0 then it means it is a good one?

**Comment by jwoertink** [comment]
We don't actually have versioned docs yet. What I meant by "latest" is, if you go to that URL in the docs, you'll see it does a 301 redirect from `/database/validating-saving` to `/database/saving-records`. The website handles legacy redirects, but our docs should all just show the latest URL instead of the legacy one.

Let me know if you still need more clarification on that. Thanks!

**Comment by nodeMD** [comment]
Got it, now I see where the problem is. Thank you for the clarification 🙂

**Comment by nodeMD** [comment]
I've added a small PR to address that issue: https://github.com/luckyframework/lucky/pull/1501
Please take a look and review when you will have a moment 🙂

**Comment by jwoertink** [comment]
Closed by #1501
