### ISSUE TITLE
`gen.action.api` should create action in the `./src/actions/api` folder

### ISSUE THREAD

**Issue by vjousse** [luckyframework/lucky#1502]
**Describe the bug**

When using `lucky gen.action.api` the action file is created in `./src/actions/`. I would expect it to be created in `./src/actions/api/` instead.

**To Reproduce**

> 1. Generate an API Action with `lucky gen.action.api MediaFiles::Create`
> 2. Check that the action has been created in the `./src/actions/` directory: `Done generating MediaFiles::Create in ./src/actions/media_files`

**Expected behavior**
API Action should be created in `./src/actions/api/`

**Screenshots/code**
If applicable, add screenshots/code samples to help explain your problem.

**Versions (please complete the following information):**
 - Lucky version: 0.27.2
 - Crystal version: 1.0.0
 - OS: ArchLinux

**Comment by nodeMD** [comment]
From the example how to generate an API Action (https://github.com/luckyframework/lucky/blob/master/tasks/gen/action/api.cr#L15) I can see that it is being done like that:
`lucky gen.action.api Api::MediaFiles::Create`
and then the action is created in  `./src/actions/api/`
but I am not sure if that resolves the issue.

**Comment by vjousse** [comment]
Yes indeed you're right. My error came from reading the "help message" from the CLI:

```
➜  lucky-blog git:(master) lucky gen.action.api
Action name is required. Example: lucky gen.action Users::Index
```
I just copy pasted the propposed solution (without thinking about it) and it didn't contain the `Api::` part.
Maybe tweaking the error message by adding an `Api::` part in front of it when we are calling `gen.action.api`?
