### ISSUE TITLE
Serializer render should be abstract

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1503]
The Serializers require that you define a `render` method. Technically it can be anything that responds to `to_json`, but we never actually enforce that. We should define the abstract `render` to ensure all Lucky Serializers have that method.

My first thought is that it should be typed to `NamedTuple`... however, for compatibility sake, we could also just not provide a return type. I'm on the fence with this one.

https://github.com/luckyframework/lucky/blob/8e86e8da8104c1c5f63426b2ad069d6826e834fe/src/lucky/serializer.cr#L4-L6

```crystal
abstract def render : NamedTuple

def to_json(io)
  render.to_json(io)
end
```

**Comment by matthewmcgarvey** [comment]
I'm not sure if it's even possible to say `NamedTuple` without also specifying the key names and types?

Also something I just learned is that you can not specify the type on the abstract method but specify it in the implementation, but can't do the opposite. That's makes me lean towards not limiting it to NamedTuple even if it's possible

https://play.crystal-lang.org/#/r/b6ok

**Comment by jwoertink** [comment]
Yeah, you don't have to specify the name types with `NamedTuple` https://play.crystal-lang.org/#/r/b6tb 

But I'm ok with not enforcing a type here, at least to start. We may decide to do that later.

**Comment by stephendolan** [comment]
If we're in refactor mode for any of this stuff, I'd also maybe recommend renaming this `JSONSerializer` or something. I had to serialize XML for an app and reached for serializers, but it didn't work very well and I ended up overriding a bunch of methods.

**Comment by jwoertink** [comment]
I think we can still leave it as "Serializer". If you wanted to use it for XML, you would just need to add your `to_xml` method that returns your XML string. If you never call `to_json`, then they are pretty generic. And actually, that even makes for a better argument for why we shouldn't enforce a return type on the `render` method. 

```crystal
abstract class BaseSerializer < Lucky::Serializer
  def to_xml
     # call render to build your XML
  end
end
```

Then in your action you could do `xml UserSerializer.new(user).to_xml`. I guess another option to could be that you would separate out your base classes...

```crystal
abstract class BaseJSONSerializer < Lucky::Serializer
end

abstract class BaseXMLSerializer < Lucky::Serializer
end
```

But good suggestion. XML is sort of pushed to the side these days, so it's hard to remember that there's other options out side of JSON. Speaking of which... what ever happened to message pack? lol 😂

**Comment by stephendolan** [comment]
Hah! Yeah, where I ended up having to jump in and do some overrides was for `for_collection`, but maybe that's just the nature of the beast when you're not using JSON!

**Comment by jwoertink** [comment]
Ah, gotcha. That makes sense.
