### ISSUE TITLE
Gzip files in StaticHandler

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#154]

**Comment by bobzoller** [comment]
working on it ^^^

**Comment by paulcsmith** [comment]
@bobzoller Thanks so much. This would be an awesome addition. I'm thinking it would look something like Amber's https://github.com/amberframework/amber/blob/master/src/amber/router/pipe/static.cr#L80 implementation. We don't need the etag stuff yet, but it should be added eventually.

I think their implementation covers a lot of cases so it would likely be quite similar. I think you used `CompressHandler` in the other PR. That only compresses the HTML/JSON response (I think) so I don't think that will work, but I'm not sure. One way to try is to add the handler to https://github.com/luckyframework/web/blob/master/src/server.cr and then run it with `crystal src/server.cr` and open `localhost:8080/tasks` and see what things look like. There is a sample app in `src/app` where you can add stuff to play around with while testing out the handler to make sure it gzips correctly.

I hope that helps!

**Comment by s0kil** [comment]
Will this also include Brotli compression?

**Comment by jwoertink** [comment]
I'm wondering if this should just use the built in crystal handler https://github.com/crystal-lang/crystal/blob/master/src/http/server/handlers/compress_handler.cr

**Comment by s0kil** [comment]
@paulcsmith Ali recently wrote a [binding to brotli algo](https://github.com/naqvis/brotli.cr)

**Comment by bdtomlin** [comment]
@jwoertink, @paulcsmith,

I think the built in crystal handler is not an option for a couple of reasons.

1. I tested it in development and it works great if all of your files are tiny, but on medium sized files it completely chokes and the compression never completes.

2. Even if the performance was within reason, it would still mean that you have to recompress the file on every uncached request.

What do you think about using the [compression-webpack-plugin](https://github.com/webpack-contrib/compression-webpack-plugin)

Then, create a `Lucky::CompressHandler` that gets added to the middleware before `Lucky::StaticFileHandler`. The `Lucky::CompressHandler` would basically check for three conditions:
1. The file is js, css, or svg
2. Accept-Encoding includes gzip
3. The .gz file exists

If the conditions are met, we just read the .gz file and send it.

If none of those conditions are met it just falls through to the current static file handler.

I'd love to hear more of your thoughts on this.

I have a working prototype stuffed in my `app_server.cr` file right now. I just copy/pasted Crystal's StaticFileHandler and did some quick mods to make it work:

```crystal
class Lucky::CompressHandler
  include HTTP::Handler

  def initialize(public_dir : String, fallthrough = true, directory_listing = true)
    @public_dir = File.expand_path public_dir
    @fallthrough = !!fallthrough
    @directory_listing = !!directory_listing
  end

  def call(context)
    if skip_gzip(context)
      call_next(context)
      return
    end
    original_path = context.request.path.not_nil!
    request_path = self.request_path(URI.decode(original_path))
    expanded_path = File.expand_path(request_path, "/")
    file_path = File.join(@public_dir, expanded_path)
    if !File.exists?(file_path + ".gz")
      call_next(context)
      return
    end

    context.response.headers["Content-Encoding"] = "gzip"
    context.request.path = context.request.path + ".gz"

    last_modified = modification_time(file_path)
    add_cache_headers(context.response.headers, last_modified)

    if cache_request?(context, last_modified)
      context.response.status = :not_modified
      return
    end

    context.response.content_type = MIME.from_filename(file_path, "application/octet-stream")
    context.response.content_length = File.size(file_path + ".gz")
    File.open(file_path + ".gz") do |file|
      IO.copy(file, context.response)
    end
  end

  protected def request_path(path : String) : String
    path
  end

  private def etag(modification_time)
    %{W/"#{modification_time.to_unix}"}
  end

  private def modification_time(file_path)
    File.info(file_path).modification_time
  end

  private def skip_gzip(context)
    !context.request.headers.includes_word?("Accept-Encoding", "gzip") && !context.request.path.ends_with?(/\.js|css$/)
  end

  private def add_cache_headers(response_headers : HTTP::Headers, last_modified : Time) : Nil
    response_headers["Etag"] = etag(last_modified)
    response_headers["Last-Modified"] = HTTP.format_time(last_modified)
  end

  private def cache_request?(context : HTTP::Server::Context, last_modified : Time) : Bool
    # According to RFC 7232:
    # A recipient must ignore If-Modified-Since if the request contains an If-None-Match header field
    if if_none_match = context.request.if_none_match
      match = {"*", context.response.headers["Etag"]}
      if_none_match.any? { |etag| match.includes?(etag) }
    elsif if_modified_since = context.request.headers["If-Modified-Since"]?
      header_time = HTTP.parse_time(if_modified_since)
      # File mtime probably has a higher resolution than the header value.
      # An exact comparison might be slightly off, so we add 1s padding.
      # Static files should generally not be modified in subsecond intervals, so this is perfectly safe.
      # This might be replaced by a more sophisticated time comparison when it becomes available.
      !!(header_time && last_modified <= header_time + 1.second)
    else
      false
    end
  end
end

class AppServer < Lucky::BaseAppServer
  def middleware : Array(HTTP::Handler)
    [
      Lucky::ForceSSLHandler.new,
      Lucky::HttpMethodOverrideHandler.new,
      Lucky::LogHandler.new,
      Lucky::SessionHandler.new,
      Lucky::FlashHandler.new,
      Lucky::ErrorHandler.new(action: Errors::Show),
      Lucky::RouteHandler.new,
      Lucky::CompressHandler.new("./public", false),
      Lucky::StaticFileHandler.new("./public", false),
      Lucky::RouteNotFoundHandler.new,
    ] of HTTP::Handler
  end

  def protocol
    "http"
  end

  def listen
    # Learn about bind_tcp: https://tinyurl.com/bind-tcp-docs
    server.bind_tcp(host, port, reuse_port: false)
    server.listen
  end
end

```

**Comment by bdtomlin** [comment]
A little refinement of this idea. An easy way to add additional compression algos like the following...

```crystal
# in generated Lucky app src/app_server.cr
class AppServer < Lucky::BaseAppServer
  def middleware : Array(HTTP::Handler)
    [
      Lucky::ForceSSLHandler.new,
      Lucky::HttpMethodOverrideHandler.new,
      Lucky::LogHandler.new,
      Lucky::SessionHandler.new,
      Lucky::FlashHandler.new,
      Lucky::ErrorHandler.new(action: Errors::Show),
      Lucky::RouteHandler.new,
      Lucky::StaticCompressHandler.new("./public", file_ext: "br", content_encoding: "br"),
      Lucky::StaticCompressHandler.new("./public", file_ext: "gz", content_encoding: "gzip"),
      Lucky::StaticFileHandler.new("./public", false),
      Lucky::RouteNotFoundHandler.new,
    ] of HTTP::Handler
  end
  # ...
end
```

```js
// in generated Lucky app in webpack.mix.js
  .webpackConfig({
    stats: "errors-only",
    plugins: [
      webpackNotifier,
      new CompressionPlugin({
        compressionOptions: { level: 9 },
        test: /\.js$|\.css$|\.html$|\.svg$/
      }),
      new CompressionPlugin({
        compressionOptions: { level: 11 },
        filename: '[path].br[query]',
        algorithm: 'brotliCompress',
        test: /\.js$|\.css$|\.html$|\.svg$/
      })
    ],
    watchOptions: {
      ignored: /node_modules/
    }
  })
```

```crystal
# in lucky lucky/src/charms/static_compress_handler.cr
class Lucky::StaticCompressHandler
  include HTTP::Handler

  def initialize(@public_dir : String, @file_ext = "gz", @content_encoding = "gzip")
  end

  def call(context)
    original_path = context.request.path.not_nil!
    request_path = URI.decode(original_path)
    expanded_path = File.expand_path(request_path, "/")
    file_path = File.join(@public_dir, expanded_path)
    compressed_path = "#{file_path}.#{@file_ext}"

    if !compress_supported?(file_path, compressed_path, context.request.headers)
      call_next(context)
      return
    end

    context.response.headers["Content-Encoding"] = @content_encoding

    last_modified = modification_time(compressed_path)
    add_cache_headers(context.response.headers, last_modified)

    if cache_request?(context, last_modified)
      context.response.status = :not_modified
      return
    end

    context.response.content_type = MIME.from_filename(file_path, "application/octet-stream")
    context.response.content_length = File.size(compressed_path)
    File.open(compressed_path) do |file|
      IO.copy(file, context.response)
    end
  end

  private def compress_supported?(file_path, compressed_path, request_headers)
    request_headers.includes_word?("Accept-Encoding", @content_encoding) &&
      file_path.ends_with?(/\.js|css|html|svg$/) &&
      File.exists?(compressed_path)
  end

  private def add_cache_headers(response_headers : HTTP::Headers, last_modified : Time) : Nil
    response_headers["Etag"] = etag(last_modified)
    response_headers["Last-Modified"] = HTTP.format_time(last_modified)
  end

  private def cache_request?(context : HTTP::Server::Context, last_modified : Time) : Bool
    # According to RFC 7232:
    # A recipient must ignore If-Modified-Since if the request contains an If-None-Match header field
    if if_none_match = context.request.if_none_match
      match = {"*", context.response.headers["Etag"]}
      if_none_match.any? { |etag| match.includes?(etag) }
    elsif if_modified_since = context.request.headers["If-Modified-Since"]?
      header_time = HTTP.parse_time(if_modified_since)
      # File mtime probably has a higher resolution than the header value.
      # An exact comparison might be slightly off, so we add 1s padding.
      # Static files should generally not be modified in subsecond intervals, so this is perfectly safe.
      # This might be replaced by a more sophisticated time comparison when it becomes available.
      !!(header_time && last_modified <= header_time + 1.second)
    else
      false
    end
  end

  private def etag(modification_time)
    %{W/"#{modification_time.to_unix}"}
  end

  private def modification_time(file_path)
    File.info(file_path).modification_time
  end
end

```

**Comment by jwoertink** [comment]
That's a lot of code. Glossing over it, it all seems ok. I haven't really done anything with compression, so I'm not sure on the best option; however, right now we have no option, so something is probably better than nothing. 

I'll try using this in one of my projects next week too so I can get a better feel for how this works.

**Comment by bdtomlin** [comment]
@jwoertink sounds good. I recommend using the version in my latest comment. It has the following benefits:

1. Minimizes additional overhead on the http server (files are pre-compressed).
2. Get's skipped if you are behind another http server that has static compression such as [nginx](https://docs.nginx.com/nginx/admin-guide/web-server/compression/)
3. Uses [nodejs's built in zlib](https://nodejs.org/api/zlib.html) (fast and battle tested)
4. Can support any compression algorithm that nodejs supports (gzip, dflate/inflate, brotli).
5. Gives you the ability to prioritize compression based on the order of the middleware.
6. IO is minimized by checking disk for files and reading files at the last possible moment and only in the case it is likely to be there.

**Comment by paulcsmith** [comment]
I like the idea to gzip at build time instead of at runtime. I haven’t had a chance to look deeply at the code but the general approach sounds solid. 

Thanks for offering to try this in your apps @jwoertink. This would be a huge performance win if we can get this working in production super easily.

**Comment by paulcsmith** [comment]
One other thought though. Will this handle compressing the HTML? That’d be another thing Lucky should do in production if possible. It could be behind a config setting so it can be turned off if you’ve got Nginx or something that does the HTML compression

**Comment by jwoertink** [comment]
Ok, so actually I don't think I can throw this in any of my apps because they all have either nginx or cloudfront or something in front of them already handling this stuff.

**Comment by paulcsmith** [comment]
No problem. We can probably test on the lucky website! It could definitely benefit from this

**Comment by bdtomlin** [comment]
So this method would only handle the compression of static files. HTML generated by lucky would be handled separately since it can't be precompiled. I think the right place to handle this is probably `Lucky::RouteHandler`. That way it efficiency is maximized since we only compress lucky responses on the fly and all static assets are pre-compressed.

This is what I have in mind for the `Lucky::RouteHandler`:

```crystal
require "colorize"

{% if !flag?(:without_zlib) %}
  require "flate"
  require "gzip"
{% end %}

class Lucky::RouteHandler
  include HTTP::Handler

  def initialize(@gzip = false)
  end

  def call(context)
    handler = Lucky::Router.find_action(context.request)
    if handler
      Lucky.logger.debug({handled_by: handler.payload.to_s})
      handler.payload.new(add_gzip(context), handler.params).perform_action
    else
      call_next(context)
    end
  end

  private def add_gzip(context)
    {% if !flag?(:without_zlib) %}
      if @gzip && context.request.headers.includes_word?("Accept-Encoding", "gzip")
        context.response.headers["Content-Encoding"] = "gzip"
        context.response.output = Gzip::Writer.new(context.response.output, sync_close: true)
      end
    {% end %}
    context
  end
end
```

Then in the middleware change
```crystal
# ...
Lucky::RouteHandler.new,
# ...
```
to
```crystal
# ...
Lucky::RouteHandler.new(gzip: true),
# ...
```

**Comment by bdtomlin** [comment]
I've got a working version based on these principles (slightly different code) that I am happy with in my app.

@paulcsmith If you would like I could create a PR on the Lucky website really quickly based on the code I have. That way you could see what you think and at least test it locally.

Keep in mind that to test the server responses locally you'll have to use port 5000 instead of the browsersync proxy (3001). Browsersync changes the "Accept-Encoding" header in order to work, so server responses won't get gzipped.

**Comment by paulcsmith** [comment]
That would be great! And thanks for the tip!
