### ISSUE TITLE
"Getting Started" guide should be more front and center on the README

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/lucky#1545]
It seems like new users may have trouble finding their way to our Getting Started page:
https://discord.com/channels/591460182777790474/611671115835768862/866060022986440734

I'd like to make some updates to our README in case users are arriving via the GitHub homepage and aren't sure how to get up and running.

Mainly, this will consist of making the "Getting Started" page more front and center, somehow. It'll be a link to this:
https://www.luckyframework.org/guides/getting-started/installing

**Comment by jwoertink** [comment]
Did this PR https://github.com/luckyframework/lucky/pull/1586 suffice for this? Or do you think we need a little more info?

**Comment by stephendolan** [comment]
Absolutely!
