### ISSUE TITLE
Allow custom types in path params

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#155]
https://gist.github.com/paulcsmith/2c15093c5bf04fe86b8f3241ab98e490

Not sure whether to default to String or force the user to write a type.

Let's not start work on this quite yet. Still needs some thought on the web side of things and on the LuckyRecord side to make sure it is handled well

**Comment by paulcsmith** [comment]
Please don't start work on this quite yet. Still needs some thought to make sure we handle it well.

**Comment by matthewmcgarvey** [comment]
I don't think this is going to be done. I'm going to close this for now
