### ISSUE TITLE
Passing optional param to `Lucky::Routable.with` leads to compile error

### ISSUE THREAD

**Issue by akadusei** [luckyframework/lucky#1579]
https://github.com/luckyframework/lucky/blob/4c89e1280eddeed1fca83960d86ed2f2c90da465/src/lucky/routable.cr#L314

Can we do without the type restriction of `optional_path_params` here?

I have the following route definition:
```crystal
class Refunds::Create < BrowserAction
  post "/receipts/?:receipt_id/refunds" do
    # ...
  end
end
```

Calling `Refunds::Create.with(receipt_id: 2)` leads to a compile error. The call does not match the method definition of `Lucky::Routable.route` above, causing it to fall through to the next definition of `Lucky::Routable.route`, which is set up to raise a compile error:

```
> 3 |     
> 4 | 
> 5 |     add_route(:get, "/receipts/?:receipt_id/refunds", Refunds::Create)
           ^
Error: Invalid call to Refunds::Create.route

Optional arguments:

- receipt_id

For more information, refer to https://luckyframework.org/guides/http-and-routing/link-generation.
```

Calling `Refunds::Create.with(receipt_id: "2")` works. (Note: "2" here is a `String`). This behaviour is inconsistent with all other params, since they can be passed to `Lucky::Routable.route` or `Lucky::Routable.with` without explicitly converting to `String`.

**Comment by jwoertink** [comment]
Interesting. So it's not that passing the optional path value that's causing the issue. It's that you can't pass the value as anything other than a `String`?

It does look like we just `to_s` on whatever the value is, so I think we can just remove that type restriction there. Though... what might be better is to have some sort of `Paramable` module that's included in the Ints, UUID, and String... That way you're not doing `SomeAction.with(user_id: user)` when you meant `user_id: user.id` :thinking: That can probably come later though. For now, just removing that type restriction is probably good enough.

**Comment by akadusei** [comment]
> Interesting. So it's not that passing the optional path value that's causing the issue. It's that you can't pass the value as anything other than a `String`?

That's correct. (Sorry if issue's title is misleading)
