### ISSUE TITLE
No output on FreeBSD 13 / Crystal 1.1.1

### ISSUE THREAD

**Issue by PhilAtWysdom** [luckyframework/lucky#1585]
On the current master branch, the "lucky" executable itself, when compiled with Crystal 1.1.1, does not produce any output to stdout or stderr.

To reproduce:

> 1. Clone repository
> 2. shards install
> 3. shards build
> 4. crystal build src/lucky.cr
> 5. ./lucky

crystal spec indicates that all specs are passing.

**Expected behavior**
Some kind of output in the terminal when running (for example) $ lucky -v

**Observed behavior**
returns to shell prompt after producing no output

**Versions (please complete the following information):**
 - Lucky version: master (48dd0b12fc0392eeef65f0dec4cd26ed52ea371d)
Crystal 1.1.1 ()
LLVM: 10.0.1
Default target: x86_64-portbld-freebsd13.0
 - OS: FreeBSD 13.0-RELEASE-p0 amd64

**Comment by PhilAtWysdom** [comment]
Also confirmed with tagged release 0.27.2

**Comment by jwoertink** [comment]
Hey @PhilAtWysdom. This repo shouldn't have any sort of output. If you're trying to install Lucky you'll need to follow the instructions on the site here https://luckyframework.org/guides/getting-started/installing#install-lucky-cli-on-linux 

Basically, there's the [CLI](https://github.com/luckyframework/lucky_cli) that is responsible for interacting on the command line. The CLI is where `lucky -v` would output from.

Give that a shot, and let me know if you still see any issues.

**Comment by PhilAtWysdom** [comment]
@jwoertink  Thank you Jeremy, not sure how I missed that, given that I'd done it previously according to the docs! Sorry for the false alarm :smile:

**Comment by jwoertink** [comment]
No worries! Glad you got it sorted out 😄
