### ISSUE TITLE
Add "spinner" to watch task when compiling, or recompiling

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1606]
Related: https://github.com/luckyframework/lucky/pull/1067
Related: https://github.com/luckyframework/lucky_cli/pull/481

When we start compiling tasks, we show a "spinner" in the console. It's neat, and adds a little flare while you're sitting there waiting. 

Right now when we run the `lucky watch` task, between compiles, you'll either see "Compiling..." or "Recompiling..." but no spinner. Having the spinner would allow it to stand out a little more within the mess that is the Process manager output..

**Comment by skojin** [comment]
Since spinner not working with overmind (https://github.com/luckyframework/lucky/pull/1067), 
I suggest add newline before "Compiling..."
And make "Done" in "Done compiling" colored like in https://github.com/luckyframework/lucky/pull/1067#issuecomment-625411134

**Comment by jwoertink** [comment]
oh, the next release of Lucky won't use Overmind anymore (unless you specifically want it to). https://github.com/luckyframework/lucky_cli/pull/710 I don't mind the suggestion as an interim, but since we already use the spinner when building tasks and such, I'd love to keep the consistency. I'd like to try it out with Nox and see if it works first. If not, then we will definitely fallback to your suggestion :+1:

**Comment by skojin** [comment]
Nox not work with spinner too.

e.g. with default Procfile that have ```lucky db.migrate```

```nox start``` Compiling... appear at end
```
release | Starting with pid of 2495
release | Did not migrate anything because there are no pending migrations.
Compiling... ⢿

release | Done
```
