### ISSUE TITLE
Pretty logger still logs () when there's no request id

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1626]
In Lucky 0.29.0 there's a new request ID that's logged on each request. It's only supposed to show up when you have a request ID set, but it seems this `id` https://github.com/luckyframework/lucky/blob/c7c4e0f91278b110e3b4efce270c03a2f8f457fe/src/lucky/pretty_log_formatter.cr#L59

is returning an empty string or something... So you'll see something like

```
GET / ()
  ...
```

**Comment by grepsedawk** [comment]
@jwoertink what is the expectation when request_id is blank?
Should it show only `GET /` with no parenthesis?

**Comment by jwoertink** [comment]
Yup, exactly. That's what it used to show. Then I added the request_id, and assumed it would be `nil` here. I guess that's not the case, though, I haven't really looked in to it.

But yeah, to be clear, if there's no `request_id`, then just show `GET /` like it used to 😄

**Comment by grepsedawk** [comment]
Are there any existing test cases you're able to point me to so I can make sure this is regression tested?
