### ISSUE TITLE
The docker image doesn't building

### ISSUE THREAD

**Issue by wilful** [luckyframework/lucky#1732]
**Describe the bug**
Source image doesn't have wget 

**To Reproduce**

1. Generate a Lucky project 'test'
2. Go to test folder
3. Run docker-compose up

**Versions:**
 - Lucky version (check in shard.lock): 0.30.0
 - Crystal version (`crystal --version`): Crystal 1.4.0 [ef05e26d6] (2022-04-06)
 - OS: Ubuntu 22.04 LTS

```bash
...
Done generating your Lucky project

  ▸ cd into test
  ▸ check database settings in config/database.cr
  ▸ run script/setup
  ▸ run lucky dev to start the server
...
test$ sudo docker-compose up
Creating network "web_default" with the default driver
Creating volume "web_postgres_data" with default driver
Creating volume "web_node_modules" with default driver
Creating volume "web_shards_lib" with default driver
Building lucky
Sending build context to Docker daemon  255.5kB
Step 1/10 : FROM crystallang/crystal:1.4.1
 ---> 4a1e17c6ceca
Step 2/10 : RUN wget https://deb.nodesource.com/setup_16.x -O- | bash
 ---> Running in 5e97e2fd9b82
/bin/sh: 1: wget: not found
```

**Comment by jwoertink** [comment]
@wilful did you mean to close this? If it's an actual issue, we should look at fixing it.

**Comment by wilful** [comment]
> @wilful did you mean to close this? If it's an actual issue, we should look at fixing it.

@jwoertink Sorry, I accidentally clicked close. The problem is actual
