### ISSUE TITLE
SSE Watcher issues

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky#1744]
**Describe the bug**

This could pretty easily fall into the simple territory of a bug we're okay living with.

In development mode, with `lucky watch --watcher=sse`, each time a browser is connected to the SSE server, a [new loop is initiated](https://github.com/luckyframework/lucky/blob/main/tasks/watch.cr#L72-L80) with `sleep 0.1`s.

Simply clicking around on a site, navigating around pages, it's easy to get this loop spinning dozens of times.

I think this would cause an issue if the lucy dev server is running for a long time, and active development is refreshing the page over and over.

**To Reproduce**

> Example:

1. Modify Procfile.dev to activate the SSE reload server.
```diff
- web: .lucky watch --reload-browser
+ web: .lucky watch --reload-browser --watcher=sse
```
3. Start server and poke around on your project.
4. What happens? I don't know! 

**Screenshots/code**

I was able to prove that this happens by modifying lib/lucky/tasks/watch.cr like this. After modifying the file, `rm bin/lucky.watch` and then `lucky dev` will compile the task on and run it.

```diff
    def initialize
      @server = HTTP::Server.new do |context|
        context.response.headers.merge!({
          "Access-Control-Allow-Origin" => "*",
          "Content-Type"                => "text/event-stream",
          "Connection"                  => "keep-alive",
          "Cache-Control"               => "no-cache",
        })
        context.response.status_code = 200

+        puts "SSE Activated".colorize(:green)
+        n = rand(1000000)

        # SSE start
        loop do
+          puts "SSE Loop #{n}"
          if @should_restart
+            puts "Triggering SSE reload"
            context.response.print "data: update\n\n"
            context.response.flush
            @should_restart = false
            break
          end
          sleep 0.1
        end

+        puts "SSE Deactivated".colorize(:red)
        # SSE stop
      end
    end
```

<details><summary>Very Verbose Output:</summary>
<pre>
web     | GET /sign_in (84038b3c-298d-41fe-bb41-6a18f22299c4)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (13.22ms) (84038b3c-298d-41fe-bb41-6a18f22299c4)
web     | SSE Activated
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | SSE Loop 749326
web     | 
web     | GET /sign_in (08675d9f-fd18-4aeb-a0f1-f3b155377843)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (1.59ms) (08675d9f-fd18-4aeb-a0f1-f3b155377843)
web     | SSE Loop 749326
web     | SSE Activated
web     | SSE Loop 876529
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | 
web     | GET /sign_in (4e3f6485-a3e7-4b4d-85d3-87d3b4599666)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (1.54ms) (4e3f6485-a3e7-4b4d-85d3-87d3b4599666)
web     | SSE Activated
web     | SSE Loop 944547
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | 
web     | GET /sign_in (925aa16b-dbe9-4386-8b4e-70e1b28d3650)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (1.58ms) (925aa16b-dbe9-4386-8b4e-70e1b28d3650)
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Activated
web     | SSE Loop 148330
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | 
web     | GET /sign_in (dbe8ad87-07cd-4815-a8ba-0636b8b2c82d)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (1.93ms) (dbe8ad87-07cd-4815-a8ba-0636b8b2c82d)
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | SSE Activated
web     | SSE Loop 551843
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | SSE Loop 551843
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | 
web     | GET /sign_in (b977bd10-53a9-462d-aa1d-743132d2e0df)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (2.09ms) (b977bd10-53a9-462d-aa1d-743132d2e0df)
web     | SSE Loop 551843
web     | SSE Activated
web     | SSE Loop 26637
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | SSE Loop 551843
web     | SSE Loop 26637
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | SSE Loop 551843
web     | 
web     | GET /sign_in (21537ee9-4d86-435e-8dfc-e371da61affb)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (1.51ms) (21537ee9-4d86-435e-8dfc-e371da61affb)
web     | SSE Loop 26637
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | SSE Loop 551843
web     | SSE Loop 26637
web     | 
web     | GET /sign_in (cab4e25c-c142-4bae-b40e-4f6ddda306a9)
web     |  ▸ Handled by SignIns::New
web     |  ▸ Rendered SignIns::NewPage
web     |  ▸ Sent 200 OK (1.56ms) (cab4e25c-c142-4bae-b40e-4f6ddda306a9)
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | SSE Loop 551843
web     | SSE Loop 26637
web     | SSE Activated
web     | SSE Loop 724780
web     | SSE Loop 749326
web     | SSE Loop 876529
web     | SSE Loop 944547
web     | SSE Loop 148330
web     | SSE Loop 551843
</pre>
</details>

**Versions (please complete the following information):**
 - Lucky version 1.0.0-rc1
 - Crystal version 1.5.1

**Comment by robacarp** [comment]
Also perhaps relevant, the [Mozilla docs on SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) contain this warning. I don't think Crystal has any HTTP2 support yet.

> Warning: When not used over HTTP/2, SSE suffers from a limitation to the maximum number of open connections, which can be especially painful when opening multiple tabs, as the limit is per browser and is set to a very low number (6). The issue has been marked as "Won't fix" in [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=275955) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=906896). This limit is per browser + domain, which means that you can open 6 SSE connections across all of the tabs to www.example1.com and another 6 SSE connections to www.example2.com (per [Stackoverflow](https://stackoverflow.com/questions/5195452/websockets-vs-server-sent-events-eventsource/5326159)). When using HTTP/2, the maximum number of simultaneous HTTP streams is negotiated between the server and the client (defaults to 100).

**Comment by mdwagner** [comment]
Ah ok, I guess my implementation was a little naive when I thought just changing `@should_restart` would work across all requests (fibers?). I did not notice this in my initial testing, but it's definitely a bug.

I was already aware of the limitations of SSE, but I know some people swear by it, so I thought it was worth keeping around.

I think my new implementation would be to store each request Context in a list, that when a reload should happen, it just pops each one off and runs the reload logic, then only break the loop when the context is closed. We'll see if that works.

**Comment by mdwagner** [comment]
@robacarp would you be willing to try out some of my fixes with your local setup?
