### ISSUE TITLE
Error compiling prod/release tasks in Crystal 1.6 

### ISSUE THREAD

**Issue by robcole** [luckyframework/lucky#1750]
```
/ # crystal build --static --release --error-trace tasks.cr -o /usr/local/bin/lucky
In tasks.cr:12:1

 12 | require "./src/app"
      ^
Error: while requiring "./src/app"


In src/app.cr:4:21

 4 | Lucky::AssetHelpers.load_manifest "public/manifest.json"
                         ^------------
Error: expanding macro


In lib/lucky/src/lucky/asset_helpers.cr:12:8

 12 | {{ run "../run_macros/generate_asset_helpers", manifest_file }}
         ^--
Error: Error executing run (exit code: 1): ../run_macros/generate_asset_helpers public/manifest.json


stdout:

    unexpected token '<E at line 1, colu


stderr:

    Unhandled exception: unexpected token '<E at line 1, colu (JSON::ParseException)
      from ???
      from ???
      from ???
      from ???
      from ???
      from ???
      from src//homsrc/env/__libc_start_mai in 'libc_start_main_stage2'
```

Working on uploading a docker image for AMD/ARM architectures that should be able to trigger this fairly easily.

**Comment by jwoertink** [comment]
Are you using Vitejs? I see that your manifest file is named `manifest.json` instead of `mix-manifest.json`....

**Comment by robcole** [comment]
@jwoertink I'm using esbuild -- this is a project that works on 1.5.1 but fails on 1.6.0.

https://github.com/the-business-factory/hirobot.app/tree/preview/1.6.0 is a branch where compiling will fail. If you check that branch out, copy `.env.example` to `.env`, and run `docker build .` from the root you should eventually see the error. LMK what other info you need.

**Comment by robcole** [comment]
@jwoertink https://github.com/robcole/concierge is a clean repo that can reproduce this bug.

**Comment by robcole** [comment]
@jwoertink this might be better in 1.6.2 -- will LYK as one app works fine with Lucky + 1.6.2 right now.

**Comment by robcole** [comment]
@jwoertink [1.6.2](https://hub.docker.com/layers/robcole/crystal/1.6.2/images/sha256-3038c2e392bd37412efa6c6c0e4fc6936a5fbc9899ba6b04777905920a1cc696?context=explore) seems to fix this, I'm closing this issue.
