### ISSUE TITLE
MissingNestedParamError with only form data

### ISSUE THREAD

**Issue by watzon** [luckyframework/lucky#1782]
**Describe the bug**
I'm trying to save a file using a SaveOperation. The operation itself has no permitted params, just a file_attribute named file. When the params get passed to the save operation's `create` method, I get an error coming from [here](https://github.com/luckyframework/lucky/blob/main/src/lucky/params.cr#L239) which I assume is because the params are technically empty.

**To Reproduce**

> Example:

> 1. Generate a Lucky project '...'
> 2. Create a save operation for a model
> 3. Add `file_attribute :file` to the top of the save operation. No `permitted_params`.
> 4. Create an action which calls the save operation's `create` method, passing in `params`.
> 5. Attempt to call the route, passing in a file.

**Expected behavior**
I'd expect the file to get passed in just fine. But instead I get a `MissingNestedParamError`.

**Screenshots/code**

![image](https://user-images.githubusercontent.com/4535422/220248144-9dd56daa-dee0-4b8b-92b3-74e40b4613ed.png)

shard. Lock (please complete the following information):**
 - Lucky version (check in shard.lock): 1.0.0-rc1
 - Crystal version (`crystal --version`): 1.7.2
 - OS: Ubuntu 22.04 through WSL

**Comment by jwoertink** [comment]
Turns out, this should be fixed in 1.0.0 by https://github.com/luckyframework/avram/pull/894 If you get a chance, can you give that a try and if so, we can close this.

**Comment by jwoertink** [comment]
I'm gonna go ahead and close this. I'm pretty sure it's fixed. If anyone else runs in to it again, we can always reopen
