### ISSUE TITLE
Add a `--with-page` flag to gen.action.browser task

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1795]
Ref: https://github.com/luckyframework/lucky/discussions/1794

This would be `lucky gen.action.browser Posts::Index --with-page` which would generate 

```
src/actions/posts/index.cr
src/pages/posts/index_page.cr
```

Maybe the `lucky gen.page` task could also have a `--with-action` just for the inverse consistency too....

**Comment by jwoertink** [comment]
> Is there room for a combo-blaster generator

I'm open to one. It would need to be named something clear with the understanding that it's a BrowserAction being generated. I don't think you'd generate an ApiAction with a page since you'll usually just return JSON...

The other option suggested was using `lucky gen.resource` without the model, migration, operations, queries....

**Comment by zw963** [comment]
I consider only `lucky gen.action.browser Posts::Index --with-page` is enough, inverse no need. it rarely happens there exists page but no action?

**Comment by zw963** [comment]
I created two bash script for make create `CRUD only(no db)` and `Action + Page` more easier.

[luckygen.tar.gz](https://github.com/luckyframework/lucky/files/11114424/luckygen.tar.gz)


I do create a https://github.com/luckyframework/avram/pull/935 for refine the CRUD templates make it more consistent.

1. links use non keyword argument form.
2. Remove unnecessary namespaces.
