### ISSUE TITLE
build lucky project use Crystal 1.13.0-dev [4dce0d594]) cause 'strict_transport_security' error when running lucky.

### ISSUE THREAD

**Issue by zw963** [luckyframework/lucky#1902]
When i built a exists lucky app use `Crystal 1.13.0-dev [4dce0d594]` use --cross-compile and `zig cc`, after copy binary into remote VPS, i get following error:

```
Unhandled exception: The 'strict_transport_security' setting for Lucky::ForceSSLHandler was nil, but the setting is required.

Try this...

  Lucky::ForceSSLHandler.configure do |settings|
    settings.strict_transport_security = some_value
  end
 (Habitat::MissingSettingError)
```

But, if same lucky app built with `Crystal 1.12.2 [04998c0c7]`, no above error.

Maybe a error on newer Crystal compiler? or something else?

Thanks

**Comment by jwoertink** [comment]
Basically a duplicate of https://github.com/luckyframework/lucky/issues/1872 and will be fixed by https://github.com/luckyframework/lucky/pull/1900
