### ISSUE TITLE
Add helpers like those found in ActionView::Helpers (Rails)

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#209]
Things like:

- [x] number_to_currency http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html
- [ ] time_ago_in_words https://apidock.com/rails/ActionView/Helpers/DateHelper/time_ago_in_words
- [x] simple_format https://apidock.com/rails/ActionView/Helpers/TextHelper/simple_format
- [x] pluralize https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize unlike Rails, always require specifying the plural version of the word.

I think these can go in  a new module called `LuckyWeb::PageHelpers` and would be included in `LuckyWeb::HTMLPage`. If someone wants to help with this, feel free to tackle just one at a time.

**Comment by paulcsmith** [comment]
If someone decides to start on one of these, please comment here so two people don't accidentally do the same work. Thanks!

**Comment by actsasflinn** [comment]
I'm working on the inflector code now. I'm planning to port portions of ActiveSupport::Inflector and then make them available similar to ActionView::Helpers::TextHelper.

ActiveSupport is useful outside of the web package as inflections are used in various places in Rails. ActiveRecord particularly and various generators in particular. I started into creating some scaffold generators and found a shortcoming in lack of inflectors.

**Comment by ugisozols** [comment]
I'm going to try and tackle the `number_to_currency` 😎

**Comment by azbshiri** [comment]
I'm going to write `pluralize`

**Comment by paulcsmith** [comment]
@azbshiri Just a heads up that @actsasflinn has started on the inflector so that needs to be merged into the `luckyframework/support` repo first. 

Until that's in, maybe a good option would be `time_ago_in_words`? It's a pretty helpful one that I'd *love* to get in soon

**Comment by azbshiri** [comment]
#221

**Comment by actsasflinn** [comment]
I'm working on simple_format now

**Comment by actsasflinn** [comment]
👍
