### ISSUE TITLE
Change number_to_currency to print to the page with `text`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#250]
Instead of returning a String, the number_to_currency helper should print to the page using the `text` method.

**Comment by actsasflinn** [comment]
@paulcsmith if you ever implemented another template engine would this be ideal? What is the motivation for having the helpers append to @view directly? I just kind of wonder, say someone wanted to implement something like crustache, you'd essentially lose the utility of the helpers right? Returning a String seems less coupled to HTMLPage, no?

**Comment by paulcsmith** [comment]
@actsasflinn Those are some good points. I'll have to think about this a bit more. I think it would work fine with other templating engines because other Crystal templating engines also append to an IO. You can configure the name of the IO so I think it should work. But your point still stands that it might be too coupled.

**Comment by paulcsmith** [comment]
Thought about this a bit and I think it would be good to use `text` to output the currencies instead of returning a String. This will match the other text helpers.

When template support is added we can still make `text` work. I'll have to write up how that can be done later.
