### ISSUE TITLE
Browser-Sync refresh fails if port 3000 already taken

### ISSUE THREAD

**Issue by nicbet** [luckyframework/lucky#258]
If there is something running on `localhost:3000` already, `browser-sync` as part of the `lucky watch` command fails to reload the browser contents, even though changes are picked up and a `browser-sync reload` command is emmited. 

From the UI output it appears that it picks the next available port, e.g., `localhost:3001`.

**Comment by paulcsmith** [comment]
Thanks for reporting this. Fixed by https://github.com/luckyframework/lucky/pull/260 :)
