### ISSUE TITLE
Asset checking prevents use of variables

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky#267]
While I like the static asset checking, it prevents us doing things like:

```crystal
            link to: href do
                img src: asset("logos/#{name}.svg")
            end
```
<img width="438" alt="bildschirmfoto 2017-12-02 um 23 45 47" src="https://user-images.githubusercontent.com/68024/33520431-f922c868-d7ba-11e7-9c90-65657524ea9e.png">

instead we have to do
```crystal
            link to: href do
              case name
              when :github
                img src: asset("logos/github.svg")
              when :facebook
                img src: asset("logos/facebook.svg")
              when :xing
                img src: asset("logos/xing.svg")
              when :twitter
                img src: asset("logos/twitter.svg")
              end
              text name.to_s
            end
```

Can we mitigate this somehow? I guess that's exactly the difference between runtime and compile time checking. Compiler/Asset checker cant know whats going on when we use a variable, so it kinda makes sense. Feel free to close if by design.

**Comment by jdbann** [comment]
Maybe a good justification for an enum in Lucky Record?

http://api.rubyonrails.org/v4.1.0/classes/ActiveRecord/Enum.html

**Comment by hanneskaeufler** [comment]
Hm interesting point. In my case they actually are static, I just used a hash instead of an enum:

```
  SOCIALS = {
    :github => "...",
    :facebook => "...",
    :twitter => "...",
    :xing => "..."
  }
```

**Comment by paulcsmith** [comment]
@hanneskaeufler This is an excellent point, and this is the exact scenario I wanted to add to the guides, but sadly haven't had time to do. I want to add a `dynamic_asset` helper that doesn't do compile time checks, *but* in this case I think it is better to use `asset`, but use a macro so you still get compile time checks. Here's an example:

```crystal
macro social_link(service, href)
  link {{ href }} do
    img src: asset:("logos/{{ service.id }}.svg")
  end
end

# And use it like:

social_link(:twitter, "https://twitter.com")
social_link(:facebook, "https://facebook.com")
```

I think that should work in your case. Note that macros need to be defined *before* you use them, so it might make sense to put the macro in a `Blog::SocialLinkComponent` that you can include in the pages that need it

**Comment by paulcsmith** [comment]
I'm going to close this. Added an issue: https://github.com/luckyframework/lucky/issues/269 that should make it easier to handle dynamic assets. Thanks for starting the discussion!
