### ISSUE TITLE
Log what page was rendered only if it was returned at the end of the action

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#270]
Right now if you do this:

```crystal
render TestPage
render AnotherPage
```

There will be a log message saying TestPage was rendered and another saying AnotherPage was rendered. Only the one returned should get a log message

**Comment by ianagne** [comment]
My initial thought on this is to follow the logging pattern that `#add_debug_message` is using.  Except, we extend the Http::Server::Context with an overwritable property called `response_message`.  Then, we set the response message whenever calling `#render`, `#redirect`, or `#json`.  The change would have the added bonus of logging redirects and json, and any duplicate render calls would just overwrite the response message.  Thoughts?

**Comment by paulcsmith** [comment]
@ianagne That is an interesting idea, but I wonder if we could do something similar without further extending the Http::Server::Context. Maybe something like this would work:

1. Add a `@debug_message : String? = nil` instance var to `Lucky::Response` initializer
1. The `render`, `redirect`, `json`, etc. can initiailze the `LuckyResponse` with a nice debug message
1. In [`handle_response`](https://github.com/luckyframework/lucky/blob/3d15a40d47b8aa16b806c92c3b698ab54af642a0/src/lucky/renderable.cr#L36-L38) it checks for a debug_message on the response and adds to the context if it exists

Does that make sense?

**Comment by ianagne** [comment]
Sounds like a plan 👍

**Comment by paulcsmith** [comment]
Awesome! And just to be clear, were you planning to work on this? No pressure at all, I just wasn't sure if I should still plan to do this or not

**Comment by ianagne** [comment]
For sure, I should be able to tackle this today or tomorrow.

**Comment by paulcsmith** [comment]
Great :D Thanks
