### ISSUE TITLE
Discuss: Folder structure for views (JSON, HTML, etc.)

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#280]
@edwardloveall had some thoughts about folder structure https://github.com/luckyframework/website/pull/81#discussion_r155336002 

> Out of curiosity, why have a json directory instead of a serializers directory? Would you create an src/xml directory for serializing xml? Also, is seems like src/pages has an implicit meaning of HTML. Should we change it to html?

## What's it like right now

src/pages - for HTML pages and layouts
src/components - for HTML components/partials
src/json - for generating JSON responses 
src/xml (not auto-generated, but this would be the pattern) - if you wanted XML responses

### html, json, xml, etc. folders

src/html - for HTML pages *and* components?
src/json
src/xml

One advantage is that everything is named after it’s format, but it feels a bit strange to me for some reason. Maybe it’s that JSON is so generic. Is it for parsing JSON? JSON response?  Seems a bit too generic now that I think about it

### pages, components, and serializers

src/pages
src/components
src/serializers

This changes src/json and src/xml to just src/serializers. So the src/serializers directory might look like this:

```
src/
  serializers/
    users/
      show_json.cr
      show_xml.cr
```

## My thoughts
I am leaning toward keeping src/pages and src/components and changing src/json to src/serializers.

What do others think?

**Comment by hanneskaeufler** [comment]
I would be +1 on changing `src/json` to `src/serializers`. That is expressing whats supposed to go in there well.

**Comment by edwardloveall** [comment]
Yeah, I agree with `src/serializers`. The hierarchy is `Type` -> `Model` -> `Action` (if necessary).

Theoretically you could have an HTML serializer that lives in `/src/serializers`, like say if your app displayed HTML code, maybe?

To be honest, I don't love putting the format of the file in the name as in `show_json.cr`. Perhaps that naming is just optional or conventional and the real format is decided by whatever you're inheriting from/including.

**Comment by paulcsmith** [comment]
Agreed on all points. I’ll change the guide and the generated skeleton to be src/serializers and suggest using that naming for rendering as well: Users::ShowSerializer

Thanks for the feedback everyone 👍
