### ISSUE TITLE
3001 points to BrowserSync config page instead of proxying to lucky server

### ISSUE THREAD

**Issue by mxie** [luckyframework/lucky#287]
After running `lucky dev` and navigate to `localhost:3000`, it gets me here:

![browsersync 2017-12-08 15-47-15](https://user-images.githubusercontent.com/602470/33784503-20396998-dc2f-11e7-836f-018588347cbb.jpg)

And here is the output I get in the terminal (truncated):

```
15:44:10 web.1      |  [Browsersync] Copy the following snippet into your website, just before the closing </body> tag
15:44:10 web.1      |  <script id="__bs_script__">//<![CDATA[
15:44:10 web.1      |      document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.js?v=2.18.13'><\/script>".replace("HOST", location.hostname));
15:44:10 web.1      |  //]]></script>
15:44:10 web.1      |  [Browsersync] Access URLs:
15:44:10 web.1      |   -------------------------------------
15:44:10 web.1      |            UI: http://localhost:3001
15:44:10 web.1      |   -------------------------------------
15:44:10 web.1      |   UI External: http://192.168.2.62:3001
15:44:10 web.1      |   -------------------------------------
```
This means that I can't get auto-reload to work, so I just use port 5000 instead and manually reload.

**Comment by paulcsmith** [comment]
I can't seem to reproduce this and so far no one else has either. I'm going to close for now, but if someone sees this when they start the app, please comment and let me know so I can investigate further!

**Comment by mxie** [comment]
I don't think I saw this issue again - don't know what changed. I'm cool with this being closed for now. Thanks @paulcsmith!

**Comment by paulcsmith** [comment]
Thanks for confirming!

**Comment by annali04** [comment]
I am having the same issue. The access URLs http://localhost:3017 points to the config page while http://localhost:3016 is the correct URL.

<img width="1090" alt="Screen Shot 2019-05-06 at 3 14 17 PM" src="https://user-images.githubusercontent.com/5592165/57258899-ac109180-7012-11e9-98dc-422bfff16813.png">
<img width="1095" alt="Screen Shot 2019-05-06 at 3 14 34 PM" src="https://user-images.githubusercontent.com/5592165/57258912-b3d03600-7012-11e9-9581-0e913354d5de.png">
