### ISSUE TITLE
Make `options_for_select` generic so it works with any kind of field

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#292]
Here is a rough example:

```crystal
class Field(T)
  def initialize(@value : T)
  end
end

def options_for_select(field : Field(T), items : Array(T)) forall T
end

field = Field(Int32).new(1)

options_for_select(field, [1])
```

This could be used in place of the hardcoded list of allowed values that are there right now: https://github.com/luckyframework/lucky/blob/7a5640e8dc7dd18e738bf3a13096f036e53680b3/src/lucky/tags/select_helpers.cr#L2

**Comment by jwoertink** [comment]
long time coming!
