### ISSUE TITLE
Asset helper doesn't work in included modules

### ISSUE THREAD

**Issue by JoshJuncker** [luckyframework/lucky#293]
I'm a newbie to Crystal and its possibilities as well as Lucky, so go easy on me :).
Expected Result:  I would expect a shared partial to be able to utilize the asset_helper.
Example Code:

module Shared::Header
&nbsp;def render_header
&nbsp;&nbsp;img src: asset("images/main_logo.png")
&nbsp;end
end

class Home::IndexPage < MainLayout
&nbsp;include Shared::Header
&nbsp;def inner
&nbsp;&nbsp;render_header
&nbsp;end
end

Actual Result:
https://gist.github.com/JoshJuncker/d76db51dae1cc956433df8137bdbeba4
15:52:22 web.1      |  in src/components/shared/header.cr:3: expanding macro
15:52:22 web.1      |      img src: asset("images/main_logo.png")
15:52:22 web.1      |               ^~~~~
15:52:22 web.1      |  in lib/lucky/src/lucky/asset_helpers.cr:7: undefined constant ASSET_MANIFEST
15:52:22 web.1      |      {% if ASSET_MANIFEST[path] %}
15:52:22 web.1      |            ^~~~~~~~~~~~~~

Let me know if you need more info.

**Comment by paulcsmith** [comment]
I believe you did things right, and this is a bug. Thanks for reporting it! To get around it, I believe you can wrap the method in `macro included`:

```crystal
macro included
  def render_header
    # The method body
  end
end
```

Let me know if that workaround works for you :)
