### ISSUE TITLE
Hide initial compile message if there is already a helpful message

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#294]
I noticed this in this commit: https://github.com/luckyframework/lucky/pull/291#discussion_r156271901

It's probably unlikely to happen on first compile, but if Lucky raises a helpful message, then it shouldn't show the initial compile error: https://github.com/luckyframework/lucky/blob/9fbd086e3bf16cba757c91f8a421af5dc475787f/tasks/watch.cr#L94-L106

**Comment by matthewmcgarvey** [comment]
I think the error printed when compilation fails complements the compile error more than detracts so I'm going to close this for now https://github.com/luckyframework/lucky/blob/8d7bb5702d92e233c90ae29f743c7780450501af/tasks/watch.cr#L167-L180
