### ISSUE TITLE
Mismatching types between luck_record and lucky

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky#302]
Ideally I want to do e.g.
```crystal
class Blog::IndexPage < MainLayout
  needs posts_count : Int32
  needs current_page : Int32
end
```
which is already a bit weird because I personally don't care if it is a 64 or 32 bit integer. But just `needs`ing an `Int` doesnt work. So my Action specifies a param `page` as an `Int32`. However lucky record yields an `Int64` with the `count` method. So I need to cast into an `Int32` here which is ugly.

```crystal
class Blog::Index < BrowserAction
  param page : Int32 = 1

  get "/" do
    posts = PostQuery.new.latest(page: page).results
    posts_count = Int32.new(PostQuery.new.published.count)
    render Blog::IndexPage, posts: posts, posts_count: posts_count, current_page: page
  end
end
```
I could of course define everything to `Int64`, but then my tests complain when I do
```crystal
private def rendered(posts, posts_count = 5, on_page = 1)
  Blog::IndexPage.new(
    flash: empty_flash,
    posts: posts,
    posts_count: posts_count,
    current_page: on_page).render.to_s
end
```
because the default for integer literals seems to be  `Int32` again. So somehow I can't seem to match up my types here nicely. Am I doing something stupid (please excuse my crystal noobness) or can we improve this somehow?

**Comment by paulcsmith** [comment]
@hanneskaeufler Crystal is working on adding a generic `Int` type that encapsulates both Int32 and Int64, but until that's ready this will be a bit tricky to handle. I'll try to come up with a good stop-gap solution.

For now, I would consider using `to_i` on the count. That will return an Int32 and is a bit less verbose. Maybe that'll help clean things up in the meantime?

**Comment by hanneskaeufler** [comment]
Yup thats exactly what I did, guess waiting on crystal is what I'll do in the meantime :)
```diff
-    posts_count = Int32.new(PostQuery.new.published.count)
+    posts_count = PostQuery.new.published.count.to_i
```

**Comment by paulcsmith** [comment]
https://github.com/luckyframework/lucky_record/commit/79b78cb0509b76686cc947c392869c783f3a3fe5 and https://github.com/crystal-lang/crystal/pull/6074

will make it so you can use Int64 columns and the PR in Crystal will make it so you can pass an Int32 and it will automatically be casted to an Int64. This should resolve the issue once both are released :)
