### ISSUE TITLE
Add viewport meta tags to MainLayout by default

### ISSUE THREAD

**Issue by mikeeus** [luckyframework/lucky#320]
Is there any downside to including the viewport meta tag in the `MainLayout` by default?

`<meta name="viewport" content="width=device-width, initial-scale=1">`

I did it manually by adding `meta name: "viewport", content: "width=device-width, initial-scale=1"` to `MainLayout`'s head tag, and we could do the same by default.

(Added by maintainer) ->If you'd like to work on this, here's the rough steps required:

https://github.com/luckyframework/lucky/issues/320#issuecomment-355183637

**Comment by paulcsmith** [comment]
Great idea! I think this would also be nice to have as a helper tag like `responsive_meta_tag` in the `SpecialtyTags` module. Then it would be used in the lucky_cli repo in MainLayout as you suggested.

If you want to tackle this, LMK, otherwise I'll add the in the next couple weeks.

**Comment by mikeeus** [comment]
Good idea, this would be a great first issue for anyone interested.

**Comment by paulcsmith** [comment]
Sounds good! Here are the steps if anyone wants to add this:

1. Add a test for `responsive_meta_tag` in https://github.com/luckyframework/lucky/blob/master/spec/lucky/specialty_tags_spec.cr
1. Add `responsive_meta_tag` to https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/specialty_tags.cr
1. Add `responsive_meta_tag` to the generated `MainLayout` https://github.com/luckyframework/lucky_cli/blob/e7705ca8d184ce671c1e711afc7e2027f3d2d1f4/src/web_app_skeleton/src/pages/main_layout.cr#L17-L23 in Lucky CLI

**Comment by ugisozols** [comment]
I'd like to take this 😃

**Comment by ugisozols** [comment]
I got buried with work stuff. @rmontgomery429 thx for taking care of this!
