### ISSUE TITLE
Include a "Not Found" default page

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky#337]
Currently, the crystal http handler fallback is shown when neither a route nor a static file matched. So you will simply see "Not Found". It could be convenient to include a fallback action/page that renders a proper 404 page. Can be added manually for sure (e.g. https://github.com/hanneskaeufler/blog/pull/36), but I can see that as a convenience feature for lucky to include out of the box.

**Comment by paulcsmith** [comment]
Definitely! I want to design a nicer looking default page that is generated with new apps so it’s not just boring plain text that is easy to miss. Thanks for creating an issue
