### ISSUE TITLE
Error running bin/setup on new project

### ISSUE THREAD

**Issue by tommyschaefer** [luckyframework/lucky#344]
Hi there!

I decided to try out Lucky today, but I've run into a bit of a snag.

I followed the [installation guide](https://luckyframework.org/guides/installing/), but ran into an issue when running `bin/setup`.

I am using macOS Sierra, the output of `crystal -v` is:
```
Crystal 0.24.1 (2017-12-26)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

and my stack trace can be found [here](https://gist.github.com/tommyschaefer/cff6af90d6750268c55bb15027003395).

It looks like the error is being raised from [this line in the Crystal source](https://github.com/crystal-lang/crystal/blob/master/src/process.cr#L321), but I don't know enough Lucky / Crystal to really understand why 😃

Thank you so much for your time!

**Comment by tommyschaefer** [comment]
Oops! Just realized that this would belong in the `lucky_cli` repository, and that there's already a issue there!

Sorry for the trouble!

**Comment by paulcsmith** [comment]
Hi @tommyschaefer! Thanks for reporting. There is a similar issue here: https://github.com/luckyframework/lucky_cli/issues/147

I've started a conversation here: https://gitter.im/crystal-lang/crystal?at=5a4fd81b5355812e5757d6a0 to try to figure it out :)
