### ISSUE TITLE
Should checkboxes have a default value?

### ISSUE THREAD

**Issue by tommyschaefer** [luckyframework/lucky#345]
Hi there!

First off, I just started playing with Lucky this afternoon, so I could be completely missing something! 😄

I have a model `Book`:

```crystal
class Book < BaseModel
  table :books do
    field title : String
    field read : Bool
  end
end
```

and a `Books::NewPage`:

```crystal
class Books::NewPage < MainLayout
  needs book_form : BookForm

  def inner
    render_book_form(@book_form)
  end

  private def render_book_form(f)
    form_for Books::Create do
      ul do
        f.errors.each do |field, errors|
          li "#{field} #{errors.first}"
        end
      end

      div do
        label_for f.title
        text_input f.title
      end

      div do
        label_for f.read
        checkbox f.read
      end

      submit "Save Book"
    end
  end
end
```

When I submit this form, with the "Read" checkbox checked, `Books::NewPage` is rendered with an error `read is invalid` (and if I wasn't just outputting the first error, I'm assuming `read is required`?).

When inspecting the `params`, I saw:

```
"book:read" => ["0", ""]
```

Through some experimenting, I found that changing the checkbox code to:

```crystal
checkbox f.read, value: "1"
```

made everything have the correct behavior.

Is this the standard way to link checkboxes with boolean fields in a model, or am I doing something wonky 😄? If so, would it maybe make sense to have the `checkbox` helper use a default `value` of `"1"`?

Thank you so much for your time! I'm really enjoying playing around with Lucky and appreciate all of the work that has been put into it!

**Comment by tommyschaefer** [comment]
Is it okay if I take this on? 😄

**Comment by paulcsmith** [comment]
@tommyschaefer That would be wonderful! Thanks!

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky/commit/8234b696fdd1ca5e55aadac2aedb4b5eabf531b0
