### ISSUE TITLE
`button` helper outputs a html link, which is confusing

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky#346]
If `button "Test", to: ButtonHelpers::Index` renders `<a href="/button_helpers">Test</a>` I am not sure I understand. How can I render an actual html button then? I think we should stick to representing the html tags more or less directly (sure, rename `p` to `para` if its a crystal keyword).

**Comment by paulcsmith** [comment]
This was likely just a dumb copy-paste bug. `button` should render a `button` tag. If you'd like to make a PR I'd greatly appreciate it :D
