### ISSUE TITLE
Add to_sentence helper

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#347]

**Comment by tommyschaefer** [comment]
Hi there! I was wondering if it might be okay for me to give this a shot? No problem at all if you or anyone else would prefer to take it on yourselves 😄

**Comment by paulcsmith** [comment]
@tommyschaefer That would be great! It would go here: https://github.com/luckyframework/lucky/blob/master/src/lucky/page_helpers/text_helpers.cr

For the first pass it doesn't need any locale/i18n options. It should work pretty much identically to the Rails version of to_sentence, but it will use the `text` method to output the result to the page.

LMK if you have any questions. I'm happy to help :)
