### ISSUE TITLE
Should text helpers append to the view directly?

### ISSUE THREAD

**Issue by tommyschaefer** [luckyframework/lucky#349]
Hi there!

While working on #348, I started to think that maybe the text helpers should return strings rather than append to the view directly.

In the context of #348, I'm imagining the following scenario:

I have:
```crystal
class TestPage
  include Lucky::HTMLPage

  needs list : Array

  def render
    to_string(list)
  end
end
```

which renders when given a list `%(a b c)`:

```text
a, b, and c
```

Now, I would like to render `I have the following items: a, b, and c`

To me, I think it feels a bit more natural to write:

```crystal
text "I have the following items: #{to_sentence(list)}"
```

over:

```crystal
text "I have the following items: "
to_sentence(list)
```

I also wonder if appending to the view is maybe a bit too much for a text helper to do? To me, it feels like that maybe falls outside of the helpers responsibility? How do you all feel about this?

Thank you so much for your time! Like I said in one of my other issues, I'm really enjoying Lucky and have a tremendous appreciation for all of the work that has been put in to it! 😄

**Comment by jwoertink** [comment]
Now that https://github.com/luckyframework/lucky/pull/781 has been merged in, the next version will have this change. Text helpers will return a string instead of rendering directly to view.
