### ISSUE TITLE
Add SQL logging page

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#357]
Make it so that you can see all the SQL that ran for a particular request. I'll add more details later.

**Comment by ducdetronquito** [comment]
This would be a really neat built-in feature !

I work regularly with Django and the [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar) is a really great tool to analyse the SQL queries details on a given view. I hope it could give you some inspiration on this topic.

Have a great day :)

**Comment by paulcsmith** [comment]
@ducdetronquito I've never seen that. That looks great and will definitely help with making the SQL debugger in Lucky. Thanks for the tip :)

**Comment by matthewmcgarvey** [comment]
We've done this and it is called 🎉🎉🎉 [Breeze](https://github.com/luckyframework/breeze) 🎉🎉🎉
