### ISSUE TITLE
Add input type text autofocus

### ISSUE THREAD

**Issue by ChangJoo-Park** [luckyframework/lucky#371]

**Comment by paulcsmith** [comment]
Hey @ChangJoo-Park! Thanks for reporting this. You can do this now like so:

```crystal
text_input f.whatever, autofocus: "true"
```

I believe that should do the trick. Let me know if that works for you and I'll close the issue

**Comment by ChangJoo-Park** [comment]
@paulcsmith Thank you for reply :) 

It works well! 

before I tried `autofocus: true` and `autofocus` only

**Comment by paulcsmith** [comment]
Great! I would like to make it work with `true`. That's on my todo list. I think it's more intuitive
