### ISSUE TITLE
Error while setting up Lucky on Mac OS

### ISSUE THREAD

**Issue by davidwessman** [luckyframework/lucky#373]
### Versions
MacOS: 10.13.2
Crystal, installed via brew.
```
Crystal 0.24.1 (2018-01-27)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```
Lucky 0.8.3 installed via Brew.

## Issue
I followed the [installation guide](https://luckyframework.org/guides/installing/) and installed all dependencies as well as Lucky. I also added `pkgconfig` to the path.

When I run any `lucky` cli command I get the error:
```
➜  ~ lucky -v
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.2.dylib
  Referenced from: /usr/local/bin/lucky
  Reason: image not found
```

I talked to @edwardloveall and he told me to write this issue.

**Comment by davidwessman** [comment]
Worked great with the new version on Brew!, thanks for the help! @paulcsmith

**Comment by paulcsmith** [comment]
So glad it worked for you with the new version!
