### ISSUE TITLE
Fix TimeHelpers to consider 28 days as being "about a month"

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#381]
Currently, it requires 30 or more days to for the time helpers to consider it `about a month`

```crystal
distance_of_time_in_words(Time.now, Time.now + 30.days) # "about a month"
distance_of_time_in_words(Time.now, Time.now + 29.days) # "29 days"
```

However, since we're in February, 28 (or 29 days) is actually the month length, so calculations like `+ 1.month` will not return `about a month` but `28 days`. This breaks the test at `spec/lucky/time_helpers_spec.cr`

I think we should change the the range to be include 28 or more days as being `about a month`.

**Comment by paulcsmith** [comment]
I agree. 28 days should be considered "about a month"

Thanks for opening the issue!
