### ISSUE TITLE
Making a more interactive built-in debug page

### ISSUE THREAD

**Issue by yjukaku** [luckyframework/lucky#382]
@paulcsmith Thanks for all of your work on this project.

I was taking a look at https://github.com/luckyframework/lucky/issues/355 and see that it was closed because of a PR that styled the generated error page.

I know you wrote the original issue, but is this really what you meant? I thought it was in reference to the pictured page below. I did some work to make the default error page be a little more useful/interactive and wanted to know if it was worth a PR. I used Rails' exception page as a guide.

With an exception raised by `raise "This is the message"` in a Lucky::Action

# Before

![screen shot 2018-02-03 at 1 33 32 pm](https://user-images.githubusercontent.com/908365/35770335-fb0bcb9a-08e6-11e8-80f7-afdc96bedc03.png)

# After

![out](https://user-images.githubusercontent.com/908365/35770366-b895e3bc-08e7-11e8-923a-f7320567d1cd.gif)

**Comment by paulcsmith** [comment]
That looks awesome! Yes, I'd love to see a PR for that 👍

**Comment by yjukaku** [comment]
Please see #389 for my first run at this. 👍
