### ISSUE TITLE
Add api only project support

### ISSUE THREAD

**Issue by timkendall** [luckyframework/lucky#383]
What are your guys thoughts on implementing an API-only option for the `init` command? It would basically nuke the `pages` and `forms` folders along with all of the client-side dependencies (i.e Browsersync, Babel, etc.).

**Comment by paulcsmith** [comment]
Definitely something that will be added! Just haven't quite got to that yet. 

BTW, there is a WIP API guide. It may help you in building an API with Lucky: https://github.com/luckyframework/website/pull/81

**Comment by paulcsmith** [comment]
Closing because we've got an issue here: https://github.com/luckyframework/lucky_cli/issues/37

Feel free to comment there if you've got ideas.

Also the guide for building an API is up! https://luckyframework.org/guides/writing-json-apis/
