### ISSUE TITLE
Add Params.to_h

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#415]
So people have an escape hatch when they need to do custom stuff.

Also so they can pretty print params to see everything available

**Comment by jwoertink** [comment]
For this, are you thinking it would do all the data conversions? Like "page=1" would be `{"page" => 1}`, or would it just assume everything is `Hash(String, String)`, and then let the developer do their own data conversions?

**Comment by paulcsmith** [comment]
Great question. It would do everything as a string and let developers handle conversions. It would also convert nested params to nested hash so the type signature would be something like this: `Hash(String, String | Hash(String, String)`

Example:

```crystal
# page=1
# user:name=Paul
# Would produce:
{
  "page" => "1",
  "user" => {
    "name" => "Paul"
  }
}
```

And once I add support for arrays of values it would also be capable of having an array of hashes, but that can come later :)
