### ISSUE TITLE
Error when compiling documentation (crystal docs)

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#416]
When running `crystal docs`, the following error comes out.

```
Unhandled type in `name`: Lucky::Action+:Class
Crystal::Doc::Type#name:String
Crystal::Doc::Type#full_name_without_type_vars<String::Builder>:String::Builder
Crystal::Doc::Type#full_name<String::Builder>:(String::Builder | Nil)
Crystal::Doc::Method#args_to_html<String::Builder, Bool>:(String::Builder | Nil)
Crystal::Doc::Method#id:String
Crystal::Doc::MethodSummaryTemplate#to_s<File>:File
Crystal::Doc::Generator#generate_types_docs<Array(Crystal::Doc::Type), String, Array(Crystal::Doc::Type)>:Nil
Crystal::Doc::Generator#generate_types_docs<Array(Crystal::Doc::Type), String, Array(Crystal::Doc::Type)>:Nil
Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil)
main

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

It was posted on the crystal-lang repo but punted back to Lucky here: https://github.com/crystal-lang/crystal/issues/5812

I haven't yet been able to track down where this is occurring. For now, I've been generating documentation by running specific files, i.e.: `crystal docs src/lucky/routeable.cr` which works fine.

**Comment by paulcsmith** [comment]
I'm going to close this and reopen on Crystal because this doesn't seem like an issue with Lucky

**Comment by edwardloveall** [comment]
I believe they have an issue for it, gotta find it, one sec

**Comment by paulcsmith** [comment]
That's ok! I opened a new one here https://github.com/crystal-lang/crystal/issues/6201

I've tried commenting on already closed issues and they tend to get ignored. I did link to the old one though in case it is helpful to the Crystal team
