### ISSUE TITLE
Button tag generates link i.e. 'a'

### ISSUE THREAD

**Issue by ianpurton** [luckyframework/lucky#420]
Whilst trying to get bootstrap navigation working I needed to do the following

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

So I use the following lucky tags...

    button to: "", class: "navbar-toggler", "aria-controls": "navbarSupportedContent", 
        "aria-expanded": "false", "aria-label": "Toggle navigation",
        "data-target": "#navbarSupportedContent", "data-toggle": "collapse", 
        type: "button" do 
        span class: "navbar-toggler-icon"
    end

However this generates...

    <a href="" class="navbar-toggler" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </a>

So I think that it should generate a button tag not an 'a' tag.

**Comment by paulcsmith** [comment]
Thanks for reporting. This was fixed by https://github.com/luckyframework/lucky/pull/350

It will be in the next release 🎉
