### ISSUE TITLE
migrations fail silently if unable to connect to database

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#423]
If the database connection fails, "lucky db.migrate" simply exits without any message. It happens to me if the database user name or password isn't set, if the password is wrong, or if postgres isn't running.

**Comment by paulcsmith** [comment]
Hi @BrucePerens! This is fixed by https://github.com/luckyframework/lucky_migrator/pull/95

You can set the branch to master in your shard if you'd like to use it now

```
# in shard.yml
github: luckyframework/lucky_migrator
branch: master
```
