### ISSUE TITLE
Custom 404 Handling

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#436]
We have a case where we need to globally catch all 404, and send traffic to a single action which could be the homepage with an additional query param added or something like that. Being able to raise a `NotFound` and send to `Errors::Show` would probably be fine provided we have access to the URL they were trying to get to, and we can redirect the user from there to a different page.

Here's a visual example
```
Intercept 404, grab data, 302 redirect somewhere else
mysite.com/affiliate/sdf3f2/track.php => affiliates.mysite.com?old_code=sdf3f2
```

**Comment by paulcsmith** [comment]
This has been mostly addressed, but the RouteNotFoundError should add the HTTP::Context so that you can get at the request uri/params

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky/commit/a5d2b4d1b11493f2c2e915f545273f4bb84566ac
