### ISSUE TITLE
private def handle_response(_response : T) gets wrong object name

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#437]
Code was merged in #291 

Version::Index returns the wrong type, but the error message is about Version::Update . Something about this macro doing  forall T, perhaps?
It's really difficult to find the bug that way!

**Comment by paulcsmith** [comment]
@BrucePerens Could you provide a code sample of what the action looks like, and the stacktrace. I know the stacktrace is pretty hairy for this bug, but it would be helpful

**Comment by BrucePerens** [comment]
Minimal Lucky application, added this action:

class Version::Update < BrowserAction
  action do
    nil
  end
end

It complains about Home::Index!

Error in src/server.cr:22: instantiating 'HTTP::Server#listen()'

server.listen
       ^~~~~~

in /usr/share/crystal/src/http/server.cr:160: instantiating 'listen(Bool)'

  def listen(reuse_port = false)
  ^

in /usr/share/crystal/src/http/server.cr:163: expanding macro

      spawn handle_client(server.accept?)
      ^

in macro 'spawn' /usr/share/crystal/src/concurrent.cr:95, line 9:

   1.   
   2.     ->(
   3.       
   4.         __arg0 : typeof(server.accept?),
   5.       
   6.       
   7.       ) {
   8.       spawn(name: nil) do
>  9.         handle_client(
  10.           
  11.             __arg0,
  12.           
  13.           
  14.         )
  15.       end
  16.     
  17.       }.call(server.accept?)
  18.     
  19.   

instantiating 'handle_client((TCPSocket | Nil))'
in /usr/share/crystal/src/http/server.cr:190: instantiating 'HTTP::Server::RequestProcessor#process(IO+, IO+)'

    @processor.process(io, io)
               ^~~~~~~

in /usr/share/crystal/src/http/server/request_processor.cr:16: instantiating 'process(IO+, IO+, IO::FileDescriptor)'

  def process(input, output, error = STDERR)
  ^

in /usr/share/crystal/src/http/server/request_processor.cr:39: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

          @handler.call(context)
                   ^~~~

in /usr/share/crystal/src/http/server/handlers/compress_handler.cr:12: expanding macro

    {% if flag?(:without_zlib) %}
    ^

in macro 'macro_139688483708416' /usr/share/crystal/src/http/server/handlers/compress_handler.cr:12, line 12:

   1. 
   2.       request_headers = context.request.headers
   3. 
   4.       if request_headers.includes_word?("Accept-Encoding", "gzip")
   5.         context.response.headers["Content-Encoding"] = "gzip"
   6.         context.response.output = Gzip::Writer.new(context.response.output, sync_close: true)
   7.       elsif request_headers.includes_word?("Accept-Encoding", "deflate")
   8.         context.response.headers["Content-Encoding"] = "deflate"
   9.         context.response.output = Flate::Writer.new(context.response.output, sync_close: true)
  10.       end
  11. 
> 12.       call_next(context)
  13.     

instantiating 'call_next(HTTP::Server::Context)'
in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in /usr/share/crystal/src/http/server/handlers/error_handler.cr:15: instantiating 'call_next(HTTP::Server::Context)'

      call_next(context)
      ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in /usr/share/crystal/src/http/server/handlers/log_handler.cr:11: instantiating 'Time:Class#measure()'

    elapsed = Time.measure { call_next(context) }
                   ^~~~~~~

in /usr/share/crystal/src/http/server/handlers/log_handler.cr:11: instantiating 'Time:Class#measure()'

    elapsed = Time.measure { call_next(context) }
                   ^~~~~~~

in /usr/share/crystal/src/http/server/handlers/log_handler.cr:11: instantiating 'call_next(HTTP::Server::Context)'

    elapsed = Time.measure { call_next(context) }
                             ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in lib/lucky/src/charms/static_file_handler.cr:10: instantiating 'super(HTTP::Server::Context)'

    super(context)
    ^~~~~

in /usr/share/crystal/src/http/server/handlers/static_file_handler.cr:29: instantiating 'call_next(HTTP::Server::Context)'

        call_next(context)
        ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in /usr/share/crystal/src/http/server/handlers/static_file_handler.cr:29: instantiating 'call_next(HTTP::Server::Context)'

        call_next(context)
        ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in /usr/share/crystal/src/http/server/handlers/websocket_handler.cr:39: instantiating 'call_next(HTTP::Server::Context)'

      call_next(context)
      ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in lib/lucky/src/lucky/error_handler.cr:14: instantiating 'call_next(HTTP::Server::Context)'

    call_next(context)
    ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in lib/lucky/src/lucky/flash.cr:18: instantiating 'call_next(HTTP::Server::Context)'

        call_next(context)
        ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in lib/lucky/src/lucky/http_method_override_handler.cr:11: instantiating 'call_next(HTTP::Server::Context)'

    call_next(context)
    ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in lib/lucky/src/lucky/log_handler.cr:15: instantiating 'call_next(HTTP::Server::Context)'

    call_next(context)
    ^~~~~~~~~

in /usr/share/crystal/src/http/server/handler.cr:24: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in lib/lucky/src/lucky/route_handler.cr:10: instantiating 'Lucky::Action+#perform_action()'

      handler.payload.new(context, handler.params).perform_action
                                                   ^~~~~~~~~~~~~~

in lib/lucky/src/lucky/renderable.cr:38: 
Home::Index returned (Lucky::Response | Nil), but it must return a Lucky::Response.

Try this...
  ▸ Make sure to use a method like `render`, `redirect`, or `json` at the end of your action.
  ▸ If you are using a conditional, make sure all branches return a Lucky::Response.

    handle_response(response)
    ^~~~~~~~~~~~~~~

**Comment by paulcsmith** [comment]
Yikes! Thanks for the stacktrace and example. This makes sense. I'll try to tackle this for next release

**Comment by paulcsmith** [comment]
It seems this may be an issue in Crystal, but I need more time to track it done. For now I'm going to remove this special error-handling and add it back later. That's better than giving people incorrect instructions. Note that a compile-time error will still be raised, it will just be a generic Crystal error
