### ISSUE TITLE
Improvable error: "missing argument: route_params"

### ISSUE THREAD

**Issue by neurodynamic** [luckyframework/lucky#443]
```
/lib/lucky/src/lucky/renderable.cr:13, line 1:
07:05:06 web.1      |  >  1.     view = Users::CheckYourEmail.new(
07:05:06 web.1      |     2.       context: context,
07:05:06 web.1      |     3.       
07:05:06 web.1      |     4.         id: user.id,
07:05:06 web.1      |     5.       
07:05:06 web.1      |     6.       
07:05:06 web.1      |     7.     )
07:05:06 web.1      |     8.     body = view.perform_render.to_s
07:05:06 web.1      |     9.     Lucky::Response.new(
07:05:06 web.1      |    10.       context,
07:05:06 web.1      |    11.       "text/html",
07:05:06 web.1      |    12.       body,
07:05:06 web.1      |    13.       debug_message: log_message(view),
07:05:06 web.1      |    14.     )
07:05:06 web.1      |    15.   
07:05:06 web.1      |  missing argument: route_params
07:05:06 web.1      |  Overloads are:
07:05:06 web.1      |   - Lucky::Action.new(context : HTTP::Server::Context, route_params : Hash(String, String))
```

I'm getting this error when passing an action to `render` instead of a page. Took me a while to figure out what was happening, so I wanted to flag it as something where a more specific error message for this particular situation might be useful, e.g. `Hint: you may be passing an action to a method that is expecting a page` or similar.

I would be happy to attempt this myself, but I have no idea how creating custom errors like that would work in Crystal or Lucky in particular. I don't suppose there's a guide somewhere?

**Comment by paulcsmith** [comment]
Good point, and thanks for reporting this. I want to make sure the error experience is the best it can be.

I'm going to refactor the render method soon and it will raise if you try to pass an Action to it. I'll close this once that's done
