### ISSUE TITLE
Discussion: rename `action/nested_action` -> `route/child_route`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#453]
After a chat with @edwardloveall it seemed like the `action/nested_action` macro may not be that clear.

One thought is changing it to `route/child_route`:

```crystal
class Users::Show < BrowserAction
  route do
    # do something...
  end
end

class Projects::Tasks::Show < BrowserAction
  # Or nested_route
  child_route do
    # do something...
  end
end
```

Is this any clearer? Any other suggestions?

**Comment by jwoertink** [comment]
I can see how it might be confusing having `action` expand to a route. Why `child_route` as opposed to `nested_route` though? The nested makes sense to me. Maybe @russ can chime in here on that.

**Comment by paulcsmith** [comment]
I'd be ok with `nested_route` as well, but I think `route` makes more sense than `action` since it is generating a route and route helpers.

Thanks for your thoughts!

**Comment by edwardloveall** [comment]
I agree that `route` is the important part. Another alternate for `child` or `nested` could be `namespaced` which is what [rails uses](http://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing).

But I think nested is fine.

**Comment by paulcsmith** [comment]
@edwardloveall Maybe a third option would be better because child/nested may not be as clear as I had hoped. "Namespaces" wouldn't work because they are automatically inferred in Lucky so using child/nested/whatever means that it is a nested resource:

```crystal
class Admin::Users::Index < BrowserAction
  # Route is "/admin/users"
  route do
  end
end

# Whereas using nested/child doesn't have to do with namespaces, it defines a sort of "belongs_to" relationship
class Admin::Projects::Tasks::Index < BrowserAction
  # "/admin/projects/:project_id/tasks"
  child_route do
   end

  # With just `route`
  # "/admin/projects/tasks"
  route do
  end
end
```

Does that make sense? Maybe there's a better name than child/nested?

**Comment by edwardloveall** [comment]
Right you are. I got them mixed up. I think `nested` is good. I get why you would use `child`, but for whatever reason `nested` jumps to mind for me before `child` does.

**Comment by jwoertink** [comment]
@paulcsmith I like the idea of exposing that third option there. It would give a little extra flexibility. @russ and I actually have a rails app with 2 endpoints that point to the same action where we can return slightly different query based on what's passed.

**Comment by paulcsmith** [comment]
I think I'm going to go forward with `route/nested_route` It seems that seems clearer than what is there now. 

If someone comes up with some new ideas they think are clearer, feel free to post even once this is closed

**Comment by azbshiri** [comment]
I think `subroute` is a option too.
