### ISSUE TITLE
Stuttering process manager

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#467]
Using [foreman](https://github.com/ddollar/foreman) or [overmind](https://github.com/DarthSim/overmind) with both `lucky dev` and just calling them directly with `foreman start -f Procfile.dev` or `overmind start -f Procfile.dev` causing the assets output to stutter. 
<img width="1034" alt="screen shot 2018-05-16 at 9 53 01 am" src="https://user-images.githubusercontent.com/2391/40131913-248c341a-58f0-11e8-9f9d-2ce6fca092c9.png">
<img width="631" alt="screen shot 2018-05-16 at 9 58 49 am" src="https://user-images.githubusercontent.com/2391/40131927-2d126f28-58f0-11e8-843a-ecc5fa9a5a9c.png">

This happens to 3 of us on our team. We're all using latest master of lucky, different process managers, and all using bash shells with laravel mix. This only happens with the assets output. The web output is fine. 

Here's the `Procfile.dev`
```
web: lucky watch
assets: bin/compile_assets --watch --display=minimal
```

**Comment by paulcsmith** [comment]
I'm fairly certain this is an issue with one of the packages or with webpack and not Lucky so I'll go ahead and close this. If someone else sees this, please comment with your webpack settings and package.json. Maybe we can track down the culprit that way!

**Comment by jwoertink** [comment]
Just leaving a note in case anyone else comes across this. It was for sure one of the dependencies I was adding in. Once I ripped them out, it stopped doing it. If I figure out exactly which one, I'll update this.
