### ISSUE TITLE
[Lucky 0.10.0] Static assets not found

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky#473]
I am currently upgrading to 0.10.0 picking myself through the upgrade guides. I did have to do this one change which I am not sure was intentional? I would think the `asset` helper automatically prefixes, instead of us having to say `assets` in the path?

```diff
-css_link(asset("images/favicon.png"), rel: "icon")
+css_link(asset("assets/images/favicon.png"), rel: "icon")
```

That sample manifest checked into the lucky repo `https://github.com/luckyframework/lucky/blob/4e1458e03c0ced80bcd242584995f1cb22f1cb78/public/mix-manifest.json` differs from the one that is generated in my app, note the `/assets` prefix.

```json
{
    "/js/app.js": "/js/app.js?id=fb223c657c5706b67eeb",
    "/css/app.css": "/css/app.css?id=08943aa77abf683da380",
    "/assets/images/favicon.png": "/assets/images/favicon.png?id=116621f309c088555e78",
    "/assets/logos/facebook.svg": "/assets/logos/facebook.svg?id=74f5a5024c3cbdf242c4",
    "/assets/logos/github.svg": "/assets/logos/github.svg?id=ea8bb7f4b65e7f8b2438",
    "/assets/logos/twitter.svg": "/assets/logos/twitter.svg?id=93a9fd6aa377d5fe5cb2",
    "/assets/logos/xing.svg": "/assets/logos/xing.svg?id=0fcaf9d336abf143ba7a"
}
```

I think I am on the exact same `laravel-mix` version.
<detail>
```yaml
laravel-mix@^2.1.11:
  version "2.1.11"
```
</detail>

**Comment by paulcsmith** [comment]
Just to make sure I understand, Laravel mix is working and the asset method is also working, but requires prefixing “asset”? Just trying to gauge the urgency. 

If it doesn’t work I’ll get in this right away. If it works but requires prefixing then I’ll take a look but maybe in the next few days

**Comment by hanneskaeufler** [comment]
Yes laravel mix is working and the asset method is also working, but requires prefixing `assets/`. One more caveat, I have to run `yarn dev` _twice_ to make the assets appear in the manifest. Not sure if related.

This reproduces for me:
```shell
rm -r public/*
yarn dev
cat public/mix-manifest.json
{
    "/js/app.js": "/js/app.js?id=fb223c657c5706b67eeb",
    "/css/app.css": "/css/app.css?id=c5bfd27b043e790aa12e"
}
yarn dev
cat public/mix-manifest.json
{
    "/js/app.js": "/js/app.js?id=fb223c657c5706b67eeb",
    "/css/app.css": "/css/app.css?id=c5bfd27b043e790aa12e",
    "/assets/images/favicon.png": "/assets/images/favicon.png?id=116621f309c088555e78",
    "/assets/logos/facebook.svg": "/assets/logos/facebook.svg?id=74f5a5024c3cbdf242c4",
    "/assets/logos/github.svg": "/assets/logos/github.svg?id=ea8bb7f4b65e7f8b2438",
    "/assets/logos/twitter.svg": "/assets/logos/twitter.svg?id=93a9fd6aa377d5fe5cb2",
    "/assets/logos/xing.svg": "/assets/logos/xing.svg?id=0fcaf9d336abf143ba7a"
}
```

**Comment by paulcsmith** [comment]
Could you make a separate issue for the `yarn dev` twice thing? I think that is unrelated.

I think the fix for the `/assets` is changing this line in your webpack.mix.js

```
# From this
.copyDirectory("static/assets", "public/assets")
# To shi
.copyDirectory("static/assets", "public")
```

Can you let me know if that works/ If it does I'll make a note in the upgrade-diffs and update the templates 👍

**Comment by hanneskaeufler** [comment]
I will add another issue, sure.

The above change will not work on its own, as then the
`.version(["public/assets"])` does not add any assets to the manifest at all. What works in _my_ case is changing that to ` .version(["public/images", "public/logos"])`.

**Comment by paulcsmith** [comment]
I just tried locally and if you make the change I suggested to `copyDirectory` and also change `version` to just `"public/"` it should work. Can you see if that works for you?

I can also confirm that you have to run yarn dev twice for images to get copied.

**Comment by hanneskaeufler** [comment]
Yeah `.version(["public/"])` works as well but adds (probably harmless) `/mix-manifest.json` to the manifest itself :) I will stick with `.version(["public/images", "public/logos"])` for now.

**Comment by paulcsmith** [comment]
Sounds good! I’ll play around with it and make some updates to the generated webpack.mix.js. I’m thinking the best bet is to iterate over folders in `public/assets` so you don’t need to do it manually and so mix-manifest.json isn’t added.
