### ISSUE TITLE
[Lucky 0.10.0] `yarn dev` must run twice to add assets to manifest

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky#474]
Btw, do you want to add a label to distinguish lucky versions?

`yarn dev` (also `prod`) only picks up on assets on the second run.

Reproduce:
```shell
rm -r public/*
yarn dev
cat public/mix-manifest.json
{
    "/js/app.js": "/js/app.js?id=fb223c657c5706b67eeb",
    "/css/app.css": "/css/app.css?id=c5bfd27b043e790aa12e"
}
yarn dev
cat public/mix-manifest.json
{
    "/js/app.js": "/js/app.js?id=fb223c657c5706b67eeb",
    "/css/app.css": "/css/app.css?id=c5bfd27b043e790aa12e",
    "/assets/images/favicon.png": "/assets/images/favicon.png?id=116621f309c088555e78",
    "/assets/logos/facebook.svg": "/assets/logos/facebook.svg?id=74f5a5024c3cbdf242c4",
    "/assets/logos/github.svg": "/assets/logos/github.svg?id=ea8bb7f4b65e7f8b2438",
    "/assets/logos/twitter.svg": "/assets/logos/twitter.svg?id=93a9fd6aa377d5fe5cb2",
    "/assets/logos/xing.svg": "/assets/logos/xing.svg?id=0fcaf9d336abf143ba7a"
}
```

My npm task: https://github.com/hanneskaeufler/blog/pull/64/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R19

**Comment by paulcsmith** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/1193 It seems this is an issue in laravel mix. I'll try some ideas out to see if there is a workaround

**Comment by paulcsmith** [comment]
This appears to work: https://github.com/paulcsmith/test-auth/commit/47da8ef12d2430260214090819608141d2f78758

* Remove copying from Laravel Mix
* Only ignore js/css/mix-manifest
* symblink public/assets to static/assets. This way the app can serve the assets and mix can version them without worrying about async copying

What do you think @hanneskaeufler? Any better ideas?
