### ISSUE TITLE
Buffer Deprecation

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#475]
When `init`ing a new Lucky project, then running `bin/setup` this warning is shown:

> (node:48012) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

It's apparently [been fixed by yarn 1.7.0](https://github.com/yarnpkg/yarn/issues/5477#issuecomment-391504801), but I upgraded and I'm still getting the warning on fresh projects.

**Comment by paulcsmith** [comment]
I've never seen this so I'm guessing something is still cached in node/yarn land. Maybe removing and reinstalling node and yarn would do the trick?

**Comment by paulcsmith** [comment]
It looks like it is a yarn issue and they're actively working on it. Hopefully in the next release, it will be fully resolved.

I'll close this here since it doesn't seem to be a Lucky issue
