### ISSUE TITLE
LuckyCli bare web app generation

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#477]
It would be pretty handy if the cli could generate a bare web app that doesn't include migrations, user model stuff, auth, etc... From the looks of the cli, I think if there was an option that just did the `web_app_skeleton` and didn't include the browser_app part, that may be enough. 

Maybe it could be `lucky init --bare new_app`?

**Comment by paulcsmith** [comment]
You can now remove authentication with the wizard: https://github.com/luckyframework/lucky_cli/pull/221

I'm sure we can add additional config in the future to make it even more minimal :)

**Comment by jwoertink** [comment]
Sweet!
