### ISSUE TITLE
Allow customizing the log message

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#480]
https://github.com/luckyframework/lucky/issues/440#issuecomment-392229762

Something like this:

```
Lucky::LogHandler.configure do
  settings.formatter = ->(context: HTTP::Context) do
    io << context.method # etc.
  end
end
```

Here is where logs are currently printed: https://github.com/luckyframework/lucky/blob/500e4bc28786722700672c398b768b3937b204cd/src/lucky/log_handler.cr#L30

Here's where a configuration option can be added to override the way logs are printed: https://github.com/luckyframework/lucky/blob/500e4bc28786722700672c398b768b3937b204cd/src/lucky/log_handler.cr#L7

**Comment by jwoertink** [comment]
Since the actual logging takes `context, time, elapsed`, then maybe this config would too? I'm thinking the custom setting would just default to what it does now, then that method becomes `@io.puts settings.formatter.call(context, time, elapsed)`. 

If you're cool with that, then I can tackle this.

**Comment by paulcsmith** [comment]
It's hard to say without seeing it, but I *think* that should work!
