### ISSUE TITLE
Allow passing LuckyRecord::AllowedInTags values to link and input options

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#483]
```crystal
# Must use String now
text_input f.name, autofocus: "true"

# I'd like to use a boolean
text_input f.name, autofocus: true
```

**Comment by jwoertink** [comment]
Do you still want this feature now that the `attrs: [:autofocus]` is a thing? And if so, would `autofocus: true` generate `autofocus="autofocus">` or `autofocus>` ?

**Comment by paulcsmith** [comment]
@jwoertink I think `autofocus: true` should generate `autofocus: true` and not do any special conversion. Ideally people use `attrs` for this now.

I think it would still be good to allow `Lucky::AllowedInTags` though because you may want something to use an integer (or some other object that you create that you want to allow in tags):

```
textarea f.content, rows: 10 # Right now you would have to do `rows: "10"`
```
