### ISSUE TITLE
Discuss: Add optional template rendering to pages

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#49]
```crystal
class Users::IndexPage < MainLayout
  needs users : UserQuery

  render_template # Assumes ./index_template.ecr/.slang - Use kilt to support just about anything
  
  # or specify template
  render_template "./some_other_extension.rss.ecr
end
```

The default would still be to use the HTML tag methods, but sometimes it's much nicer to use templating languages like ECR when doing content heavy pages like landing pages, pricing pages, etc. They're usually quite simple and have large paragraphs of text, which work better in template languages

**Comment by paulcsmith** [comment]
Or maybe at compile time it checks for the template and renders that if it's in the default location. Only use `render_template` only when rendering something other than the default

**Comment by paulcsmith** [comment]
Relevant conversation on Gitter:

https://gitter.im/luckyframework/Lobby?at=5a106f57cc1d527f6b880c2c

> @tarvit I will try to explain why support of template engines is important for me.
Actually there are benefits in generating by crystal code and I see them: close integration with app code, ability to call any code directly without passing parameters, control validity by compiler.
But there are disadvantages in this approach. Actually html page belongs to a another layer from architectural standpoint - view layer. and having it integrated in app and coupled with it closes possibility to make srict borders between the layers.
so why templates a better: they physically are not code. they have no access to all app code so we have a strict border between layers and interface of communication berween view and action class is defined and is transparent. templates have single responsibility and can not perform any other action than generate response based on params passed to them
another disadvantage I noticed is hard integration of simple html snippets into app because you need to recode them. slim and coffee script have converters so it is easier to adapt plain js and html to your app
‎also if your markup is complex you need to generate tons of code to simply add some angular or bootstrap classes. and simple code related to markup will be mixed with potentially important code of view logic.

> Paul Smith @paulcsmith 12:41
@tarvit I think those are some valid points. Some I agree with and other I'm not as sure about. I can't see anything about the way Lucky handles views that is more/less of a boundary between your app and the view layer. In a template you can also call any code. Nothing stops you from running queries or saving forms in them. It's up to the developer not to do that. So I think that's about the same either way. If anything I'd say there is more explicit interface between your code and the view because you must explicitly declare what a page needs in order to be initialized. So it encourages being clear about what the page/view needs in order to work.
I totally agree that one pain point is translating HTML to code is hard because there isn't something that converts it like there is for Slim or CoffeeScript. I rarely need to do that though, but maybe others do? If so I think we could create a converter to help people at. That would be a good idea.
Could you give an example of what you mean by
also if your markup is complex you need to generate tons of code to simply add some angular or bootstrap classes. and simple code related to markup will be mixed with potentially important code of view logic.
It seems writing bootstrap or angular would be just as easy as HTML. I can do div class: "nav" or div "v-on:click": "counter += 1" for a vue.js component. I don't think this is much harder than doing it with HTML. If anything I think it is less code. But maybe I'm misunderstanding what you mean?
If it's about the generated code, then it actually isn't more or less. When you use .ecr or slang or any of the other templating languages it translated them to code as well. So Lucky and those templating languages work similarly in that regard. They're both pretty fast, and they both generate Crystal code under the hood

> Paul Smith @paulcsmith 12:47
I think the advantages of doing it with Crystal methods and classes is large. You can use regular methods to extract code. You can use classes for more complicated HTML if you want. It also makes it so you can define abstract methods on the class. For example you could force the page to implement a page_title method so that you never forget a title for a page. That is something that is hard/impossible to do with templating languages. Or at least, more awkward. So I think the advantages outweigh the disadvantages. But I agree there definitely are some! It may depend on how often you translate existing HTML to Lucky. I personally rarely do that so it hasn't been an issue.

**Comment by testbird** [comment]
+1 for optional template/layout abstraction and choice (https://github.com/jeromegn/kilt)

**Comment by paulcsmith** [comment]
Yeah I think we should go ahead and do this.  I don't think it will be a lot of work and it is a nice option to have

**Comment by testbird** [comment]
Perfect. For the record, another nice thing of the HTML DSL is that it does not require a separate set up files. Templates are very handy for importing pre-existing content or external (non-dev, html-file-editor) editing.

Someday though, the DSL together with crystal-to-javascript conversion could be very good for an absolute top notch in-browser/frontend content management. I mean the new generation of CMS, like https://www.neos.io/features/editing-content.html

**Comment by testbird** [comment]
BTW: With templates, `route` could not only default the path according to the name of the class, but also render a template from the folder structure.
For example selecting from to the files, according to enabled template language, class (inheritance), display mode, format, and special mode:
https://web.archive.org/web/20160424053516/http://zenadmin.org/en/documentation/Wiki/list334.html

**Comment by jwoertink** [comment]
This PR https://github.com/luckyframework/website/pull/129 documents how to use templates. Plus we can always expand on the guides. Maybe this can be closed?

**Comment by paulcsmith** [comment]
Let’s leave it open for now. I’m thinking we should have an official lucky_template shard that adds a macro and documents things a bit. It’d be a tiny package but I think having that would be nice

What do you think?

**Comment by jwoertink** [comment]
Oh yeah, that makes sense. I like it.

**Comment by paulcsmith** [comment]
Handled in the guides :D https://github.com/luckyframework/website/pull/129
