### ISSUE TITLE
Lucky Params doesn't handle nested query params

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#491]
```crystal
request = build_request body: "", content_type: "" #helper taken from specs
request.query = "filter:name=taco&page=1&per=50"
params = Lucky::Params.new(request)
params.nested?("filter") #=> {}
```

This works fine for [json](https://github.com/luckyframework/lucky/blob/master/src/lucky/params.cr#L146), [form, or multipart](https://github.com/luckyframework/lucky/blob/master/src/lucky/params.cr#L158), but missing for the query.

**Comment by paulcsmith** [comment]
Good point. I think this makes sense to add so that it works uniformly across all param types!
