### ISSUE TITLE
Consider moving from yarn -> npm

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#493]
https://mixmax.com/blog/to-yarn-and-back-again-npm

Need to do more research. I haven't had any issues with yarn so this may just be a problem with absolutely massive applications (they said yarn still takes 2 minutes to install all their packages)

**Comment by jwoertink** [comment]
Interesting. I just ran in to an issue last week on a react native project where I was using yarn and kept running in to this issue where the app wouldn't boot. I used npm and things were fine. I haven't had any other issues outside that one project. Maybe it could just be configurable in a `.lucky/config` or something?

**Comment by hfjallemark** [comment]
Interesting, we experienced the opposite on (npm hanging/slow restores) our last project and switched from npm to yarn. But that could have been npm 5, maybe the resolved those issues in npm 6 (which the article mentions).

**Comment by CodelessFuture** [comment]
We use npm at work and many times we have to cancel node_modules to make it work again.

**Comment by rishavs** [comment]
Allowing people to choose between npm & yarn at lucky init (via flags) is probably the best way to do this for now.
yarn is rather problematic on windows and i too switched back to npm.

**Comment by westonganger** [comment]
I fully support switching to npm. Yarn was slick for a brief time, but npm stepped their game up big time shortly afterwards. Ever since then yarn has caused me way too many moments of grief and annoyance, whereas npm has been smooth sailing for quite some time now.

**Comment by paulcsmith** [comment]
For now we’ll keep it as yarn, but once more important issues are covered I think it would be great to support either one!
