### ISSUE TITLE
Add spec helpers

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#50]
### For request specs

Something I've actually used (also includes FactoryBot like factories):
https://gist.github.com/paulcsmith/c5da6e8888d1a50f13fb6d9acc37a6a9

Some experimental ideas:
https://gist.github.com/paulcsmith/d44ac002bd1b7c57dcb8f7217ac499a7

### Pages don't need much to get started

```crystal
html = MyCoolPage.new(whatever_args).render

html.to_s.should contain("some text")
```

**Comment by 5minpause** [comment]
This gist cannot be found => 404

**Comment by paulcsmith** [comment]
Ah you're right. Good catch!

**Comment by paulcsmith** [comment]
https://github.com/luckyframework/lucky_cli/pull/187
