### ISSUE TITLE
Comparison between Lucky and Amber

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#508]
https://gitter.im/luckyframework/Lobby?at=5b228b55fd5b835b2d5ba223

I think it would be helpful to work together with the Amber team to generate a comparison doc that we both feel is fair. That way people will have an easier time deciding what framework they'd like to work with.

Something similar to https://vuejs.org/v2/guide/comparison.html

Specifically:

* What do they both do
* What does one do that the other doesn't
* How do they do the same thing differently, and what are the pros/and cons

**Comment by fernandes** [comment]
more discussion on crystal-loot/web-framework-comparison#1

**Comment by karmakaze** [comment]
The discussion on crystal-loot/web-framework-comparison#1 is very detailed.
It would be good to come up with a high-level summary from that.

In addition to points listed by @paulcsmith I would like to add:

* edit/recompile mechanism and speed for seeing changes
* different use cases, or developer backgrounds which may better suit one or the other

**Comment by paulcsmith** [comment]
Great ideas @karmakaze!

I'll close this and post new discussion to 
https://github.com/crystal-loot/web-framework-comparison/issues/1
