### ISSUE TITLE
Problem installing Lucky on Mac OS X

### ISSUE THREAD

**Issue by CodelessFuture** [luckyframework/lucky#509]
**crystal -v**                                                                                                                                                                                       
Crystal 0.25.0 (2018-06-15)

**LLVM: 5.0.1**
Default target: x86_64-apple-macosx

**brew install lucky**                                                                                                                                                                                 
==> Installing lucky from luckyframework/lucky
==> Downloading https://github.com/luckyframework/homebrew-lucky/raw/master/tarballs/lucky-0.10.0.tar.gz
Already downloaded: /Users/max/Library/Caches/Homebrew/lucky-0.10.0.tar.gz
==> mkdir lib
==> mv teeplate lib/
==> mv lucky_cli lib/
==> crystal build lib/lucky_cli/src/lucky.cr
Last 15 lines from /Users/max/Library/Logs/Homebrew/lucky/04.lucky.cr:

s = String.build do |sb|
           ^~~~~

in lib/teeplate/src/lib/file_tree/macros/directory.cr:57: instantiating 'pack_ecr(Int32, String::Builder, String, String)'

      pack_ecr i, sb, abs, $1
      ^~~~~~~~

in lib/teeplate/src/lib/file_tree/macros/directory.cr:33: undefined method 'stat' for File:Class

  ____files << ::Teeplate::StringData.new("#{rel}", io.to_s, #{File.stat(abs).perm})
                                                                    ^~~~

**Comment by paulcsmith** [comment]
Hey @CodelessFuture! Crystal 0.25 just come out I'm working on updating Lucky to work with it today. I'll be sure to update here when it is ready to go

**Comment by CodelessFuture** [comment]
Thanks!

After I install it I write an article on Medium

**Comment by paulcsmith** [comment]
@CodelessFuture Awesome! Be sure to ping me if you want any feedback.

The new version is out and guides have been updated. Good luck!
