### ISSUE TITLE
Add post_compile hook for 'lucky watch'

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#513]

**Comment by jwoertink** [comment]
Would this be like a method that gets called after the compile happens and used for is someone wrote a custom watch task that inherited from the current watch file? Or were you thinking this had a very specific function?

**Comment by paulcsmith** [comment]
I'm not exactly sure how it would work, but I'm imagining that it would run scripts inside `bin/post_compile/`. That way you can add as many scripts as you want and shards can extend it by installing a compiled binary in the folder. For example, you might run a linter, check that config looks right, or post a a "Successfully built" notification to the OS.

This new functionality would probably be trigger from within the lucky watch task along with `bin/pre_compile` and `bin/compile_failure`. That do basically the same thing but for different events.

The idea would be that you can build and symlink your own scripts to `bin/(pre|post)-compile` or you can add shards that use `postinstall` (example: https://github.com/luckyframework/lucky/blob/15a71085a5d1b2bdc7b1ee1df27640b3dbbc3db3/shard.yml#L61-L73) that add them to the `bin/(pre|post)-compile` folder for you. So you could add a "lucky_success_notifications" shard and it might add some scripts for showing notifications

Does that make sense? Do you have any other ideas for this?

**Comment by jwoertink** [comment]
Ah nice! I like that. This could be good for CI type stuff too. Running ameba or autodeploy type deals.

**Comment by paulcsmith** [comment]
I think that is a good idea to have that, but it wouldn't work in this case since this would only be when watching, and in test it doesn't run the watch command. So maybe to clarify things it would be better to put scripts in `bin/watch/post_compile` so it's clear it is for the watch command.

Maybe a different script folder could be added for post-compile scripts that always happen, but I'm not sure how to integrate that. It might have to be in Crystal itself. I'm not sure 🤔

**Comment by jwoertink** [comment]
Oh, right. I guess that makes sense. So you're running your local dev, and saved a file, it builds everything, re-compiled assets, and then ran this set of post_compile stuff...

**Comment by paulcsmith** [comment]
Yep exactly. So you could have it notify you on failed builds, successful builds, notify of linting errors. Stuff like that :)

**Comment by paulcsmith** [comment]
And actually it might be better to have just one folder and you pass the event type as the first arg. So a folder like `bin/lucky_watch_hooks/` and a script like `notifications`. When compilation fails it would get "compile-failure" as the first argument. Or "compile-success" if it was successful. The script can also ignore events it doesn't care about that way

**Comment by jwoertink** [comment]
I like that way better. That makes sense. Then each file can have one function that does whatever it needs based on the type of event instead of several different scripts basically doing the same thing. So it would be like "here's an event, run all scripts in this folder and pass this event into each of them". Maybe running them in alphabetical order?

**Comment by paulcsmith** [comment]
Yeah exactly! I think alphabetical makes the most sense. I think each script should be independent so it shouldn't (fingers crossed) matter which ones run first

**Comment by paulcsmith** [comment]
I'm rethinking this because it is too complex. Will close this and re-open something else later with more details
