### ISSUE TITLE
Allow passing valueless attributes to HTML methods

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#518]
```crystal
video attrs: [:allow_fullscreen], class: "my-video"
text_input f.name, attrs: [:required, :autofocus], class: "input"
```

**Comment by jwoertink** [comment]
I was going to tackle this, but after [reading the spec](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes), I'm curious on your thoughts here. 

```html
<input required>
is the same as
<input required="required">
or
<input required="">
```

The spec actually says
> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether. 

So really, rendering `<input required>` is just syntactic sugar and no different than just rendering `<input required="">` which you can do now with `text_input f.name, required: ""` 

Instead of doing this, what if just fixing https://github.com/luckyframework/lucky/issues/483 to catch when it's value is `true`, it renders like `required="required"`, and `false` just doesn't render that attribute?

**Comment by paulcsmith** [comment]
@jwoertink I had the same thought, but I think it could cause issues. It's tough to know whether the string is "false" because the user meant to remove the field or if "false" is just a string that someone happened to type in a field. Imagine this code:

```
show_fields = false
div id: "fields", show_fields: false
```

Then some JS:

```
document.getElementById("fields").getAttribute("show-fields") // Oops! That attribute does not exist
```

Since it may be unexpected behavior, I think adding in the `attrs` option makes the most sense. It's clear and won't have unexpected surprises. I imagine it should also work for text fields so you can do `text_input f.name, attrs: [:autofocus], class: "my-field"`

What do you think? Does that make sense?

**Comment by jwoertink** [comment]
Ah. Yeah, I guess that would make sense. Though, in that case, I think `show_fields: false` should not include the attribute, but `show_fields: "false"` should include it with a value of "false". I wonder how rails handles doing that? 

Ok, so in this, would it be ok for `attrs: [:autofocus]` to just render `autofocus=""` or `autofocus="autofocus"` vs just doing the ` autofocus>`?

**Comment by paulcsmith** [comment]
I believe that in Rails it will always print "false" but I am not sure...that would be interesting to check.

I think leaving off the `=` and having the bare word `autofocus` would work best since it takes a bit less space and should work the same.

**Comment by jwoertink** [comment]
Ok, just checked in a rails app:

```ruby
text_field_tag(:search, "", name: "q", id: "q", required: false) #=> <input .... />

= text_field_tag(:search, "", name: "q", id: "q", required: true) #=> <input .... required="required" />

text_field_tag(:search, "", name: "q", id: "q", required: "false") #=> <input .... required="required" />
```

The last one actually kind of surprised me.
