### ISSUE TITLE
More concise JSON serialization

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#526]
Just an experiment for now. Not sure how `merge` would work, but I think it is a nicer API.

```crystal
class Users::Serializer < Lucky::Serializer
  needs user : User

  # Make this a class method instead of a new object
  def self.collection(users)
    { users: users.map { |user| Serializer.new(user) } }
  end

  # render single instance
  def render
    json.merge @user.to_h(:name, :email, :age)
    json.add "custom", "my-custom-value"
  end
end

# In an action
json Users::Serializer.new(user)
json Users::Serializer.collection(UserQuery.new)
```

Requires adding a `to_h` method to models. It would likely have to be a macro to maintain type-safety. I don't love it, but the API will be a lot nicer this way I think

## Alternative

```crystal
class Users::Serializer 
  class One < BaseSerializer
    needs user : User

    def render
      {
        name: @user.name
      }
    end
  end
  
  class Many < BaseSerializer
    needs users : UserQuery

    def render
      {users: @users.map { |user| One.new(user) }}
    end
  end
end

json Serializer::One.new(user)
json Serializer::Many.new(user)
```

**Comment by jwoertink** [comment]
Just thinking about this. I actually love the API we already have setup. It's setup easy to understand and use. Since we have the `for_collection` method, that already handles doing the collection. 

Now, what I think might be cool is adding `needs` which is shorter and more consistent with other APIs, then we don't need to define an initializer (which I misspell ALL the time). Next, adding a quick macro to call `render` with some columns from the model.

```crystal
class UserSerializer < BaseSerializer
  needs user : User

  # or whatever it would be called
  serialize name, age, username, email
end
```

That would essentially do this:

```crystal
class UserSerializer < BaseSerializer
  def initialize(@user : User)
  end

  def render
    {name: @user.name, age: @user.age, username: @user.username, email: @user.email}
  end
end
```

and of course, the escape hatch here would be that you can just define `render` on your own. (maybe `render` should also be abstract since it's actually required 🤔 )

What are your thoughts on this?

**Comment by paulcsmith** [comment]
@jwoertink I like the idea of adding needs. I much prefer it over initialize in most cases TBH 😆especially since you can inherit needs.

I'm not as big a fan of a serialize macro because:

* It is hard to figure out how to modify the serializer with custom values
* macros in general have weird error message 😂

I think we can maybe solve this with regular methods, or potentially with a macro and really good error handling messages.

What if we had something like this where it kind of crosses between your suggestion and the original method based approach?

```crystal
class Users::Serializer < BaseSerializer
  needs include_details : Bool = false
  needs user : User

  def render
     set({name: user.name}) # This is basically what you have today
     set(:single_key, 123)
     # Works great for conditionals
     if include_details?
        set(all_the_deets: true)
     end
     
     # macro 
     set_attrs :email, :age, :other_thing, from: user
     # expands to
     set({email: user.email, age: user.age, other_thing: user.other_thing})
  end
end
```

Thoughts? I like this because the simple case is still there, you can see how to use conditionals pretty easily, and how to customize stuff. And it adds the `set_attrs` macro to serialize multiple methods from an object.

And since it is all still in a regular method changing the key name for a particular method is easy:

```crystal
set_attrs :email, :age, from: user
set :name, "#{user.first_name} #{user.last_name}"
```
