### ISSUE TITLE
bin/setup always fails at the migrate step

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#529]
bin/setup is able to create the database and populate it, but it fails at the migrate step because it's not set up the database user name and password in config/database.cr, and although it's already prompted for the password (or psql did) it didn't pass it to the app.

Also, when it prompts for the password, there is nothing that tells you what it's looking for except "Password: ". But it's looking for the password for my personal Postgres user name.

The best solution might be to create a localhost user per app, and generate a password for that user.

**Comment by paulcsmith** [comment]
Added some helper text to bin/setup to help guide users to setting username/password. I'm considering adding a Docker setup by default. I'll keep in mind some ways to improve though because I think it can still be better!
