### ISSUE TITLE
Required public/mix-manifest.json for API only application

### ISSUE THREAD

**Issue by sdzyba** [luckyframework/lucky#533]
I tried to remove `public` directory with `mix-manifest.json` in it since I plan to have an API only application and now I'm getting the error:
```
in lib/lucky/src/lucky/asset_helpers.cr:4: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
   1. Manifest at /.../api/public/mix-manifest.json does not exist
   2. Make sure you have compiled your assets
--------------------------------------------------------------------------------
Syntax error in expanded macro: macro_4564338096:1: unknown token: '\e'

Manifest at /.../api/public/mix-manifest.json does not exist
^

================================================================================

  {{ run "../run_macros/generate_asset_helpers" }}
  ^
```

I suppose this shouldn't be a required file for API app.

**Comment by perezperret** [comment]
This was an issue when deploying to Heroku, what I did was just remove the manifest from the `.gitignore` and everything is running smoothly. If you care to give me a couple of pointers on how to go about it, I would love to try and make a pull request to fix this.

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky/pull/651
