### ISSUE TITLE
[Feature Request] Being able to define multiple routes on the same action

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#542]
I know I have weird requirements, but this has come up twice now for us. Both times we've found a way around it, but I would imagine at some point that may not be possible.

Imagine you have some routes like this:

```
/affiliates/jeremy
/affiliates/paul
/affiliates/russ

/affiliates/:id
```

The first three are static routes that all go to the same exact action which isn't a `Affiliates::Show` type action. The last one would be your standard `Affiliates::Show` action. 

In our case, we would send the first 3 to the `Affiliates::Show`, and then filter out the value of the params and do different things based on what it looks like. Instead, we'd rather do something like this:

```crystal
class Affiliates::Redirect < BrowserAction
  {% for affiliate in ["jeremy", "paul", "russ"] %}
    get "/affiliates/{{ affiliate.id }}" do
      # do special redirect linking for these affiliates
      # returns 301
    end
  {% end %}
end

class Affiliates::Show < BrowserAction
  get "/affiliates/:id" do
    # render affiliate page
    # returns 200
  end
end
```

Now, I get this would not only be difficult to add in, but would also cause some other issues like where would `Affiliates::Redirect.path` go? That one might be simple to solve with something like `Affiliates::Redirect.path(pattern: "/affiliates/jeremy")` or something along those lines.

Another solution might be something like this:

```crystal
get ["/affiliates/jeremy", "/affiliates/paul", "/affiliates/russ"] do |path|
  # path knows which one was called to get in here
end
```

The current work around would be something like this
```crystal
class Affiliates::Redirects::Jeremy < Affiliates::Redirects::Base
  get "/affiliates/jeremy" do
  end
end
```
However, in our case, we have an affiliate with a name beginning with a number, and we have 130+ of these (a lot of classes).

**Comment by paulcsmith** [comment]
Hey @jwoertink Could you give an example of what the redirect would look like? 

I'm not totally sure I understand the use-case but maybe you could flip this around:

```crystal
get "/affiliates/:id" do
  case id
  when "paul"
  do_something_for_paul
  when "jeremy"
  do_something_for_jeremy
  else
     do_stuff_with_the_id
  end
end
```

Would that work? If not can you explain why? I think it would be cool to allow multiple paths for the same action, but I'd like to fully understand the use-cases before adding it

**Comment by jwoertink** [comment]
That code example could technically work, though in our case, there would be 130+ `when` clauses. We ended up rolling with something like 

```crystal
if SPECIAL_CASES.includes?(id)
  do_redirect_for_id(id, status: 301)
else
  render(page)
end
```

Since there's technically work arounds, I don't really see this as a major issue, but it would be cool to have a way to handle this. A sort of "alias route" type deal. Let me know if that needs more clarification, or if you think it's dumb, I won't be offended if you close this 😛

**Comment by paulcsmith** [comment]
That makes sense. I think I understand now and I think that your SPECIAL_CASES idea seems to cover things in a pretty nice way. I can see why the case thing would be a PITA. 

How do you feel about SPECIAL_CASES now that you've implemented it. Would adding "aliases" make the code much cleaner or easier to use? It seems that the SPECIAL_CASES is easier/shorter than using an alias in this case, but I may be wrong

**Comment by jwoertink** [comment]
It's not horrible. Definitely something we can live with in our use case. I think the only way it would have been cleaner would be something like this:

```crystal
# what we have now
class AffiliateRedirects::Index < BrowserAction
  SPECIAL_CASES = ["jeremy", "paul"]
  get "/:path" do
    if SPECIAL_CASES.includes?(path)
      do_this
    else
      do_that
     end
  end
end

# VS

class AffiliateRedirects::Index < BrowserAction
  get ["/jeremy", "/paul"] do
    # no need to `do_that` because only the special cases his this action
    do_this
  end
end
```

**Comment by jwoertink** [comment]
We won't support multiple paths in the same Action, and you can set multiple formats now https://luckyframework.org/guides/http-and-routing/request-and-response#setting-accepted-request-formats
