### ISSUE TITLE
Spec apparently doesn't care where the helper is?

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#548]
Some of these file in this directory require the spec_helper like this

https://github.com/luckyframework/lucky/blob/master/spec/lucky/root_spec.cr#L1

And some of them require it like this

https://github.com/luckyframework/lucky/blob/master/spec/lucky/select_helpers_spec.cr#L1

I have no clue how this is even working....

/cc. @edwardloveall

**Comment by jwoertink** [comment]
Related: https://github.com/crystal-lang/crystal/issues/7408

**Comment by paulcsmith** [comment]
Nice find. Thanks for linking. Since it is a Crystal issue I'll go ahead and close this for now. Feel free to reopen though if you later found out it really is something in Lucky!
