### ISSUE TITLE
Add 'match' macro to actions

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#551]
> Would it make sense to include a match method that takes any HTTP verb as a symbol? I’m likely to want to match PROPFIND, PROPPATCH, REPORT, etc. too.
> https://gitter.im/luckyframework/Lobby?at=5b575246f477e4664abc5274

It would look like this:

```crystal
class MySpecialAction < Api/BrowserAction
  match :report, "my-path" do
  end
end
```

Ideally, it should raise at compile-time if given an uppercase symbol. This will help maintain consistency.

The code should go in the `Routeable` module: https://github.com/luckyframework/lucky/blob/master/src/lucky/routeable.cr. This bit of code will be helpful: https://github.com/luckyframework/lucky/blob/master/src/lucky/routeable.cr#L21-L29

And here are the specs: https://github.com/luckyframework/lucky/blob/master/spec/lucky/action_spec.cr#L134-L175

**Comment by joeldrapper** [comment]
I’m happy to take this.
