### ISSUE TITLE
Heroku Push Rejected : Two different lockfiles found 

### ISSUE THREAD

**Issue by ianpurton** [luckyframework/lucky#561]
Just built a new app and tried to get it deployed to Heroku. Lucky v0.11.0

> Counting objects: 224, done.
> Delta compression using up to 8 threads.
> Compressing objects: 100% (195/195), done.
> Writing objects: 100% (224/224), 965.21 KiB | 43.87 MiB/s, done.
> Total 224 (delta 26), reused 183 (delta 6)
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> Node.js app detected
> remote: 
> remote: -----> Build failed
> remote:  !     Two different lockfiles found: package-lock.json and yarn.lock
> remote: 
> remote:        Both npm and yarn have created lockfiles for this application,
> remote:        but only one can be used to install dependencies. Installing
> remote:        dependencies using the wrong package manager can result in missing
> remote:        packages or subtle bugs in production.
> remote: 
> remote:        - To use npm to install your application's dependencies please delete
> remote:          the yarn.lock file.
> remote: 
> remote:          $ git rm yarn.lock
> remote: 
> remote:        - To use yarn to install your application's dependences please delete
> remote:          the package-lock.json file.
> remote: 
> remote:          $ git rm package-lock.json
> remote:     
> remote:        https://kb.heroku.com/why-is-my-node-js-build-failing-because-of-conflicting-lock-files
> remote: 
> remote:  !     Push rejected, failed to compile Node.js app.
> remote: 
> remote:  !     Push failed
> remote: Verifying deploy...
> remote: 
> remote: !       Push rejected to REDACTED
> remote: 

Can I use  .slugignore to ignore one of the lock files or do we need both for deployments?

**Comment by paulcsmith** [comment]
When you run the new app?

**Comment by paulcsmith** [comment]
Also did you perhaps run npm install on accident at any point?

**Comment by paulcsmith** [comment]
It looks like this was resolved (https://gitter.im/luckyframework/Lobby?at=5b694742945df30dc163eb0c) so I'll go ahead and close this 👍
