### ISSUE TITLE
Upcoming breaking change in crystal 0.26.0

### ISSUE THREAD

**Issue by bcardiff** [luckyframework/lucky#563]
Hi, FYI The shell-table shard version will need to be updated to support 0.26.0 https://github.com/jwaldrip/shell-table.cr/issues/2

**Comment by paulcsmith** [comment]
Thanks for the heads up!

**Comment by paulcsmith** [comment]
We'll use a forked version for now 
https://github.com/luckyframework/shell-table.cr
