### ISSUE TITLE
Server port not changing despite change in config/watch.yml

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#570]
When I try to change my `config/watch.yml` to a different port, BrowserSync still proxy's to port 5000. It also ignores when I set a port for the environment like so:

```sh
PORT=4567 lucky dev
# or
export PORT=4567
lucky dev
```

```sh
yarn run v1.9.4
$ path/to/app/node_modules/.bin/browser-sync start -c bs-config.js --port 3001 -p http://0.0.0.0:5000
web    | [Browsersync] Proxying: http://0.0.0.0:5000
```

**Comment by jwoertink** [comment]
Just adding on to this:
<img width="499" alt="Screen Shot 2019-09-05 at 8 54 01 AM" src="https://user-images.githubusercontent.com/2391/64358210-e71fd300-cfba-11e9-9b5d-80d8cf1b105d.png">

My `.env` has `PORT=5000`, but my `config/watch.yml` has `port: 9090`. 

Also related: https://github.com/luckyframework/lucky_cli/issues/324. TL;DR: the process runners will inject their own PORT env var which overrides this.

**Comment by richarddewit** [comment]
Somehow the `Lucky::ServerSettings` either aren't updated by the `config/watch.yml`, aren't read from `config/watch.yml`, or are overwritten later. When I `puts settings.port` after the server settings are set, it still outputs `5000` despite the setting in `config/watch.yml`:

**`config/watch.yml`**
```
host: 0.0.0.0
port: 4000
```

**`config/server.cr` line 12+**
```
    # Change host/port in config/watch.yml
    # Alternatively, you can set the PORT env to set the port
    settings.host = Lucky::ServerSettings.host
    settings.port = Lucky::ServerSettings.port
    puts settings.port
```

**Output (just the `puts`)**
```
web    | 5000
```

---

Btw @jwoertink, just noticed a typo in the screenshot you posted (Begin**n**ning) and looking back in my terminal it's there too :sweat_smile:
