### ISSUE TITLE
Find way to clearly highlight the server/port to go to

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#571]
I really like how this makes it super obvious

<img width="1060" alt="screen shot 2018-08-14 at 9 06 16 am" src="https://user-images.githubusercontent.com/22394/44093376-63b4337a-9fa1-11e8-8677-b23a3f2f1332.png">

**Comment by jwoertink** [comment]
You can use the colorize to do this.

```crystal
require "colorize"
text = <<-TEXT
                            
[OK] Server Listening on tcp
                            
TEXT
puts text.colorize.back(:light_green).fore(:black)
```

<img width="398" alt="screen shot 2018-08-15 at 8 39 43 am" src="https://user-images.githubusercontent.com/2391/44157225-ce1e4a00-a066-11e8-808b-6d1b858d1753.png">

**Comment by paulcsmith** [comment]
The tricky part is that the output is generated by BrowserSync right now. It's not super hidden, but it's not super obvious either...

Maybe I can just print the "Listening on ...." after BrowserSync start. It'll be duplicate, but it'd stand out a lot more. What do you think?

**Comment by jwoertink** [comment]
Oh, you're saying because it's ran in a spawn though Process, so node is actually the one printing the message? Maybe you could `> /dev/null` or whatever that syntax is to silence that output, then send out your fancy output?

**Comment by paulcsmith** [comment]
Yeah pretty much. Browserync is proxying requests so that's the URL that people need to access, but it is printed by Browsersync, not Lucky. I could do what you're saying and hide the output, but it also has output when it detects a changed file and triggers a reload. I think that would be helpful to keep.

Maybe I could create an intermediate IO object that hides blacklisted lines or something. That seems a bit complex though, and fairly error-prone

**Comment by jwoertink** [comment]
Looks like you added this in [this commit](https://github.com/luckyframework/lucky/commit/cc8f45b7d0129422dceba243772678ffcbb0ab19)?

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky/commit/cc8f45b7d0129422dceba243772678ffcbb0ab19

**Comment by paulcsmith** [comment]
Thanks for pointing that out!
