### ISSUE TITLE
Clueless newbies (that means me) who build lucky rather than lucky_cli get no warning

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#577]
If a clueless person (that is me a lot of the time) builds lucky instead of lucky_cli, and attempts to run the resulting executable, it just exits quietly. It should say "Did you mean to build lucky_cli?".

**Comment by paulcsmith** [comment]
Definitely agree. In fact, I think making a `bin/build` that would be good so it is harder to typo and "just works"

**Comment by jwoertink** [comment]
Fixed by https://github.com/luckyframework/lucky/pull/1586
