### ISSUE TITLE
Test against nightly Crystal

### ISSUE THREAD

**Issue by fernandes** [luckyframework/lucky#591]
Shouldn't lucky be tested against crystal night, like [LuckyRecord](https://github.com/luckyframework/lucky_record/blob/a74caf9217d0bb9d5b6940c171a2751fcf97899d/.travis.yml#L4-L11) is?

The main idea is to try to catch some bugs before a Crystal release.

I can open a PR (I think it's a simple `.travis.yml` modification)

See you

**Comment by paulcsmith** [comment]
Yes that would be wonderful! Thank you :)
