### ISSUE TITLE
Add a task for releasing

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#594]
https://gitter.im/luckyframework/Lobby?at=5b880e01cff55e561781f175

We get this question a lot: "how do I make a release build for my app". It would be good to have a task that abstracts this.

**Comment by paulcsmith** [comment]
Nice idea! I like the `lucky build.release` idea. It would be a super simple wrapper around `crystal --release src/server.cr`

**Comment by edwardloveall** [comment]
Exactly. Good name!

**Comment by paulcsmith** [comment]
Also, so people know what it is doing under the hood (so they learn a bit of Crystal that might be useful in other projects). I think it should say "Building binary with 'crystal --release src/server.cr'"

**Comment by paulcsmith** [comment]
And a good example tasks is here: https://github.com/luckyframework/lucky/blob/master/tasks/routes.cr

**Comment by edwardloveall** [comment]
Hi @ajwann! Please do! Let us know if you need any assistance.

**Comment by edwardloveall** [comment]
Sounds like a good start to me! We may want to change parts of it once you submit it for a PR, but you gotta start somewhere 😄 

Also, you can take a look at the existing watch task if you'd like another example of how we're using `Process.run`

https://github.com/luckyframework/lucky/blob/master/tasks/watch.cr#L84

**Comment by paulcsmith** [comment]
@ajwan thanks for offering to tackle this one! There is a PR up for review though so it may be better to work on something else https://github.com/luckyframework/lucky/pull/602

Sorry I didn’t post here when it opened 😜

**Comment by edwardloveall** [comment]
Sorry about that @ajwann . Thanks for catching that Paul. I must have forgotten about that one.

**Comment by ajwann** [comment]
@paulcsmith @edwardloveall no worries, I'll take another issue
