### ISSUE TITLE
Properly support HEAD requests

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#601]
https://ochronus.com/http-head-request-good-uses/

GET requests should respond to HEAD, but should only return headers and not the response body

**Comment by paulcsmith** [comment]
As noted by @jwoertink https://gitter.im/luckyframework/Lobby?at=5b9836b7f3c26b08f662791b

**Comment by HarrisonB** [comment]
Should HEAD requests to `LuckyRouter` simply point to GET? Obviously `LuckyRouter` doesn't know the workings of the payload that it'd be returning, but I feel like it makes sense.
