### ISSUE TITLE
Discussion: Handling Lucky::Exceptions::InvalidParam

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#628]
When you have an action that requires a param like `page : Int32`, lucky will throw the `Lucky::Exceptions::InvalidParam` error and return a 500. In cases of people trying to "hack" you, this can cause issues in environments like Elasticbeanstalk where too many 500 errors will cause your instance to be auto-scaled down.

```
Required param "page" with value "32B" couldn't be parsed to a "Int32"
```

After some talks about this, it may be better to have the server return a [422](https://httpstatuses.com/422). This is the only example I've come across, but there may be other examples. I think this exception should still be raised so that way it's still reported to error reporting, but have the server return a status not 500 range.

**Comment by robacarp** [comment]
Invalid input is an expected use case of a web application, I don't think any set of input should purposefully cause a 500. 422 is a fine use for that, I think.
