### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by johansmitsnl** [luckyframework/lucky#631]
Asked on the chat if there is internationalisation support (i18n) but @edwardloveall noted that there is none available at the moment.

Suggestion to look at https://github.com/whity/crystal-i18n and the suggestion to add an issue :smile:

**Comment by jwoertink** [comment]
We now have this documented on how to add it in. https://www.luckyframework.org/guides/frontend/internationalization

Granted, it's not baked in, but with this guide, it's pretty easy to setup, and we can always improve the guide as more tools become available and easier to use.

**Comment by btihen** [comment]
I have agreed to bring it into Lucky once Paul gives me guidance on how he would like it architected in order to be a good citizen/module within Lucky.

**Comment by paulcsmith** [comment]
Yes thank you @btihen! I’ve slowly been working on what I think would be a nice API. I’m on vacation but might find a bit of time to work on it for fun in the evenings :)

**Comment by btihen** [comment]
Hi Paul, I look forward to doing internationalization as a general solution.  But no stress - enjoy vacation! Bill
