### ISSUE TITLE
A possible Docker development workflow for a new application

### ISSUE THREAD

**Issue by revgum** [luckyframework/lucky#643]
I put together a gist with some notes and files I've used to setup a development environment for a new Lucky application using docker. 

**A few gotchas that caught me:**
- Shards need to be compiled within the docker image, not on the host machine (I use MacOS)
- overmind depends on tmux which doesn't work well in docker-compose, although I saw some posts online that suggested setting COLUMNS and LINES environment variables to make it work but couldn't make it happen. So this Docker image is built with forego and works nicely.

I'd be happy to get comments on how to improve this, but thought I'd share because I hadn't found anyone else having set this up already. 

https://gist.github.com/revgum/ebdc2ef4316373705b93002af2741bf9

**Comment by paulcsmith** [comment]
Thank you for this! I'm researching this now as part of #671. This is very helpful

**Comment by paulcsmith** [comment]
I'm going to close this in favor of #671 to keep discussions in one place. Thanks for opening this. It was super helpful to have this
