### ISSUE TITLE
Default favicon

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#646]
It's not much, but when booting a brand new lucky app and visiting the home page, browsers will try to auto fetch `/favicon.ico` which throws a 500 error. Rails includes a blank one in its public directory, so maybe can do something similar.

**Comment by robacarp** [comment]
I'm all for a default favicon: 👍 
But also, shouldn't a nonexistent route produce a 404 instead of a 500?

**Comment by jwoertink** [comment]
Actually, that's a good point. It should be a 404. 🤔

**Comment by paulcsmith** [comment]
Good point @robacarp  I believe it is a 404 right now: https://github.com/luckyframework/lucky_cli/blob/24510c84bb05f85c3cd7ba834b0b8be183cfcbe8/src/web_app_skeleton/src/actions/errors/show.cr.ecr#L17-L27

It raises the error, but returns a 404 to the user

**Comment by robacarp** [comment]
cooool. 404s are the right stuff.

For the purposes of discussion / devils advocacy:

>So there are a _ton_ of this kind of request that browsers of various kinds make requests for:
>- favicon (how 2001!)
>- apple touch icons (kind of them to implement their own namespaced standard; some people even make a bunch of different explicit sizes 🤦‍♂️ [this site shows 9 sizes!](https://bradymower.com/create-ios-android-shortcut-icon-for-website/))
>- the generic "icon" (android, giving it a go at another standard, but supporting sizes which are different than , but thankfully not as many are suggested) [(obligatory xkcd reference you were already thinking about)](https://xkcd.com/927/)
>
>Favicon is the most requested, by far, because all my little tabs need pictures the size of a kernel of corn, but the others are requested when "save this website to my home screen" type functionality is used on various platforms.

I don't advocate shipping 12+ icons with the repo, but a favicon sounds like it'll ease developer experience in development. Less noise is better noise.

**Comment by paulcsmith** [comment]
I think one difference between the favicon and the others is that the favicon is requested no matter what, but those other icons (at least the iOS ones) are only requested if you add HTML tags telling iOS to look for them. So I think those should be ok.

But definitely agree on the favicon stuff! I think it'd be a huge help and clean things up a lot in test/dev/prod. Seems like an easy win!
