### ISSUE TITLE
html whitespace control

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky#669]
Whitespace in html is a subtle beast. Related to #668, there have been a few times when I want to add a space between tags, but because lucky html is method driven there is no easy way to do this. In regular html, a space, newline, or any other whitespace character would work. 

This snippet is an example:

```crystal
para do
  text <<-TEXT
  ICMP Echo is a low level network protocol which checks to see a host is responsive
  and measures the time of that response. It is equivalent to the 
  TEXT
  a "ping", href: "https://en.wikipedia.org/wiki/Ping_%28networking_utility%29"
  text " utility."
end
```

The rendering I'm after should look something like this markdown-formatted paragraph:

> ICMP Echo is a low level network protocol which checks to see a host is responsive and measures the time of that response. It is equivalent to the [ping](https://en.wikipedia.org/wiki/Ping_%28networking_utility%29) utility.

Specifically the embedded link in the paragraph, where I want this spacing: `[...] equivalent to the <a ...>ping</a> utility.`

In order to accomplish that, I've had to add a dangling space at the end of the heredoc as well as leading space on the second `text` method (it's there, but you can't see it rendered in this comment). The dangling space is hard to see, even with `:set list`, and a lot of people have their editors configured to trim them automatically...but I can't add a comment to prevent the trim, because it's a heredoc :complainy-complainerson-mc-complainerface:

I've run into similar issues with [other whitespace-trimming syntax dsls](https://github.com/jeromegn/slang/issues/29), and [I know that](http://haml.info/docs/yardoc/file.REFERENCE.html#tilde) many [other rendering engines](https://api.rubyonrails.org/classes/ActionView/Base.html) have dealt with this problem 🍌 

It feels brittle to add spaces like that -- Is there currently some way around this that doesn't make things so brittle? 🌮

**Comment by HarrisonB** [comment]
I immediately thought of [this article](http://chriseppstein.github.io/blog/2010/02/08/haml-sucks-for-content/) after reading. I think it would be pretty straightforward to implement in Lucky (though I suppose you’d lose some type safety).

**Comment by paulcsmith** [comment]
Great point. This has also been brought up in #266 and there are some ideas here. I think in the short term people could go with a heredoc and use an anchor tag with interpolation (as show in one of the suggestions in that issue). 

However, I do wish there was a way to still keep the type-safety with it. Maybe there could be some kind of macro as @HarrisonB mentioned here 
https://gitter.im/luckyframework/Lobby?at=5c300d871948ad07e8edd7e6

Maybe something like this?

```crystal
ecr <<-ECR
Something <%= link "google", to: "https://google.com" %>
ECR
```

I don't even know if that is possible, but it could work. Or if there is a *lot* of content it might be better to use Kilt and have render an ECR template. Definitely open to ideas/experiments.

**Comment by HarrisonB** [comment]
Well I imagine we could have a script like `src/run_scripts/parse_markdown` (and `src/run_scripts/parse_ecr`, etc). It wouldn't necessarily be _type-safe_ per se, but if the template were to raise any errors, you'd know at compile-time. If you wanted to make sure it goes through the same Lucky tag methods, you could maybe do some verification with [html2lucky](https://github.com/luckyframework/html2lucky), but I don't know how you'd recompile the results of _that_.

**Comment by edwardloveall** [comment]
What if we had a `space` method that inserted a space?

```crystal
para do
  text <<-TEXT
    ICMP Echo is a low level network protocol which checks to see a host is responsive
    and measures the time of that response. It is equivalent to the
  TEXT
  space
  link "ping", to: "https://en.wikipedia.org/wiki/Ping_%28networking_utility%29"
  space
  text "utility."
end
```

This might sound silly but I've had spaces in HTML bite me pretty hard in the past especially when working with CSS. They are pretty difficult to detect if you're _aren't_ expecting them. This:
* makes them very explicit and difficult to add accidentally
* keeps the type safety

It comes at the cost of some prettiness.

**Comment by edwardloveall** [comment]
I also like @HarrisonB's suggestion of processing the markdown into Lucky code then rendering it. My only reservation is it puts the other step in front of the developer that they have to troubleshoot when something goes wrong.

**Comment by HarrisonB** [comment]
I really like @edwardloveall’s solution. Explicit is nice because also does a bit of explaining why you’re doing it this way. Though it does feel a bit verbose at times.

Also, there is a bit of a catch with Markdown specifically: it doesn’t have syntax errors. So there’s no real advantage to doing things at compile time. For ECR it could still be beneficial, but I don’t know how it’d work with string interpolation.

One other idea we could consider is “inline tags”, sort of like what [Pug does](
https://pugjs.org/language/interpolation.html#tag-interpolation), but I don’t know what that would look like and it would probably involve adding custom syntax.

**Comment by edwardloveall** [comment]
Quick note before I forget, it could also be a short `s` method or something less verbose. Perhaps it could even wrap another tag like `s { link "foo" to: ... }`

**Comment by robacarp** [comment]
I could vote for a space method, and if nothing else it's a quick bridge for most situations. I can easily add it to my application today and get moving.

[Lucky is already inserting spaces _sometimes_](https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/base_tags.cr#L60) and [not _others_](https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/base_tags.cr#L71)

However, I think it's important to be careful of the paradigm too. For reasons that may be lost to time, HTML (and the way browsers interpret it) was designed to collapse whitespace, but not remove it. A single space in a .html file is the same as 43 spaces, newlines, and tab characters. Web developers have been hacking this with `&nbsp;`s for literally decades. We get around a lot of this behavior with CSS manipulation.

My preference would be to build a system which behaves like html behaves, but admittedly the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) is subjective.

**Comment by robacarp** [comment]
Just to sync the discussion with gitter, @paulcsmith is going to give a swing at implementing something like this soon: 

`raw “Name #{strong user.name}”`

**Comment by jwoertink** [comment]
We already have a `raw` method though... https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/specialty_tags.cr#L56-L58

One implementation could be:

```
def space
  raw("&nbsp;")
end
```
