### ISSUE TITLE
Docker with Lucky + new CLI tool for using Lucky with Docker

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#671]
### The promised land of Docker

* Everyone uses the exact same tools/versions
* New team members get up and running quickly
* New Crystal/Lucky users don't have so many things to set up locally
* New versions of Crystal wouldn't break Lucky since the image would be locked to a particular version :)
* Easy to deploy anywhere

This would solve a lot of issues people have with SSL and Crystal on Mac, installing Postgres with proper tools. Configuring username/password, etc.

### The reality (IMO)

* It is quite difficult to get a docker environment working if there aren’t very good tutorials on how to make it work with your environment
* Commands are very loooong: `docker-compose exec app lucky gen.page Users::IndexPage`. That’s a pain.
* Requires new Lucky users to learn the ins and outs of Docker to get started. I don't want to add another barrier to learning Lucky/Crystal.
* Docker filesystem on Mac/Windows is incredibly slow. This makes file intensive operations like “yarn install” 10x as slow.  I think I’ve found a way around this though. 

### How I think we can bridge the gap

* Generate docker files that work out of the box with node/yarn, Postgres, crystal
* Make docker the default way to use Lucky. Use it in all the guides
* Write guides for deploying the image to Heroku and Digital Ocean

Just having something that works out of the box and guides that use it would help a lot. **But it is still a pain to remember the long commands and have to constantly type them out**. It is also a pain to remember which app to run commands on. That’s where the next part comes in:

**Build a script/CLI that makes it much easier/faster to use**

### CLI called “Up”

The idea here is that for the most part you use tools like you normally would instead of needing to know all about Docker and which services do what. So you could do `up yarn install`, `up lucky gen.action Users::Index`, etc. and it will know what to do with those.

* `up`  -> Starts the containers and attaches to the app so you can see the logs
* `up stop`
* `up nuke` -> deletes images and redoes everything
* `up restart` -> start and stops the containers but keeps the images
* `up logs`
* `up tail` -> shortcut for tailing logs `up logs -f`
* `up logs <app>`
* `up <any command not recognized>` -> Run in the `app` container. So `up crystal spec` run `crystal spec` in the app container.
* `up ssh` -> find process and then start interactive bash into it!

At first I'd like this to just work with Lucky, but I think eventually this could be used with just about any project using Docker. Maybe with an `up.yml` file:

```yaml
delegates:
  yarn:
    service: node
  rails:
    service: app
  rspec:
    service: app
    config: # optional
      some_env_key_or_config_option: :foo
```

## Things to test

- Work well with chromedriver/LuckyFlow
- LiveReload works with assets/html
- Lucky precompiled tasks work
- Opening screenshots with LuckyFlow

**Comment by paulcsmith** [comment]
@jwoertink said you are a Docker fan, @russ. I'd love to hear what you think of this

**Comment by russ** [comment]
I like this approach a lot. I think it will definitely help new and "old" users alike.

Would this be specific to Lucky or would there be an up config file mapping what commands start, stop, restart, etc run?

**Comment by paulcsmith** [comment]
@russ I actually *just* added a section on a `up.yml` file! I think at first it'd be easiest to get an MVP out there with just Lucky/Crystal support, but there isn't anything really Lucky specific here, so I think it'd be 100% possible to make this a tool you can use with anything

**Comment by jwoertink** [comment]
I wonder if this would help with our deployment. Right now we have this `./bin/deploy` file that we copy from other projects. I have no idea what is going on, and getting an app deployed to EB is a little weird at first.

**Comment by robacarp** [comment]
Every project I setup docker for comes with a few scripts: bin/develop, bin/package, bin/publish, bin/serve and bin/dev_database (at least).

- bin/develop: a wrapper around the docker/compose commands required to get a local dev environment up and running.
- bin/package: a wrapper around docker commands required to build a non-development container, and tag it in a predictable way.
- bin/publish: (usually) a wrapper around some aws commands required to publish to ECR.
- bin/serve: executed from within a container to actually start the server. Commonly it also sub-shells to another process which fetches database credentials from Parameter Store or Vault, and exports them to the actual server process.
- bin/dev_database: a shortcut that drops a dev into the psql prompt _inside_ the docker compose environment; also has some hooks to import a sql file into that database.

A good portion of what you have there could be pretty easily represented as shell aliases to docker-compose commands, and it's essentially what I've tried to create with the bin/ scripts.

**Comment by paulcsmith** [comment]
@robacarp Thank you for sharing. Would you be willing to publish some of those scripts?

Also I think you're right about some of them, but a lot of what I think the CLI could do well is delegate to the correct container. This could be done with a script instead, but I guess I just prefer writing Crystal instead of bash. It also would make it easier to work on Windows, which right now is unsupported.

If we did go a bash script route we could do `bin/up` instead, but I'm not totally sold on that. I think it is harder to test bash scripts and the code is usually pretty messy.

I think some scripts would still be in Lucky though. A `bin/setup` script to run all the migrations, seeds, yarn deps, etc.

**Comment by paulcsmith** [comment]
Oh and I agree a lot of it could be done with shell alias commands, but I'd like to have it standardized so the guides match what people use. Asking people to create a bunch of aliases is a big ask for someone just starting out, and it is also hard to update if we add more aliases

**Comment by ianpurton** [comment]
I'm currently developing lucky applications on windows using docker.

We have multiple projects running different architectures. So our workflow revolves around docker-compose up. We have the minimum amount of tooling installed natively.  

My docker-compose.yml has postgres intergrated.

I think you have to split this into 3 parts from a new users perspective.

**Project Intialization**

Creating a lucky project. Ideally I want to do something like.

`docker run lucky/lucky-0.12 lucky new myproject`

This completely removes the part of the install guide with install crystal and build lucky. This would be a docker image maintained by the lucky project owners.

**Day to day development**

cd into myproject and run 

`docker-compose up`

Point my browser at locahost:3001, Fire up VSCode and I'm away. This gives me a full development environment with headless chrome etc. 

It wouldn't be a big deal for me to run lucky tasks via an official image. i.e.

`docker run lucky/lucky-0.12 lucky db.migrate`

**Docker deployments to prod** 

I'm not using docker for deployments. Heroku works fine. But this would be another Dockerfile with all the dev tools removed. A prod dockerfile has to have a low attack surface.

Here's my development docker file.

    # Use the official crystal image
    FROM crystallang/crystal:0.27.0

    # Install Lucky dependencies
    RUN apt-get update \
        && apt-get install -y curl libc6-dev libevent-dev libpcre2-dev libpng-dev libssl-dev libyaml-dev zlib1g-dev wget \
        && curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
        && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
        && curl -sL https://deb.nodesource.com/setup_8.x | bash \
        && apt-get install -y nodejs yarn git \
        && apt-get install -y postgresql-client \
        && curl https://cli-assets.heroku.com/install.sh | sh

    # Install chrome so we can have headless browser testing.
    RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
        && apt-get update \
        && dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install \
        && apt-get install -y fonts-liberation libappindicator1 xdg-utils \
        && apt-get install -y libnss3 

    # Change the workdir inside the container
    WORKDIR /app

    # Copy in project files
    COPY . .

    # Install shards
    RUN shards install

    # Let's patch the shards to run headless.
    RUN sed -i -e 's/# chromeOptions/chromeOptions/g' lib/lucky_flow/src/lucky_flow/server.cr

    # Build lucky CLI so we can use it
    RUN crystal build lib/lucky_cli/src/lucky.cr --release --no-debug -o /usr/local/bin/lucky && chmod +x /usr/local/bin/lucky

    # Build all the node packages
    RUN yarn --pure-lockfile

    RUN npm run dev

**Comment by robacarp** [comment]
Eh, when I said `bash aliases`, I should have said `bash wrapper scripts`. I wouldn't recommend that we actually use the bash alias functionality to accomplish this. Shipping a bunch of scripts (in whatever language) is my approach of choice as well.

I prefer to use bash for this sort of thing, not because it's a fun language to write but because it's particularly well suited to mangling commands and spawning/chaining commands. No messy PTY code, etc. It also has the big benefit that it doesn't require any compiling.

I'm [uploading a bunch of the dev and deployment workflow scripts](https://github.com/robacarp/devops_scripts) I use as a starting point for applications, a project I've been putting off for way too long.

**Comment by paulcsmith** [comment]
@robacarp @ianpurton how do you handle CI? I’ve got it working under Travis but setup takes a long time since none of the layers are cached :S this is one of the final issues I haven’t quite figured out

**Comment by paulcsmith** [comment]
Thanks for posting @ianpurton! Sounds like this might just be one of the downsides of Docker unless you're willing to pay Circle for layer caching :P

**Comment by ditsara** [comment]
Regular docker user here (on Linux) -- I recently created a sample app to learn more about Lucky and Crystal.

Would my `Dockerfile` and `docker-compose.yml` (below) be helpful? I haven't integrated chromedriver, so there might need to be a few small changes.

I find that docker-compose (and the bash-it aliases) meets my needs quite well for regular development. Bash-it aliases `docker-compose` to `dco`, and additionally I alias `docker-compose run --rm web` to `dcor`. So I commonly use:

- `dco up -d` -- Starts the containers detached (or leave out `-d` to start attached)
- `dco stop`
- `dco down` -- deletes images and redoes everything
- `dco restart` -- start and stops the containers but keeps the images
- `dcol` -- tails all the logs; equivalent to `docker-compose logs -f`
- `dcor <command>` -- Run in a new app container, ie `dcor crystal spec` or `dcor bash`
- `dco exec web <command>` -- Run command in running app container (I rarely use this)

## docker-compose.yml

```YAML
version: '3'
services:
  db:
    image: postgres:9.4

    environment:
      POSTGRES_USER: lucky
      POSTGRES_PASSWORD: developer
    volumes:
      - data:/var/lib/postgresql/data
  web:
    image: ditsara/lucky:development
    build:
      context: .
    environment:
      DB_HOST: db
      DB_USERNAME: lucky
      DB_PASSWORD: developer
    ports:
      - 3001:3001
      - 3002:3002
      - 5000:5000
    volumes:
      - .:/app:cached
    working_dir: /app
    command: script/dev
    depends_on:
      - db

volumes:
  data:
```

## Dockerfile

```Dockerfile
FROM crystallang/crystal:0.27.2
LABEL MAINTAINER="Dan Itsara <dan@glazziq.com>"

ENV builddir=/build

# - Install Lucky prereqs
#   - Overmind
#   - Node and Yarn
#   - other libs
# - Install Lucky
# - Cleanup build
RUN mkdir -p $builddir && cd $builddir \
  && apt-get update -qq \
  # curl for downloads, tmux required for Overmind
  && apt-get install -y curl tmux \
  # Overmind
  && curl -L -O https://github.com/DarthSim/overmind/releases/download/v2.0.1/overmind-v2.0.1-linux-amd64.gz \
  && gunzip overmind-v2.0.1-linux-amd64.gz \
  && mv overmind-v2.0.1-linux-amd64 /usr/local/bin/overmind \
  && chmod +x /usr/local/bin/overmind \
  # Node and Yarn
  && curl -sL https://deb.nodesource.com/setup_9.x | bash -\
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -\
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list\
  && apt-get update -y \
  && apt-get install -y nodejs yarn=1.7.0-1 \
  # all other libs
    libc6-dev libevent-dev libpcre2-dev libpng-dev libssl-dev libyaml-dev zlib1g-dev postgresql postgresql-contrib \
  && git clone https://github.com/luckyframework/lucky_cli $builddir/lucky_cli \
  && cd $builddir/lucky_cli \
  && git checkout v0.13.2 \
  && shards install \
  && crystal build src/lucky.cr --release --no-debug \
  && mv lucky /usr/local/bin/lucky \
  && cd / && rm -rf $builddir

WORKDIR /app
```

**Comment by paulcsmith** [comment]
Here is the preview of the `up` command line tool https://github.com/paulcsmith/up

If you all could give it a shot and LMK what you think that'd be great. Feel free to leave issues/feedback on that repo!

**Comment by paulcsmith** [comment]
And thanks for the examples @ditsara. This will be helpful when I build out the default docker stuff for Lucky

**Comment by paulcsmith** [comment]
I'm getting close to what I feel is a nice Docker set up but compiles seem to take 2-3 times longer...

Could someone try it out? https://github.com/paulcsmith/website-v2#setting-up-the-project

Is this slow compile time normal? Maybe it is just how I set up Docker? 

It may be my machine (I've got an extremely aggressive virus/malware suite on here because of work).

**Comment by ianpurton** [comment]
I cloned and ran with `docker-compose up`  and got the following build error.

When I run `docker-compose run app bash` and take a look around I don't have the lib folder which I would expect to have been created from the shards install in the Dockerfile.

Maybe the `COPY . /data` (line 29 in the Dockerfile) overwrites it?

```
Step 6/6 : COPY . /data
 ---> 3168c45a346d
Successfully built 3168c45a346d
Successfully tagged website-v2_assets:latest
WARNING: Image for service assets was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating website-v2_assets_1 ... done
Creating website-v2_app_1    ... done
Attaching to website-v2_assets_1, website-v2_app_1
            yarn run v1.13.0
            $ yarn run webpack --watch --hide-modules --color --config=node_modules/laravel-mix/setup/webpack.config.js
            error Command "webpack" not found.
            info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
            error Command failed with exit code 1.
            info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1     | Error in tasks.cr:2: while requiring "./src/app"
app_1     |
app_1     | require "./src/app"
app_1     | ^
app_1     |
app_1     | in src/app.cr:1: while requiring "./shards"
app_1     |
app_1     | require "./shards"
app_1     | ^
app_1     |
app_1     | in src/shards.cr:2: can't find file 'dotenv'
app_1     |
app_1     | If you're trying to require a shard:
app_1     | - Did you remember to run `shards install`?
app_1     | - Did you make sure you're running the compiler in the same directory as your shard.yml?
app_1     |
app_1     | require "dotenv"
app_1     | ^
app_1     |
website-v2_assets_1 exited with code 1
website-v2_app_1 exited with code 0
```

**Comment by ianpurton** [comment]
I've started experimenting with another approach by installing VSCode into the image and using the this as a way to completely version my environment.

Web based VSCode https://medium.com/coderhq/coder-v0-2-providing-all-of-vs-code-in-the-browser-a830535050ee

Dockerfile is here https://github.com/ianpurton/development_environments/blob/master/lucky-framework/Dockerfile

I can then open the terminal in VSCode and run crystal/lucky commands as well as headless browser testing.

![image](https://user-images.githubusercontent.com/36966/56562710-4cde6600-65aa-11e9-8c1c-d6db497026da.png)

**Comment by chillfox** [comment]
There is a serverless deploy tool called up 
https://github.com/apex/up

**Comment by paulcsmith** [comment]
After playing around with Docker for the past 8 months I don’t think we should add this out if the box. There are so many ways to use Docker and it takes so much effort to keep things working that we can’t support it right now

Once lucky is a bit more stable we may add some kind of recipe for adding this but we just can’t afford to do it now
