### ISSUE TITLE
Add detailed log formatter outputting to dedicated log file

### ISSUE THREAD

**Issue by HarrisonB** [luckyframework/lucky#682]
While a user can create their own log formatter and add it to their middleware, I think it would be helpful to also include a more detailed log formatter that outputs to a dedicated log file (with one for each environment, e.g. `log/development.log` à la Rails). This could include SQL logging like what's requested in #357.

Honestly, I think that Rails's logging is a fine example to follow, but I'm curious what other info different frameworks include by default. It seems Rails includes the following by default:

* HTTP method
* Resource path
* IP of requesting user
* Timestamp of start of request
* Action that will be generating response (or basically where the request is being routed)
* Format of expected response
* Request parameters
* Session
* User agent
* Headers (with user agent included again--not sure why it's separated out in Rails)
* SQL queries (with timings)
* View renders (with timings)
* HTTP response status
* Total time to return response (with subtotals for view rendering and DB interfacing)

In terms of presentation, Rails's formatting is very readable (IMO) but it may not be as parseable for search purposes and may cause problems when requests are interleaved. For this reason, we may also want to look into key-value-style loggers (e.g. [LogRage](https://github.com/roidrage/lograge)) as a default for production environments.

**Comment by paulcsmith** [comment]
Partly addressed in #697 

I think adding too much by default would be overwhelming, BUT I think we should add some of this such as the content_type and so more timing info.

The other stuff can either be logged by the user if they want it (I want to make it so you can attach whatever data you want to logs) or maybe it will be in a debug page.

The new implementation in #697 will also allow you to write to files, or a mix of files + STDOUT if you want!

**Comment by paulcsmith** [comment]
I think I'll close this for now as the new logger supports a lot more options, and we can add more detailed logging in a fancy debug page!
