### ISSUE TITLE
Allow creating App instance without LogHandler for specs

### ISSUE THREAD

**Issue by mikeeus** [luckyframework/lucky#690]
This would be useful for request specs which currently print out like:
![image](https://user-images.githubusercontent.com/16954412/42882245-5a93df08-8aa1-11e8-9c89-1d8247e44a90.png)
But would be nicer like:
![image](https://user-images.githubusercontent.com/16954412/42882315-7424e598-8aa1-11e8-9269-3c8fd687aa4c.png)

I'm thinking something like this:
```crystal
class App
  private getter server

  def initialize(@quiet : Bool = false)
    @server = HTTP::Server.new [Lucky::HttpMethodOverrideHandler.new]
    unless @quiet
      @server << Lucky::LogHandler.new
    end
    
    @server += [
      # Disabled in API mode, but can be enabled if you need them:
      # Lucky::SessionHandler.new,
      # Lucky::Flash::Handler.new,
      Lucky::ErrorHandler.new(action: Errors::Show),
      Lucky::RouteHandler.new,

      # Disabled in API mode:
      # Lucky::StaticFileHandler.new("./public", false),
      Lucky::RouteNotFoundHandler.new,
    ]
  end
  ...
end
```
And it can be used in `spec/setup/start_app_server.cr` like:

```crystal
app = App.new(quiet: true)
...
```

Any thoughts?

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky_cli/pull/298
