### ISSUE TITLE
exposing SO_REUSEPORT

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#707]
Prior to 0.13, there was an `app.cr` file generated which had a `listen` method. This method called `server.bind_tcp` where the third argument is `reuse_port`. Since this method was exposed, it was easy to just add `true` at the end for this feature.

Now that it's been abstracted away in to a parent class, this method is hidden. Just as easily, we can override the method, but maybe this is a good time for some sort of configuration setting? 

```crystal
class App < Lucky::BaseApp
  #...
end
Lucky::BaseApp.configure do |setting|
  setting.reuse_port = true
end
```

Or maybe this is on by default? I'm not sure what the implications to having it on by default is, but I know that we have it set to on for our apps.

**Comment by paulcsmith** [comment]
Yes I think adding a config setting makes sense. Would you mind opening a PR for this on this repo and lucky_cli in config/server.cr that adds this and defaults to false?

**Comment by paulcsmith** [comment]
Actually I think the problem here is it isn't flexible enough. I can see someone wanting to set other options or SSL stuff when listening. It'd be a bummer to have to keep adding settings for everything you can do.

How about instead we make `listen` and `abstract def` and move the listen code to be generated in lucky_cli. That way people can do whatever they want with it, just like before. What do you think?

**Comment by jwoertink** [comment]
That's fine, but that doesn't fix another thing I just saw where the `base_uri` defaults to `http`. If that's used in production at all, then people will want to update that to `https`. Aside from those 2 things, I can't think of any other options people would want.

**Comment by paulcsmith** [comment]
Good call. Let's also add an `abstract def protocol` that defaults to `http`. I think that'll be a good stop-gap. I'm planning to rework how host/port and all that works so it is more reliable and use friendly, but for now I think this'll work

**Comment by jwoertink** [comment]
Ok. I'll make those 2 abstract defs and submit that PR 😄

**Comment by paulcsmith** [comment]
Thank you :D

**Comment by jwoertink** [comment]
This is resolved now.
