### ISSUE TITLE
Include comments on page (in dev only) that print the component that rendered them

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#715]
This would make it much easier to look at the page source and determine what component to look at:

Example:
<img width="659" alt="screen shot 2019-03-03 at 11 01 28 pm" src="https://user-images.githubusercontent.com/22394/53709835-4d5b4b80-3e08-11e9-849a-a19909b6a4a3.png">

**Comment by jwoertink** [comment]
ooo! I really like this one 😄
