### ISSUE TITLE
/bin/bash^M: bad interpreter

### ISSUE THREAD

**Issue by saggit** [luckyframework/lucky#718]
Hi, i am new to lucky, this error seems quit simple to solve with dos2unix, but could not found file `script/precompile_tasks`, full error see below:

```shell
Installing lucky (0.13.3)
  Postinstall script/precompile_tasks
  Failed script/precompile_tasks:
  /bin/sh: script/precompile_tasks: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by paulcsmith** [comment]
Hey @saggit! Is this a brand new app? Also, what OS are you on?

**Comment by saggit** [comment]
thanks for your reply, Yes it’s a brand new app with lucky init and I am running on MacOS 10.13

**Comment by paulcsmith** [comment]
Interesting. It should work because the script is written with unix line endings. When I look at the file locally and run `dos2unix` it does not make any changes to the file. Can you paste the output of `which bash` and also `echo $PATH`. Also what shell are you using? zsh, bash? I'm not sure that would matter but maybe it'll help us track it down

**Comment by saggit** [comment]
@paulcsmith  I am use the zsh 

```shell
➜  hwapp git:(master) ✗ which bash
/bin/bash
➜  hwapp git:(master) ✗ echo $PATH
/usr/local/opt/ruby/bin:/usr/local/bin:/Users/kelvince/.cargo/bin:/Users/kelvince/Envs/djproject/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/kelvince/golang/bin:/usr/local/share/dotnet:/Users/kelvince/.rvm/bin

```

**Comment by robacarp** [comment]
@paulcsmith I suspect the extra space here is causing the issue: https://github.com/luckyframework/lucky/blob/master/script/precompile_tasks#L1

**Comment by paulcsmith** [comment]
Ahh, thanks @robacarp. I have that space in all of the scripts so this should be removed from all the them then. Since I can't reproduce this issue,  I'll try to get to this soon so we can see if it works for @saggit.

**Comment by robacarp** [comment]
@paulcsmith I'm unable to reproduce it as well, even when executing it under `sh`, so I don't think that's the problem. [There is a more bulletproof way of writing shebang lines](https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash) but it's probably not that important.

**Comment by saggit** [comment]
I think the problem may solved, my Git config somehow set `core.autocrlf=true`,  Thanks for all your help.

**Comment by paulcsmith** [comment]
That’s great news! I’m glad you figured it out
