### ISSUE TITLE
[Discussion] Changing params API

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#727]
## The current way

```crystal
params.get(:page) # Single value from top level params, e.g. "1"
params.nested(:user) # Hash of attributes under key, e.g. {"name" => "Jane"}
params.many_nested(:users) # Array of hash attributes under key, e.g.  [{"name" => "Jane"}]
```

These methods are mostly used for internal Lucky/Avram code and rarely used in user code, but I think we should make them clearer so when people try to contribute it makes sense.

## What might be better

```crystal
params.get(:page) 
params.hash(:user)
params.array(:users)
```

I think these new names read a lot better, make more sense, and are a tad bit shorter too :)

Thoughts? cc @HarrisonB @jwoertink @edwardloveall

**Comment by jwoertink** [comment]
Is there something that prevents using `params.get` to return a single value, hash, or array?

**Comment by jwoertink** [comment]
Sounds like a decent reason to me. I don't think I've really needed to use the nested yet, however, I don't like `many_nested`. It's just a weird method name that I'm sure I'll never remember lol. I like the proposed names. 

I haven't checked, but if you did `params.array_of(:page)`, would that return `["1"]`, or blow up?

**Comment by paulcsmith** [comment]
Yeah for the most part the methods are used internally by Lucky and Avram but I figure if we can make them better we should haha. 

In the case of array_of(:page) it would raise because the param is not an array

**Comment by paulcsmith** [comment]
I also wonder if `params.hash_for(:user)` makes more sense. Since it isn't used much outside of internal Lucky/Avram code the extra clarity might be good. Does that make more sense or was `params.for(:user)` ok?

**Comment by HarrisonB** [comment]
I think hash_for is a good change (on top of the suggested changes).

We also may want to look towards Onyx’s param handling for other ideas in dealing with params

Harrison Bachrach

**Comment by paulcsmith** [comment]
@HarrisonB Can you provide a bit more detail on what you mean? I think Onyx has a great type safe way to handle this, but this is for more ad-hoc param access. I do want to see if we could work with Onyx param handling for query params at the action level. That way Lucky doesn't need to roll its own!

**Comment by HarrisonB** [comment]
@paulcsmith Ah, gotcha. Yes, I think integrating with Onyx itself for structured params makes sense.

> The other option would be to have a wrapper class like Crystal uses with `JSON::Any` but that has also been confusing (at least to me) because you often need to use `as` and `to_x` a bunch of stuff and the errors are hard to understand when you get it wrong

This was the other thing I was thinking but these are valid points.

The only thing that I might suggest is changing "for" to another preposition? Maybe `hash_at`?

Also, what would `params.get(:user)` return? A hash?

**Comment by paulcsmith** [comment]
`params.get(:user)` would return a single value if there was one, or it would raise. I like `hash_at/for`. Thank you for the feedback!

**Comment by paulcsmith** [comment]
Maybe `params.for` could/should be `params.value_at` for extra clarity? `params.value_at(:page)`

**Comment by jwoertink** [comment]
Would this `params.value_at` only return a Hash? So `params.value_at` and `params.array_at`?

**Comment by paulcsmith** [comment]
I wrote the wrong thing at first. I meant `params.get` could be `params.value_at`. So it'd return a single value

**Comment by skojin** [comment]
I vote to have also params[:name] to return single value. value_at is too long.
Also I like "get" over "value_at" because it more short.
And I not like "_at" suffix, for me value, hash, and array is better

**Comment by paulcsmith** [comment]
One thing to keep in mind is that you should rarely ever use these methods yourself, so length may not matter as much. The only time I ever use these is when I'm writing code in Lucky or Avram.

With that said I kind of agree with the `_at`. I'm not sure if it actually helps. I'd rather not do `params[]` because then it looks like it is a hash, but it isn't really.

Then again maybe I should just make the param parser a hash :P I think that could be hard to traverse but maybe it is worth it for simplicity.

**Comment by edwardloveall** [comment]
I like the naming of `hash_at` or `hash` and others because it predictable and memorable once you've learned what they do. Using those methods encourages thinking about the return value you're working with.

`value(:name)` is a little weird to me because there are other places where we use that method name. `cookie.value` or `field.value` or `where_clause.value`. None of these methods take an argument. I don't think this is super critical and I can't think of a better name than `params.value(:name)`, but I wanted to bring it up.

I don't love the idea of the params being a hash, mostly because then all the value would have to be some kind of union type like `String | Hash | Array` which weakens the type system. Like if I had a form that was creating multiple `tags` on the blog post, I could get them with `params.array(:tags)` and then call `each` to iterate. If it was just a hash value that could be one of three types, I could only iterate over them if I cast it to an Array first.

**Comment by paulcsmith** [comment]
Well said @edwardloveall. I think `value` can be confusing because of what you said. I think I'll stick with `get`. It isn't super clear, but is not actively misleading. That plus the fact compiler will catch if you try array or hash methods should make it fine.

**Comment by paulcsmith** [comment]
Thoughts on `array_of(:users)` and `hash_for(:user)`? Any clearer/more confusing? Not worth the extra characters?

**Comment by HarrisonB** [comment]
`array_of(:users)` to me suggests that the entries will be deserialized somehow, but maybe I'm mad 😛

**Comment by paulcsmith** [comment]
I think I’ll just keep it simple and do `array` and `hash` then :) The extra stuff might be more confusing than helpful

**Comment by edwardloveall** [comment]
An alternative to `get` or `value` could also be `single` or `scalar`, which maybe fits into the set of `array` and `hash`.

**Comment by paulcsmith** [comment]
I’m not sure  about single or scalar. Seems a bit unclear to me. What do you think about sticking with the types? `params.string(:page)` since it is always a string

**Comment by jwoertink** [comment]
I still like `get`. I'm not sure what a "scalar" is, though, I feel like after programming for 15 years I probably should know what that means 😝  but at this point, I'm too afraid to ask.

**Comment by edwardloveall** [comment]
`string` is great @paulcsmith! That definitely fits with hash and array. `get` is fine too to be honest. The strongness of my opinion on this is about 2/5

@jwoertink me too 😬 Looking it up just now, my understanding is it's a single value, but possibly with the caveat of being able to be increased and decreased. I think it comes from vector math where you have a unit vector pointing in a direction, and you "scale" each axis by a value to get the final vector. So the vector `(0, 5)` is the result of the unit vector `(0, 1)` where the `y` value is scaled by 5, thus making the scalar: 5. But don't quote me on that 😄

**Comment by rlindgren** [comment]
Lucky beginner here. Can Lucky::Params parse deeply nested hashes?
```crystal
# ?filter:a=1&filter:b=2&filter:c:a=3&filter:c:b=4
params = Lucky::Params.new(request)
puts params.nested(:filter) # => {"a" => "1", "b" => "2", "c:a" => "3", "c:b" => "4"}
puts params.nested("filter:c") #=> {"a" => "3", "b" => "4"}
```

**Comment by vlazar** [comment]
This makes a very consistent API:
```crystal
params.string(:page) 
params.hash(:user)
params.array(:users)
```
