### ISSUE TITLE
[Feature] Adding a fallback route

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#728]
This has been brought up a few times, but I'd like to actually propose something. Related to https://github.com/luckyframework/lucky_router/issues/12 I propose a `fallback` method. 

```crystal
class Fallback::Index < BrowserAction
  fallback :get do
    render(SomePage::Index)
  end
end
```

My thought is there's just another [container](https://github.com/luckyframework/lucky_router/blob/master/src/lucky_router/matcher.cr#L5) that stores the fallbacks. The fallbacks would be scoped to each HTTP method so that way you can fallback on GET and not worry about POST, etc..

a fallback is just when the router can't find anything that matches, then it looks for one of these to be defined. You would only be allowed 1 fallback per HTTP Method. This is also not to be confused with [route globbing](https://github.com/luckyframework/lucky_router/issues/3). With route globbing you may want to match something like `/posts/*dates` where dates could be `2019` ,`2019/04`, `2019/04/01`, etc... With the fallback it's just "I didn't find anything that matched, so just run this code instead".

This could happen [here](https://github.com/luckyframework/lucky/blob/master/src/lucky/route_handler.cr#L11) which would be updated to something like:

```crystal
    if handler
      Lucky.logger.debug("Handled by #{handler.payload.to_s.colorize.bold}")
      handler.payload.new(context, handler.params).perform_action
    elsif Lucky::Router.has_fallback?(context.request)
      Lucky::Router.fallback_handler(context, handler.params)
    else
      call_next(context)
    end
```

The main usecase @russ and I have for this is working with SPA. When you want to do deep linking in to your app, Lucky throws a route not found exception. There's a few current "hacks" for this:

1. piggyback off `handle_error(error : Lucky::RouteNotFoundError)` in `Errors::Show` which would allow you to render a specific page. The downside is this puts some view rendering logic in an errors action where your app now is based around throwing an error. Also, handling when it really should be a 404 becomes tricky.

2. Define all the same routes you have in your SPA router in Lucky as well. This means duplicating routes in 2 different languages. Very prone to missing something.

**Comment by paulcsmith** [comment]
I like this idea I just don't have time to get to it :( If you can contribute then yeah let's do this! I think we should keep it all in Lucky and not in LuckyRouter though. This seems like a framework specific thing and I think it'll be easier to test that way too (won't require changes to two repos at once).

Can you explain why you'd need different fallbacks for different HTTP methods?  That's the one part I'm not totally sure about (I haven't worked on an SPA in awhile :D). My thought was that this was only necessary on GET requests and so could probably just be `fallback do/end` and catch all. But I may be missing the use case

**Comment by jwoertink** [comment]
I'll try to keep it all in lucky. My thought was by storing it in the router, it keeps the storage of that data somewhere, but I guess that can sort of be mimic'd in lucky itself.

I originally was going to do `fallback do/end` , but then I started thinking about how in our apps, we get people constantly trying to hack in by doing POST or PUT with random URLs. I wouldn't want any POST/PUT,etc.. to go to our fallback. If it did, then that would mean I'd have to catch the request method to return early. 

I guess what we could do is default it to `:get`. Then if you don't specify, it's assumed it's `"GET"`. Unless you think it should only fallback on GET? I think I'd be ok with that too considering I don't think I've ever needed a fallback for a POST. 

I'll start with GET, and see how far I get. If we decide let's add the rest, I can make that change.

**Comment by paulcsmith** [comment]
Oh I see what you mean now. Yeah let’s just do the fallback for GET to start. 

I’m guessing the fallback action could be stored in the Lucky::Router https://github.com/luckyframework/lucky/blob/master/src/lucky/router.cr
