### ISSUE TITLE
More complete support for configuring CORS

### ISSUE THREAD

**Issue by HarrisonB** [luckyframework/lucky#737]
Right now in the guides, for JSON APIs we have

> ## Handling CORS
> 
> When working with an API, you may need to set some [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers. Doing this in Lucky is pretty easy!
> 
> In your `src/actions/api_action.cr`, you can use a `before` action to set your headers.
> 
> ```crystal
> abstract class ApiAction < Lucky::Action
>   before set_cors_headers
> 
>   def set_cors_headers
>     response.headers["Access-Control-Allow-Origin"] = "*"
>     response.headers["Access-Control-Allow-Headers"] = "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
>     continue
>   end
> end
> ```

This works for [Simple Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests), but not for more complex requests (e.g. `PUT` requests, requests with custom headers, etc.). Those must send a "pre-flight" `OPTIONS` request to get the necessary permissions, which a Lucky-backed application should be able to respond to with the correct headers.

Responses to `OPTIONS` requests should also include a `Access-Control-Allow-Methods` header with an appropriate value.

There are a few options on how to handle this:
* Add some middleware to respond to `OPTIONS` requests before they get to the `Lucky::RouteHandler`
  * This makes it very easy to add, remove, or modify globally, but makes per-endpoint changes a bit cumbersome
* Modify `LuckyRouter::Matcher` to match on `OPTIONS` requests that have a corresponding `GET`, `POST`, etc. endpoint and handle it somehow
  * This seems like a bad mixing of responsibilities
* Have `Lucky::Action` autogenerate `OPTIONS` endpoints when creating `GET`, `POST`, etc. endpoints.
  * This might be a bit tricky to actually implement. Not sure.

`Lucky::ErrorAction`s should also return valid CORS headers, which is not currently possible (without setting the headers for every `handle_error` method individually). This can be done easily once #736 is resolved.

It might also be nice to wrap this up in a setting or a mixin so that you only need to set this up in one place.

**Comment by jwoertink** [comment]
I agree dealing with cors is a pain. Right now all my CORS stuff is handled by nginx though, so I haven't needed to do anything custom in Lucky directly to really feel it out. Right now if you need options, you can do 

```crystal
match :options, "/profile" do
  # action code here
end
```

But one thing I haven't tried yet is if you need a specific action to respond to both `OPTIONS` and `PUT`, then how that would work since you can only do 1 route per action.

I'm not really sure what the best option is here, but for your third suggestion, we already do that for GET requests [here](https://github.com/luckyframework/lucky_router/blob/master/src/lucky_router/matcher.cr#L9-L11)

**Comment by HarrisonB** [comment]
The thing about non-global solutions is that, to me, they feel a bit odd.

If i hit a endpoint you don’t respond to, you shouldn’t fail to provide a response for CORS reasons (unless that’s your intent).

**Comment by ianpurton** [comment]
I'm trying to get around this using the following pattern (added to my ApiAction class.

It works for the pre-flight request but it also seems to override my get action and so gets called twice.

Does anyone have a solution for this?

```
match :options, "/profile" do
  response.headers["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS, DELETE" 
  text "", 204
end
```

**Comment by jwoertink** [comment]
I'm not sure if this is the right way yet since the app i'm doing cors stuff on isn't in production, but I added a handler:

```crystal
Lucky::ErrorHandler.new(action: Errors::Show),
Lucky::CORS.new,
Lucky::RouteHandler.new,
```

Then I dropped [this in](https://gist.github.com/jwoertink/d3249ede2f080ec8754cc5a63804b31a).

None of my actions mention any cors stuff, and it seems to work locally for what I'm doing. I think this should be built in to Lucky though with a much easier way to configure.

**Comment by ianpurton** [comment]
@jwoertink Thanks, I tweaked it a bit to fit my use case.

I added `Lucky::Cors.new` to my src/app.cr

Then created the following as cors_handler.cr in a handlers folder and included it into the app.cr.

```crystal
module Lucky

  class CORS
    include HTTP::Handler

    def call(context : HTTP::Server::Context)
      call_next(context) unless context.request.method == "OPTIONS"

      context.response.headers["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS, DELETE" 
      context.response.headers["Access-Control-Allow-Headers"] = "X-API-KEY, Content-Type, Accept, Origin, Authorization"
      context.response.headers["Access-Control-Allow-Origin"] = "*"
    end

    private def preflight?(context)
      context.request.method == "OPTIONS"
    end
  end
end
```

**Comment by jwoertink** [comment]
Dropping this example in for future references: https://gist.github.com/jwoertink/76454c6cfc78b42b33384bba3cb13bde. CORS has many different ways to handle it, but hopefully we can come up with a easy to use minimal setup for this just to get people going.

**Comment by jwoertink** [comment]
We now have a better guide for handling CORS https://www.luckyframework.org/guides/json-and-apis/cors

I'm gonna close this out for now. If your app uses CORS, please take a look over the guide and let us know if we're missing anything.
