### ISSUE TITLE
ErrorHandler has useless Habitat setting

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#740]
When https://github.com/luckyframework/lucky/pull/721 got merged in, it removed the usage of  the `show_debug_output` setting on ErrorHandler. It [used to](https://github.com/luckyframework/lucky/blob/5648b98a797527582c5c54de0b9fbbad9609c0cb/src/lucky/error_handler.cr#L16) be used for showing changing the output. 

If this option is no longer used, we should just remove the Habitat setup from it. 

/cc. @HarrisonB

**Comment by jwoertink** [comment]
Turns out this setting still exists https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/src/actions/errors/show.cr.ecr#L33

@paulcsmith Are we trying to get rid of this setting? [ref](https://github.com/luckyframework/lucky/issues/719)

**Comment by paulcsmith** [comment]
I think it should still stick around. We need some way to configure whether we show debug output or a user friendly error page. We do need to change error handling so it is more intuitive but I’ve been thinking that may require multiple changes that still aren’t quite coming together yet. I hope I can share something soon that looks better

**Comment by jwoertink** [comment]
cool. I'll close this out for now.
