### ISSUE TITLE
ForceSSLHandler - Hsts error

### ISSUE THREAD

**Issue by volodymyrgreen** [luckyframework/lucky#743]
Hi. Lucky shows the following error after initialization of new app during compiling process:
```
web    | Compiling...
web    | Unhandled exception: The 'hsts' setting for Lucky::ForceSSLHandler was nil, but the setting is required.
web    |
web    | Try this...
web    |
web    |   Lucky::ForceSSLHandler.configure do |settings|
web    |     settings.hsts = Nil
web    |   end
web    |  (Habitat::MissingSettingError)
```
Maybe we should add a default value for `Lucky::ForceSSLHandler#settings.hsts`? 
Or at least make it optional.

**Comment by paulcsmith** [comment]
Hi! Are you using lucky master? Or is this the officially released version?

If you are using master then yes we will add this before release. If this is the officially released version then this is a bigger problem :)

Could you paste the shard.lock file from your app?

**Comment by volodymyrgreen** [comment]
Sure.

<details>
<summary>My shard.lock</summary>
version: 1.0
shards:
  authentic:
    github: luckyframework/authentic
    version: 0.3.0

  avram:
    github: luckyframework/avram
    version: 0.9.3

  blank:
    github: kostya/blank
    version: 0.1.0

  callback:
    github: mosop/callback
    version: 0.6.3

  carbon:
    github: luckyframework/carbon
    version: 0.1.0

  cli:
    github: mosop/cli
    version: 0.7.0

  cry:
    github: paulcsmith/cry
    version: 0.4.0

  db:
    github: crystal-lang/crystal-db
    version: 0.5.1

  dexter:
    github: luckyframework/dexter
    version: 0.1.1

  dotenv:
    github: gdotdesign/cr-dotenv
    version: 0.2.0

  exception_page:
    github: crystal-loot/exception_page
    version: 0.1.2

  habitat:
    github: luckyframework/habitat
    version: 0.4.1

  lucky:
    github: luckyframework/lucky
    commit: 9a8ebb47d50e19ce2d974a16401708e2901d092d

  lucky_cli:
    github: luckyframework/lucky_cli
    version: 0.13.2

  lucky_flow:
    github: luckyframework/lucky_flow
    version: 0.4.0

  lucky_router:
    github: luckyframework/lucky_router
    version: 0.2.2

  optarg:
    github: mosop/optarg
    version: 0.5.8

  pg:
    github: will/crystal-pg
    version: 0.15.0

  selenium:
    github: ysbaddaden/selenium-webdriver-crystal
    commit: a6d0e63ab7ddc6a20923bf4157bc6247c1fa2acc

  shell-table:
    github: luckyframework/shell-table.cr
    commit: 078a04ea58ead5203bb435a3b5fff448ddabaeea

  string_inflection:
    github: mosop/string_inflection
    version: 0.2.1

  teeplate:
    github: mosop/teeplate
    version: 0.7.0

  wordsmith:
    github: luckyframework/wordsmith
    version: 0.2.0
</details>

**Comment by paulcsmith** [comment]
@volodymyrgreen It looks like you are using Lucky master, which is the problem. Did you purposely set the branch to master or was it generated like that? If not maybe you are on Linux and you built the Lucky CLI did you checkout the tag: `git checkout v0.13.2` before building?

**Comment by paulcsmith** [comment]
I'm going to close this for now because I don't believe it is a bug, but feel free to continue to leave comments here so we can get this sorted out for you :)
