### ISSUE TITLE
Improve development log output

### ISSUE THREAD

**Issue by volodymyrgreen** [luckyframework/lucky#744]
Would be nice to have some space between log messages(like Rails logger does). 
It might improve log readability for some people.

For instance:
<details>
<summary> Current development log output</summary>

GET /
 ▸ Handled by Home::Index
 ▸ Ran protect_from_forgery
 ▸ Ran test_backdoor
 ▸ Rendered Lucky::WelcomePage
 ▸ Sent 200 (606.0µs)
GET /
 ▸ Handled by Home::Index
 ▸ Ran protect_from_forgery
 ▸ Ran test_backdoor
 ▸ Rendered Lucky::WelcomePage
 ▸ Sent 200 (1.41ms)
</details>

<details>
<summary>Output with space between messages</summary>

GET /
 ▸ Handled by Home::Index
 ▸ Ran protect_from_forgery
 ▸ Ran test_backdoor
 ▸ Rendered Lucky::WelcomePage
 ▸ Sent 200 (606.0µs)

GET /
 ▸ Handled by Home::Index
 ▸ Ran protect_from_forgery
 ▸ Ran test_backdoor
 ▸ Rendered Lucky::WelcomePage
 ▸ Sent 200 (1.41ms)
</details>

**Comment by paulcsmith** [comment]
Great idea! Working on that now
