### ISSUE TITLE
Update Lucky to use new HTTP::Status

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#747]
Crystal just had [this commit](https://github.com/crystal-lang/crystal/commit/b42631e9b3c62621f42832755427d530c6e452d2) which adds in an `HTTP::Status` enum. Lucky [has this defined](https://github.com/luckyframework/lucky/blob/master/src/lucky/action.cr#L20), but it's missing my favorite status 418. I think we should just use the built in crystal one after crystal 0.28.0 is released.

The cool thing too, is the next version of crystal will give us compile time deprecation notices. I haven't tried this, but I think we could do something like:

```crystal
@[Deprecated("Lucky::Action::Status deprecated, please use HTTP::Status instead")]
alias Status = HTTP::Status
```

**Comment by jwoertink** [comment]
Ok, so this one might be a little tricky. It's not as simple as just doing an alias because of the casing, and crystal enums treat different casing as different values. 

Also, apparently the `@[Deprecated]` annotation only works on methods. As far as I know, there's not a way to log out a deprecation warning when calling individual enums. 

So my suggestion is to hard flip these over. It would be a complete breaking change; however, we changed the mime type thing that was also a breaking change anyway.

**Comment by paulcsmith** [comment]
@jwoertink I think a full breaking change is a-ok. We'll do it in a new release so people can upgrade when they are ready 👍
