### ISSUE TITLE
Checking a request type in actions

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#759]
When you're inside an action, you have access to [these methods](https://github.com/luckyframework/lucky/blob/master/src/lucky/content_type_helpers.cr). One issue though is that these currently look for `Content-Type` header only. This works great in an API where you require a `Content-Type` to be passed, but from my recent findings, browsers don't pass this header with the request. That header is more for the response.

This means, doing this fails:

```crystal
route do
  if html?
    render(Home::Index)
  else
    raise Lucky::RouteNotFoundError.new(context)
  end
end
```

When I visit this page in both firefox, and chrome, here's the `headers` I have available:
```
HTTP::Headers{"Host" => "localhost:3001", "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0", "Accept" => "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language" => "en-US,en;q=0.5", "Accept-Encoding" => "gzip, deflate", "Referer" => "http://localhost:3001/about", "DNT" => "1", "Connection" => "keep-alive", "Cookie" => "_session=abc123...", "Upgrade-Insecure-Requests" => "1", "Pragma" => "no-cache", "Cache-Control" => "no-cache"}
```

My thought is we can look at the accept header first then fallback to content-type after then finally an empty string. However, in doing this, it changes the logic a bit of how these are determined. If you look at my `Accept` header above, HTML is `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`. This means more of a regex approach would be needed. The other thing is I feel like with an html request, `html?` and `xml?` should both return true, but for an xml request `html?` would be false, and `xml?` would be true.

**Comment by paulcsmith** [comment]
I didn't quite have time to read this all (feeling sick) but I have some code from another project= that should handle this I think

```
module Lucky::VerifyContentType
  macro included
    before verify_content_type
  end

  abstract def accepted_content_types

  def verify_content_type
    content_type = request.headers["Content-Type"]?

    if content_type.nil? || content_type == "*/*"
      content_type = accepted_content_types.first
      context.request.headers["Content-Type"] = content_type
    end

    if accepted_content_types.any? { |accepted_type| content_type.starts_with?(accepted_type) }
      continue
    else
      raise Lucky::ContentTypeNotAcceptedError.new(content_type, accepted_content_types)
    end
  end
end

class Lucky::ContentTypeNotAcceptedError < Lucky::Error
  def initialize(content_type : String, accepted_content_types)
    super <<-TEXT
      '#{content_type}' is not an accepted content type.

      Here are the accepted formats: #{accepted_content_types.join(", ")}
    TEXT
  end
end

```

Used like this:

```
abstract class ApiAction < Lucky::Action
  # Include modules and add methods that are for all API requests
  include Lucky::VerifyContentType

  def accepted_content_types
    {"application/json"}
  end
end

```

But of course can/should be used in BrowerActon too with "text/html" first

**Comment by jwoertink** [comment]
I like this; however, it looks like when the content_type is nil (which is seems to always be in a browser), then you're going to force in the first one (most likely being `text/html`). That means that if you're making an XML request, then you're shoving in the wrong content type and checking against it.

But get feeling better first. No rush on this one. I have a "hack" in place that works for now.
