### ISSUE TITLE
Running database migrations in production

### ISSUE THREAD

**Issue by ld100** [luckyframework/lucky#768]
What is the way to run migrations in production? There are absolutely no docs available on this topic on Lucky Framework site, so I've done things according to my understanding, but something went wrong:

1. I build and run the main application from src and run it (success)
2. I build and run tasks.cr as a tool to create/migrate/seed database (success)
3. I create the database `tasks db.create` (success)
4. I try migrating the database  `tasks db.migrate` (failure)

Getting following error message:
Unhandled exception: Unable to connect to the database. Please check your configuration. (Exception)
  from /usr/src/app/lib/avram/src/avram/tasks/db/migrate.cr:7:5 in 'call'
  from /usr/src/app/lib/lucky_cli/src/lucky_cli/runner.cr:27:9 in 'run'
  from /usr/src/app/lib/lucky_cli/src/lucky_cli/runner.cr:14:3 in '???'
  from /usr/share/crystal/src/crystal/main.cr:47:14 in 'main'
  from ???
  from ???
  from ??

Using Crystal 0.27.2 and Lucky 0.13.2

Please help.

**Comment by paulcsmith** [comment]
Hi there @ld100. You are doing things correctly, but it looks like the database settings in config/database.cr are incorrect (`Unhandled exception: Unable to connect to the database. Please check your configuration`). This likely means the `DATABASE_URL` is missing or incorrect, but it is hard to tell since I do not know what your `config/database.cr` looks like, but that is almost certainly the issue. The reason `create` worked is that it uses `createdb` under the hood which does not require the database url, running and connecting to the database does though. That is why migrate failed

**Comment by ld100** [comment]
Thanks @paulcsmith 
Could you please look on my database config and tell if something is wrong?
https://gist.github.com/ld100/dac7de3038771ae86e14ca95e89312fd

The thing is that I do not use DATABASE_URL, instead I take postgres host, port, name and password from environment variables and set it in unified way for all of environments. The thing is that it works totally fine in dev environment, but not on production.

**Comment by paulcsmith** [comment]
@ld100 Your config looks ok, but maybe your environment variables are incorrect or not set right. I would try printing them out to see what they are and make sure it is correct

```crystal
# Add this in config/database.cr
pp! ENV["DB_HOST"]
pp! ENV["DB_PORT"]
# And any other ENV var. Or `pp! ENV` to print them all
```

**Comment by ld100** [comment]
@paulcsmith I've double checked everything and it looks fine. E.g. I'm able to log into Postgres via psql command using same environment variables as credentials and host.
So far I think the only difference between development and "production" environments I have is the execution environment. In dev I run Lucky inside Debian-based docker container (based on official Crystal 0.27.2 image), however for production I build 2 binaries (and some helper shell-script) and run within alpine linux based Docker container, just attached its configuration to the Gist: https://gist.github.com/ld100/dac7de3038771ae86e14ca95e89312fd#file-dockerfile

Do you think it is possible there are some external libraries required by Lucky or Crysatal PG (despite the fact I've compiled the app with --static flag), that are not available in my production environment?
Sorry if the question is stupid, but what is the best way for me to debug this thing on production to find exactly which step is faulty?

**Comment by ld100** [comment]
@paulcsmith My concerns were true. I've just tried using the official Crystal docker image with the same set of dev libraries installed instead of Alpine Linux one for production and it worked fine. Turns out the issue with the environment, which was "masked" by Avram.

**Comment by paulcsmith** [comment]
I'm so glad you got it working! Feel free to hop on https://gitter.im/luckyframework/Lobby if you run into anything else
