### ISSUE TITLE
How to use select_input with 'multiple' attribute

### ISSUE THREAD

**Issue by isev-general** [luckyframework/lucky#777]
Hi,

First thanks for making this cool framework, I've really enjoyed using it!

My issue is with a many-to-many relationship and using a select field with the `multiple` attribute to assign many associations to one model.

I have the many to many relationship set up fine, the issue is with generating HTML/Form to save the associations.

I could not figure out from the docs how to do this, but this is what I have so far:

```crystal
# In my pages
select_input f.category_ids, name: "article:category_ids[]", multiple: "multiple" do
  options_for_select(f.category_ids, categories_for_select)
end

private def categories_for_select
  @categories.map do |category|
    {category.name, category.id}
  end
end
```

I was thinking that if I set up a virtual field called category_ids, and then parsed this data in an after_save hook, that would be a simple solution. Unfortunately I don't think it's possible

```crystal
# this is what I'm trying to do
class ArticleForm < Article::BaseForm
   after_save sync_categories
  virtual category_ids : Array(Int32)

  def sync_categories(article : Article)
    # do relationship syncing here
  end
end
```

It seems it's not possible to create a virtual field that's an array of integers. 

Is there a way to do this that I've missed in the docs?

**Comment by jwoertink** [comment]
Hey, sorry for such a late response. Not sure if you figured this out yet or not, but I think this is just a bug. I tried to do this myself, and also ran in to the same issue.

I'll be digging in more to figure out how to handle this as well as looking at writing some better docs around this. If you do happen to find a solution before I get to it, please post here. Thanks!

**Comment by acoustep** [comment]
Hi @jwoertink not a problem :)

I have not come up with a proper solution but I do have a hacky one. So I'd definitely be interested to see how to implement this properly.

If anyone is interested in my hacky work-around, I'm using Javascript to sync the selected items to a hidden input field with commas separating the selected IDs. In my Lucky Form I have a virtual field with the same name as this hidden input, which accepts a String. I then use an after save web-hook to split the string, and sync the many-to-many relationship.

**Comment by akadusei** [comment]
Will adding something like this to *Lucky* help?:

```crystal
module Lucky::SelectHelpers
  def options_for_multi_select(
    field : Avram::Attribute(Array(T) | Nil),
    select_options : Array(Tuple(String, T)),
    **html_options
  ) : Nil forall T
    select_options.each do |option_name, option_value|
      attributes = {"value" => option_value.to_s}

      is_selected = field.value && attributes["value"].in?(field.value.not_nil!)
      attributes["selected"] = "selected" if is_selected

      option option_name, merge_options(html_options, attributes)
    end
  end
end
```

I use it myself, but I'm not sure how it applies to this issue.

**Comment by matthewmcgarvey** [comment]
This is connected to https://github.com/luckyframework/lucky/issues/1380
