### ISSUE TITLE
Consider returning a string from time_ago_in_words instead of a text element

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#780]
I was trying to make this code recently:

```crystal
time(
  time_ago_in_words(post.created_at),
  class: "created_at",
  datetime: post.created_at.to_rfc3339,
)
```

However, `time_ago_in_words` returns an `IO` object not a string. If I cast it to a string:

```crystal
time(
  time_ago_in_words(post.created_at).to_s,
  class: "created_at",
  datetime: post.created_at.to_rfc3339,
)
```

it compiles, but it spits out the HTML of the whole page! I believe this is because it's combining with the IO that renders the page so when you turn it to a string you get the whole page's html output. Not ideal 😉 .

What if instead we don't wrap `time_ago_in_words` in a `text` element? That way it can be used in a `time` element, or an `a`, or whatever!

**Comment by paulcsmith** [comment]
Definitely! I think there is even another issue that proposes this. I would happily accept this change. Then it could be used outside HTML too!
