### ISSUE TITLE
Lucky Sentry

### ISSUE THREAD

**Issue by KCErb** [luckyframework/lucky#782]
I can't use `https://github.com/samueleaton/sentry` with Lucky because in `Watch` a top-level module "Based on the sentry shard with some modifications to outut and build process." is using the same name.

It'd be nice if that was renamed to "LuckySentry" or something along those lines.

My use case is that `lucky watch` doesn't quite do what I need, and the lucky version of sentry doesn't allow me to pass `run_args` which means I can only run a "command without spaces".

I really like that build_commands and run_commands are arrays, so I could use `LuckyWatch` if it took some kind of argument for feeding in an array of args for each command.

I would be happy to put together a PR if there is interest:
1. Rename `Sentry` to `LuckySentry` or `Lucky::Sentry`
2. Support a form of run_commands and build_commands that takes, instead of an array of strings, a hash:
`{"command": ["arg", "Args"], "command": ["arg", "Args"]}`
or nested array
`[["command", ["arg1", "args"]], ["command", ["arg1", "args"]] 

whichever of the two you folks thinks sounds better. I lean towards hash myself.

Thoughts? Interest?

**Comment by KCErb** [comment]
Actually, an array of tuples makes more sense to me now that I'm playing around with it:

```
run_commands = [
  {"docker", "exec -ti container_name sh -c "echo lucky"},
  {"docker", "exec -ti container_name sh -c "echo rules"}
]
```

**Comment by KCErb** [comment]
Hmm, the more I think of this, the less I think of it :) I'd close this but I want to give someone a chance to actually read these and respond before I jump to that.

I started working on my PR / patch and realized more and more that Lucky Watch is rather tailored to Lucky, and especially a non-docker, browser-sync, process manager approach. It doesn't seem smart to try to make that flexible. There are plenty of watch/guard/sentry (I was actually quite surprised when I looked it up on awesome crystal) tools out there.

So I'm still in favor of a name change, but not so much in favor of asking the api to handle arrays of run and build commands with args. That crosses the line in my opinion.

**Comment by paulcsmith** [comment]
Ideally lucky watch could add some more options but I think that’d require some other changes in how Lucky CLI pre compiles tasks. 

For now I think renaming is the best solution. That way you can at least use Sentry now. 

Would you be open to doing the rename? If not I’ll try to get that done next week

**Comment by KCErb** [comment]
Yes I can do a rename. If not today then tomorrow I expect.
