### ISSUE TITLE
number_to_currency still writes to IO

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#790]
[this PR](https://github.com/luckyframework/lucky/pull/781) changed a few of the text helpers to return a string as opposed to writing directly to the view IO. The rule is that if the method returns HTML, it should render directly to the view, and if it only returns a plain string, then the method should just return the string.

Looks like [number_to_currency](https://github.com/luckyframework/lucky/blob/master/src/lucky/page_helpers/number_to_currency.cr#L33) is still calling `text` which renders to the view IO, but there's no reason (that I can see) that it should.

**Comment by paulcsmith** [comment]
Yeah that should return a string. Good call!
