### ISSUE TITLE
XML rendering support

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#803]
We already have `json`, so why not just add a nice helper method for `xml`? 

Right now you can do

```crystal
Lucky::TextResponse.new(context, content_type: "text/xml; charset=utf-8", body: string status: 200)
```

but I'm thinking we do something like

```crystal
private def xml(body : String, content_type : String = "text/xml",  status : Int32? = nil) : Lucky::TextResponse
    Lucky::TextResponse.new(context, content_type, body, status: status)
end
```

https://github.com/luckyframework/lucky/blob/master/src/lucky/renderable.cr#L164

The only thing we would need to consider is if that `content_type` should go there. Following along with other examples, it shouldn't; however, XML content types could be `application/rss+xml` if you're building RSS, or you may want to add the charset. Maybe a better solution is all the others allow you to override the content_type?

**Comment by paulcsmith** [comment]
Yeah let's add this 👍 I think if you want to override the content type the method basically works like a `TextResponse`. So maybe we have another method called `send_response` that accepts the body, content_type and status and just delegates it to `Lucky::TextResponse`.
