### ISSUE TITLE
Allow optional parameters in components

### ISSUE THREAD

**Issue by watzon** [luckyframework/lucky#804]
Currently any `needs` parameter that gets included in a Component makes that a required parameter when using `mount`. It would be nice if there was either

- a `wants` macro that defines an optional parameter
- the ability to have it determine that any nillable `needs` parameter is optional

### Example

```crystal
needs user : User?

# or

wants user : User
```

**Comment by paulcsmith** [comment]
I think `needs user : User?` is good so we don't have to introduce a new concept. This kind of matches the behavior of `getter user : User?` where the default is `nil` even though you don't need to specify it. Thank you for opening this!

**Comment by watzon** [comment]
No problem :)
