### ISSUE TITLE
Should we have a comment element?

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#819]
Looking at the [recent change](https://github.com/luckyframework/lucky/blob/c295b1cc0e51623985b5daede698a67ddc8e4a25/src/lucky/mount_component.cr#L39) to how we render in comments for component mounting, I wonder if we want a `comment` tag that can be used in views:

```crystal
comment "start embed wrapper"
div class: "wrapper" do
  #...
end
```

**Comment by edwardloveall** [comment]
Probably not, since that could easily conflict with the concept of a comment on a piece of media, like a blog post. Also, it's probably a code smell to be adding so many comments, but I thought I'd bring it up anyway.

**Comment by jwoertink** [comment]
I thought the same thing when I first added that. Do people still use the IE comments?
```
<!--[if IE 6]>
<![endif]-->
```

I don't even think most devs today know what those are 😛  If they are helpful, then it might not be a bad thing to add with some options for specifying those.

The other thing too could be that we make it so they only render in development by default. Maybe a nice config option for that? We use comments in our HTML for debugging things like geo tags when using VPN and stuff. That would be a lot better than forgetting you added a comment using `raw "<!--"` and then deploying with that.

**Comment by edwardloveall** [comment]
That's true, one of our missions is to catch bugs so that would be nice. I also want to start adding some things that are stripped in production, `flow_id`s being chief among them.

**Comment by paulcsmith** [comment]
I think we should close this because `comment` is such a common name. I can see this causing issues when doing something like this:

```crystal
post.comments.each do |comment|
  comment # Which one!?
end
```

But maybe we can re-open it if we come up with a nice name or use-case? I feel a regular Crystal comment prob makes more sense 99% of the time so not sure this should be added  even if we do come up with a name. Thoughts?

**Comment by edwardloveall** [comment]
Agree. Until we have a real use-case for it I don't think we should add it. Worse case right now someone can use `raw`, correct?

**Comment by paulcsmith** [comment]
Yep! That’s what we do when adding a comment for showing which component was rendered
