### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by allenjd3** [luckyframework/lucky#826]
I'm wondering, what is the best way to deploy to digital ocean or aws? Do you use crystal cli to make a binary and then have the server load it on startup? Would you need something like nginx to proxy the requests? Heroku can get expensive as you grow. 

Thanks for the help!

**Comment by jwoertink** [comment]
My app is on elastic beabstalk using docker. We ran in to issues with the whole crystal cross compilation stuff, and we develop locally on mac. So the way our deployment works is
* Build docker container locally
* create release build of lucky app `crystal build --release src/my_app_name.cr`
* put binary and required files (i.e. Dockerrun.aws.json) in to temp dir
* zip up EB files in to app.zip
* use `eb deploy --label $LABEL` to deploy app
* post deploy cleanup

If we had the cross compilation stuff working (or developed on linux directly), then the first 3 steps would go away. You don't need nginx sitting in front of it, but if you're not going to run docker, then it may help so you can do things like throttle requests, or add open resty for auto SSL certs.

The main things are 
* Get crystal installed on the server
* create a release binary
* boot the binary on your port, and do your server setup stuff

That's really it.

**Comment by allenjd3** [comment]
Do you need any sort of process manager? Sorry for the potentially dumb questions- I'm not really familiar with the crystal language

**Comment by jwoertink** [comment]
That depends on what your app does. If it's just a single process, then no. It would be assumed that your assets are built prior to going to production. So you wouldn't boot a second process for assets. 

Now, if your app requires a worker like sidekiq or something, then you'd need to build and boot that separately. You could use a process manager in production for that if you wanted, but not necessary if you just boot and daemonize each process.

**Comment by paulcsmith** [comment]
We now have a guide for deploying to Ubuntu servers :D https://luckyframework.org/guides/deploying/ubuntu
