### ISSUE TITLE
Beef up responsive meta tag

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#828]
We have this cool method 

https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/specialty_tags.cr#L40

But the viewport meta tag has a lot [more options](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag#Viewport_basics). We should have this method take some options to update things like `user-scalable`, `minimum-scale`, and `maximum-scale`.

**Comment by smadeja** [comment]
I've created [this little draft](https://github.com/smadeja/lucky/commit/1fd8eac1a64712e64f35e9491ba5e8204035bb87). What do you think?

**Comment by jwoertink** [comment]
That looks good @smadeja. You can submit the PR and we can look over it. Thanks!
