### ISSUE TITLE
Own process runner

### ISSUE THREAD

**Issue by deepj** [luckyframework/lucky#830]
Hello,
I wanted to give Lucky framework a try the but I was stopped in the step of the process runner installation on macOS.

I'm not happy I'm forcing to install another 3rd party tool and there is no way to not use them.

1. Overmind - I'm forcing to install tmux which I don't use and it's useless to be installed on my system
2. Forego - I have to install Go which I don't use at all
3. Heroku CLI - I don't use Heroku at all

Will Lucky have own native process runner in the future?

**Comment by paulcsmith** [comment]
Sorry this has been such an issue to get started. We may have a process runner in the future but it will be a bit. 

If you don’t mind opening two terminal tabs you can run “lucky watch” in one and “yarn dev” in the other

Or if using API mode you can use just “lucky watch”!

**Comment by paulcsmith** [comment]
I’ll close this for now and revisit once we have more time to tackle something like this

**Comment by paulcsmith** [comment]
Note: we could possibly fork this and improve it https://github.com/arktisklada/crank then bundle with Lucky CLI or something
