### ISSUE TITLE
csrf_meta_tags issue with context

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#831]
The `Shared::LayoutHead` component needs the `context` when it's mounted; however, if you look at the component class, there's no mention of actually using the `@context`, so at first glance it seems it's not needed. 

Then if you remove the needs, and don't include it, you get an error saying it can't determine the type of `@context` when passing to [this method](https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/forgery_protection_helpers.cr#L23). 

This can lead to some confusion (as it did for me just now when migrating to new class based components from older modules). My first thought was "oh, components need to have context passed always?" Then I read the error a little more and dug into the code and saw it's because the `csrf_meta_tags` method requires it. Maybe this is just documentation? Maybe we pass context in to that method? Or maybe it's just me and not really a thing? lol

**Comment by paulcsmith** [comment]
Yeah let’s make it explicit and pass context into those methods so it’s clear it is needed! Good catch

**Comment by paulcsmith** [comment]
Closing in favor of this issue https://github.com/luckyframework/lucky/issues/836. Thanks for bringing this up. I think this'll definitely help make things clearer!
