### ISSUE TITLE
The exception page info is slightly off in development

### ISSUE THREAD

**Issue by smadeja** [luckyframework/lucky#846]
This should say "Error 500":

![Screenshot 2019-07-09 at 22 30 50](https://user-images.githubusercontent.com/3882931/60920880-806f8900-a299-11e9-8823-6d51f5a0b162.png)

And I'd expect to see something like `http://localhost:3001/articles/` here:

![Screenshot 2019-07-09 at 22 42 44](https://user-images.githubusercontent.com/3882931/60921489-ec062600-a29a-11e9-8c27-efd8fb499c8a.png)

**Comment by paulcsmith** [comment]
This should be fixed in the next release. Thanks for reporting!
