### ISSUE TITLE
cache, cache-invalidation, in-browser cache+rendering, and live (reactive) DOM element updates

### ISSUE THREAD

**Issue by testbird** [luckyframework/lucky#851]
Ok, steep topics, but can it be made a valley opening... maybe?

I could not find anything about caching. So I thought if that is still on the todo, maybe consider choosing a solution that can --at the same time-- also "render" many other beneficial side effects.

Implementation is clearly above my head, but I think having the HTML DSL could have turned solving several hard problems into a much softer integration problem, for which prior art exists.

Idea:
* Mark changed HTML element instances (maintain cache invalidation tree).
* Execute the same code in browser (transpiled to javascript https://opalrb.com).
* Same invalidation info can be used for reactivity of selected dom elements.
* Unclear: Websocket to pass and sync data between client and server. Prior art looks like having Implemented this in the framework or ORM, but without any offline capability. So alternatively, to make this a soft problem, maybe just dynamically start up one CouchDB per user on the server and load a PouchDB .js in the browser, and let them sync up over a lucky-controlled? websocket (Still "isomorphic" code runs on both sides, communication is turned into DB writes and callbacks on both sides.)

=> Changes can be pushed both ways between client-and-server and other clients. (Even the js-version of the app code could be passed over the DB sync to allow hot-fixes without a full URL cache invalidation.)
=> The server can still render and deliver static and dynamic pages, files, etc.
=> The html may load a "client-worker" .js that loads the DB and parts of the site into the local browser cache, allowing for offline-viewing **and** -operation of the site as a "progressive web app" (PWA).

Existing code:

#### Overview (taken from the unmaintained http://voltframework.com)

Volt is a Ruby web framework where your Ruby code runs both on the server and the client (via opal.) The DOM automatically updates as the user interacts with the page. Page state can be stored in the URL. If the user hits a URL directly, the HTML will first be rendered on the server for faster loading and easier indexing by search engines.

Instead of syncing data between the client and the server via HTTP, Volt uses a persistent connection between the client and the server. When data is updated on one client, it is updated in the database and any other listening clients (with almost no setup code needed).

Pages HTML is written in a template language where you can put ruby between {{ and }} . Volt uses data flow/reactive programming to automatically and intelligently propagate changes to the DOM (or any other code wanting to know when a value updates). When something in the DOM changes, Volt intelligently updates only the nodes that need to be changed.

EDIT:
Some "=> features" above.
More elaborate article explaining some concepts: https://medium.com/@mitch_23203/the-exact-same-app-in-hyperstack-7f281cef46ca

**Comment by matthewmcgarvey** [comment]
Both of the examples you listed (opal and volt which uses opal) are intense codebases that transpile ruby into javascript. Maybe someone is doing something like that for crystal, but our team how no plans on doing this sort of thing for Lucky. We are invested in making a backend framework and server side rendering using Crystal.

These ideas sound interesting, so if you are invested in crystal, I'm sure you could find people to help you make something like that!
