### ISSUE TITLE
Exposing params via `needs` is not congruent

### ISSUE THREAD

**Issue by mwlang** [luckyframework/lucky#853]
In the Pages, we access params with "@" whereas in the Action, we access params without the leading "@".    This incongruence leads to extra effort on developer to remember when "@" is required and when not.

For example:

In the Action:
```crystal
class Charts::Folder < BrowserAction
  include Auth::AllowGuests

  get "/charts/:folder" do
    render FolderPage, folder: folder
  end
end
```

In the Page:
```crystal
class Charts::FolderPage < PublicLayout
  needs folder : String

  def content
    h1 "Folder #{@folder}"
    # ...
  end
end
```

The `needs` directive should expose params so as to not need the leading "@" and the Page definition would become:
```crystal
class Charts::FolderPage < PublicLayout
  needs folder : String

  def content
    h1 "Folder #{folder}"
    # ...
  end
end
```

**Comment by paulcsmith** [comment]
This is also confusing because in Operations we generate a getter. We should definitely create a getter for needs in operations as well

https://gitter.im/luckyframework/Lobby?at=5db8858e2f8a034357fc578f
