### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#868]
Supersedes #500 

https://gist.github.com/paulcsmith/7f9099ee46f41dc3bdfaa62ab1070ebd

## Problem

* A decent amount of duplication: https://github.com/luckyframework/lucky_cli/blob/d439b9c7e3c9e8817a25cf7c5fd66e03ec7646d9/src/web_app_skeleton/src/actions/errors/show.cr.ecr#L1
* No easy way to report errors
* Sometimes  we don't want to debug certain errors. Right now there is not a built-in/easy way to do that

## Solution

```crystal
class Errors::Show < Lucky::ErrorAction
  default_format :html
  dont_report Lucky::RouteNotFoundError 
  
  # This handles a lot of the default Lucky errors, and any errors you add `Lucky::RenderableException` to
  def render(error : Lucky::RenderableException)
    if html?
      render Errors::ShowPage, status: error.status_code, title: error.error_message
    else
      json ErrorSerializer.new(message: error.error_message), status: error.status_code
    end
  end
  
  def render(error : Exception)
    if html?
      render Errors::ShowPage, status: 500, title: "Something went wrong"
    else
      json ErrorSerializer.new(message: "Something went wrong"), status: 500
    end
  end
  
  def report(error : Exception)
    # Send an email, use Rollbar, etc.
  end
end
```

## `Lucky::RenderableException`

You can extend classes with this module to automatically have Lucky handle them

```crystal
class MyException
  include Lucky::RenderableException

  def status_code
    418
  end
  
  def error_message
    "I am a teapot!"
  end
end
```

**Comment by paulcsmith** [comment]
@jwoertink thoughts?

**Comment by jwoertink** [comment]
This is pretty much what I'm doing in my apps now. Looks like a companion to https://github.com/luckyframework/lucky/issues/500

My actual handler:

```crystal
class Lucky::BugsnagHandler < Lucky::ErrorHandler
  EXCLUDED_ERRORS = [Lucky::RouteNotFoundError, BrowserAction::RecordNotFound]

  def call(context : HTTP::Server::Context)
    call_next(context)
  rescue error : Exception
    send_report(context, error) if Lucky::Env.production?
    call_error_action(context, error)
  end

  # Skip error classes we created and call on purpose.
  private def send_report(context, error)
    return if EXCLUDED_ERRORS.includes?(error.class)
    Bugsnag.report(context, error)
  end
end
```

**Comment by paulcsmith** [comment]
Cool :) Well I'm glad it is battle tested!

I think the other part of this is moving the html/json checks to a single method instead of having to do it in every method. Thoughts on that?

**Comment by paulcsmith** [comment]
And yeah #500 could probably be closed with this. I'm thinking having that report method should be plenty. Then you can report however you want, even if a lib has no "Lucky" support. You just give it whatever you want.

**Comment by jwoertink** [comment]
Doing the content type check should for sure move someone. I submitted this https://github.com/luckyframework/lucky_cli/pull/323 a while ago because in json it would still try to render the page. But we want to make sure the exception page is basically off when you're in api mode.

**Comment by paulcsmith** [comment]
I'm working on improving the accept headers which should tackle part of that #822. The other part of this is that we should still render some debug info, but we should do it as JSON. So I think we should add a `Lucky::ErrorDebugSerializer` that we can call. It'd render a simple stack trace and the error message. And if you don't want that you can change it to something else in n`Errors::Show`
