### ISSUE TITLE
Bash in built-in tasks ?

### ISSUE THREAD

**Issue by waghanza** [luckyframework/lucky#878]
Hi @paulcsmith,

The `shebang` in 
https://github.com/luckyframework/lucky/blob/95361062b9ec143356add4714d12e9eff6005e61/script/precompile_tasks#L1
assume `bash` interpreter is installed

This break compilation, for example on **alpine** ?

Are `bash` feature really necessary here ?

Regards,

**Comment by jwoertink** [comment]
Hey, thanks for reporting!

We actually did try to remove the bashisms in a few of the projects [ref1](https://github.com/luckyframework/lucky_cli/pull/362#issuecomment-514257906), [ref2](https://github.com/luckyframework/avram/pull/142). Taking a look at that script, it looks like there's no pipes being used, so the `pipefail` is pointless in this case; however, there are other cases where it's not. 

It's possible to replace the pipefail with a bashless alternative, but it leaves us open to possible issues with regards to needing a way to run specs against custom shell functions that are complex. 

I would love to be fully shell compliant on all scripts. If you have some suggestions on how we can do this, we'd love to hear it.

**Comment by j8r** [comment]
That's not that problematic, usually `set  -eu` is fine. There are mitigations like checking the return value of the pipe command.
If you really want to know the exit core of cmd1 in `cmd1 | cmd2`, there are POSIX alternatives.

**Comment by jwoertink** [comment]
@j8r The only POSIX alternative to `-o pipefail` I found was in [this answer](https://stackoverflow.com/questions/13084352/how-to-implement-set-o-pipefail-in-a-posix-way-almost-done-expert-help-nee), but that's not a solution we want to implement. Do you happen to know a better alternative? We'd like to move it over on all our scripts, but so far that's the only major thing that's holding us back. 

Thanks for the help!

**Comment by j8r** [comment]
No @jwoertink, sorry, What scripts really need `pipefail`?
In my experience, this can often be mitigated by other means, like checking the content of the variable. And also this is not rare that a failing command make the one after the pipe fails, too.
