### ISSUE TITLE
Support HTTP PATCH just like PUT and DELETE

### ISSUE THREAD

**Issue by oneiros** [luckyframework/lucky#884]
Coming from rails I have learned to prefer PATCH over PUT. lucky already supports this somewhat:

* You can use the `patch` route helper in your actions.
* The `link` helper will generate the correct `data-method` attribute.
* Rails-UJS takes care of sending a POST request with the `_method` parameter.

When the request arrives in lucky, it will not work, though. PATCH is currently not allowed as a method override and thus POST will be assumed for this request. The relevant code is here: https://github.com/luckyframework/lucky/blob/b69d163a097d2ee83142142ba0aa177502c771fe/src/lucky/http_method_override_handler.cr#L15

In my case this failed more or less silently. I suspect that if there is a matching route with POST even more confusing things could happen.

I would like to see PATCH fully supported just like PUT and DELETE. In fact I already prepared a PR I am happy to send, if you agree.

But I also understand if you want to keep the list of supported HTTP method overrides to a minimum.

**Comment by paulcsmith** [comment]
Hi @oneiros I think you're right that we should also allow `PATCH` as a method override. Happy to accept a PR to add that!

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky/pull/885

Thanks!!
