### ISSUE TITLE
Pluralize doesn't take Int64

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#887]
If you use [select_count](https://github.com/luckyframework/avram/blob/master/src/avram/queryable.cr#L142), it will return `Int64`, but passing that to `pluralize` will throw 

> no overload matches 'SomePage#pluralize' with types Int64, String

https://github.com/luckyframework/lucky/blob/master/src/lucky/page_helpers/text_helpers.cr#L89

My guess is we should probably also support `Int16`. Maybe we just have a few overloads that convert the type, and pass to a main method?

**Comment by paulcsmith** [comment]
Nice catch. I think we could use a union type there so it accepts all the Int types

**Comment by vnbrs** [comment]
Would it be bad to just accept [`Int`](https://crystal-lang.org/api/0.23.1/Int.html)? That would cover the following types: `BigInt`, `Int16`, `Int32`, `Int64`, `Int8`, `UInt16`, `UInt32`, `UInt64`, `UInt8`

**Comment by paulcsmith** [comment]
Yeah that’s a great idea!
