### ISSUE TITLE
Simplify serializers

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#893]
Rather than creating an `IndexSerializer` and a `ShowSerializer`, I propose that we generate a `BaseSerializer` with an `array_of` method that handles generating an array of items. That way the user just needs to create one serializer and can call `MySerializer.array_of(items)`

```crystal
# This is auto-generated with your Lucky app
# src/serializer/base_serializer.cr
abstract class BaseSerializer < Lucky::Serializer
  def self.array_of(objects : Enumerable, *args, **named_args)
    objects.map do |object|
      # Pass extra args. So if you have a serializer with `initialize(@todo, @current_user)` you could do:
      # MySerialize.array_of(todos, current_user: current_user)
      new(object, *args, **named_args)
    end
  end
end

class ArticleSerializer < BaseSerializer
  def initialize(@user : User)
  end

  def render 
    {name: @user.name}
  end
end

ArticleSerializer.new(@user) # Just one

# One of these
ArticleSerializer.array_of(@users)
ArticleSerializer.for_collection(@users)
```

**Comment by paulcsmith** [comment]
Would love to hear your thoughts on this @edwardloveall @jwoertink

**Comment by jwoertink** [comment]
I have so many serializers that are literally just doing that same thing 😂

**Comment by paulcsmith** [comment]
So you're saying you like this idea? :P

**Comment by jwoertink** [comment]
yup. Current code I use:

```crystal
class Sites::IndexSerializer < Lucky::Serializer
  def initialize(@sites : SiteQuery)
  end

  def render
    @sites.map do |site|
      Sites::ShowSerializer.new(site)
    end
  end
end
```

**Comment by paulcsmith** [comment]
Yeah I think this is the way to go. And of course you don't have to use it if you've got some crazy stuff going on. That's the benefit of plain old classes :D So I think this is a good tradeoff of simplicity and flexibility

**Comment by edwardloveall** [comment]
Yeah that's great. Weird, nitpicky question: is `array` the right word? Is it technically an array or an an Enumerable? Would `collection_of` be better? `list_of`? `array_of` is totally fine also, I just like getting into semantics.

**Comment by paulcsmith** [comment]
I went back and forth on that a lot and in the end thought `array_of` was most intuitive even if it may not be 100% correct. I also  thought of `many` which is a bit more generic. `ArticleSerializer.many(users)` but I feel like it is *too* abstract. Thoughts?

**Comment by jwoertink** [comment]
I think `array_of` would be correct since `map` returns an array.

**Comment by jwoertink** [comment]
`ArticleSerializer.collection(@articles)` I think would be ok too

**Comment by edwardloveall** [comment]
Yeah `many` doesn't quite feel right. Looking through the thesaurus, we could also do `ArticleSerializer.horde_of(@articles)` which could be fun.

**Comment by jwoertink** [comment]
![](https://media.giphy.com/media/xThtatRttFzLD9oEtG/giphy.gif)

**Comment by paulcsmith** [comment]
We should also have `murder_of` so if  you are serializing crows you can use proper English

But seriously, I think `array_of` is the most intuitive. Technically you can pass a query object which is enumerable and not an Array but it returns an array so I think still  works.

**Comment by paulcsmith** [comment]
We can also debate more in the PR. I personally like `array_of` and `collection` of all the options so far

**Comment by vlazar** [comment]
In `representable` gem there is `for_collection` method http://trailblazer.to/gems/representable/3.0/api.html#automatic-collection-representer

**Comment by paulcsmith** [comment]
Thanks for the links @vlazar I like `for_collection` over just `collection`, but not totally sure if I like it over `array_of`, partly because of length. What are you thoughts @edwardloveall @jwoertink ?

**Comment by edwardloveall** [comment]
I think I'm about where you are @paulcsmith, but _just_ on the other side of the fence. I prefer `for_collection` over `array_of`. Length doesn't bother me as much as "correctness", but I feel 49/51% about it.

**Comment by paulcsmith** [comment]
I kinda feel the same and am flip flopping. I took this to Gitter/Twitter to see if we can get some other thoughts on it!

**Comment by vlazar** [comment]
What do you guys about single method for automatic `singular` / `collection` serializer like the one in http://trailblazer.to/gems/representable/3.0/api.html#automatic-singular-and-collection ?

**Comment by paulcsmith** [comment]
I think in dynamic languages that is a good idea, but in Crystal I'd rather have the added protection of dedicated methods for each. This also makes it easier to handle a collection different than a single resource. 

Here's an example of how  having dedicated methods would catch a potential bug:

```crystal
class UsersWithEmail::Show < ApiAction
  get "/user_with_email/:email do
     user = UserQuery.new.email(email)
     UserSerializer.represent(user)
  end
end
```

This would compile but since I didn't call `first` it will render a collection. This kind of thing happens and can be annoying to debug. By having an explicit `for_collection` method and `new` for single resource we would get a nice error saying that it expects a `User` but got a `UserQuery`
