### ISSUE TITLE
Add link to migrations guide in generated migrations

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#915]
https://github.com/luckyframework/lucky/blob/0a7596184a3f13e45e14f2359a3149b4e20aea4f/tasks/gen/model.cr#L33

**Comment by citizen428** [comment]
@paulcsmith Can you elabore a little bit?

**Comment by jwoertink** [comment]
When we generate a migration, there should be a block comment that points you to visit https://luckyframework.org/guides/database/migrations so that way you have a quick reference to get started.
