### ISSUE TITLE
Time.utc is not the best option for time measure

### ISSUE THREAD

**Issue by aniliyidogan** [luckyframework/lucky#927]
When I was researching how to make time measurements better in Ruby, I came across an article: https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/

A similar situation occurred when I was using Lucky and I started to examine the code. I saw that Time.utc was being used. Then in the API, I came across: https://crystal-lang.org/api/0.31.1/Time.html#monotonic:Time::Span-class-method

I'd like to make a change.
https://github.com/luckyframework/lucky/blob/master/src/lucky/log_handler.cr#l13

**Comment by jwoertink** [comment]
This is a good point. We should actually be using [Time.measure](https://crystal-lang.org/api/0.31.1/Time.html#measure(&block):Time::Span-class-method)

**Comment by aniliyidogan** [comment]
Thank you for your quick reply @jwoertink . Yeah, Time.measure came to mind. But I think it should be included in this line: https://github.com/luckyframework/lucky/blob/master/src/lucky/log_handler.cr#L14 This is a process. What do you think?

**Comment by jwoertink** [comment]
I'm thinking something like:

```crystal
def call(context)
  should_skip = settings.skip_if.try &.call(context)
  time = Time.measure do
    log_request_start(context) unless should_skip
    call_next(context)
  end
  log_request_end(context, duration: time) unless should_skip
rescue e
  log_exception(context, time, e)
  raise e
end
```

This is untested, but my initial guess would be to try out something along these lines. Maybe @paulcsmith would have some insight?

**Comment by aniliyidogan** [comment]
Time is using in the rescue block, it may be written directly as Time.utc in the block. But some arguments are not used in the log_exception method. I don't understand.

**Comment by paulcsmith** [comment]
Hey @aniliyidogan Sorry for the late response! I've gotten  lot of emails and did not notice this!

Morre accurate measurement would be *awesome*. Could you open a PR using `Time.monotonic` like you originally proposed? I think what you proposed would work!

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky/pull/944#issuecomment-541527288 thanks @aniliyidogan
