### ISSUE TITLE
Context is reset before it's passed to exception page

### ISSUE THREAD

**Issue by bdtomlin** [luckyframework/lucky#933]
In development with the `Lucky::ErrorHandler` set to debug (show_debug_output == true) the status code on the error page always shows 200 and there are other issues as well.

To reproduce, create a new lucky project, run the dev server, then visit http://localhost:3001/hjghgkhg. The response status is correct, but the error code printed to the page is 200.
<img width="762" alt="Screen Shot 2019-10-06 at 9 11 44 AM" src="https://user-images.githubusercontent.com/25921/66270464-9a2d5780-e819-11e9-91e7-ba96c46e8236.png">

I've traced the issue back to here https://github.com/luckyframework/lucky/blob/4fd49c186fba7f5d3f08d8acea5685a725f6dc9b/src/lucky/error_action.cr#L80-L88

I looks like the context is getting reset before it's passed to `Lucky::ExceptionPage.for_runtime_exception`. This causes the status, headers, and cookies to be lost so that the error page can't access them.

Here's a simple fix:

```crystal
def render_exception_page(error : Exception, status : Int) : Lucky::Response
  body = Lucky::ExceptionPage.for_runtime_exception(context, error).to_s
  context.response.reset
  Lucky::TextResponse.new(
    context: context,
    status: status,
    content_type: "text/html",
    body: body
  )
end
```
I would be glad to do a pull request for this bug, but I wanted to have a discussion about handling testing.

It seems like the thing that should be tested is that the `Lucky::ExceptionPage.for_runtime_exception` method receives the original context and not the reset context. That is not easy to test currently. Any thoughts?

Thanks.

**Comment by paulcsmith** [comment]
Thanks for the thoroughly written issue! I’m beginning to think we just shouldn’t reset the context at all. In terms of the spec I think there could be one that passes in a context with a 500 status that is passed to the error action and we test that the status remains the same. But I’m not sure I may need to dig in more. If you want to submit a PR lmk otherwise I may try to tackle it this week!

**Comment by bdtomlin** [comment]
I agree with not resetting the context. If that's the case, we can continue with the theme of the spec and just check the content. I'll create a pull request shortly.

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky/pull/934#issuecomment-538823329
