### ISSUE TITLE
Add HTML parsing to spec helpers

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#94]
Makes it easier to read test output and be more specific about where text is expected

https://github.com/kostya/myhtml or https://github.com/kostya/modest

**Comment by azbshiri** [comment]
I think this helps a lot. Would you explain in more detail and where the hook should be written?

**Comment by paulcsmith** [comment]
@azbshiri great question. I don't have a good place for them yet because I haven't written any spec helpers. I'm still not 100% sure how they should look. There are some really rough ideas here though: #50

**Comment by azbshiri** [comment]
I would like to work on this. But do me a favor and add me to the organization if it's possible.

**Comment by paulcsmith** [comment]
@azbshiri thanks so much for your contributions. I’m so glad you are going to keep working in Lucky. I think it would be good to first start an issue with some proposals for how spec helpers would work for making requests. Just to make sure we’re all on the same page. 

I am going to keep the organization just me and people at thoughtbot for now but I’ll open it up to other core team members later. I’d first like to get to know people better, see what your code looks like, and make sure we’re on the same page in terms of vision for Lucky.

**Comment by matthewmcgarvey** [comment]
This isn't very clear and I've not heard anyone complain about something like this. I'm going to close this. If anyone comes across this issue and relates/understands, feel free to open a new issue 👍
