### ISSUE TITLE
Lucky watch help option is overridden by LuckyCli::Task

### ISSUE THREAD

**Issue by bdtomlin** [luckyframework/lucky#942]
LuckyCli::Task hijacks the help option so if you pass "--help", "-h", or "help" it will never fall through to your options parser:

https://github.com/luckyframework/lucky_cli/blob/a0ac6e52bcb0fd65605019905dd06fdb3e6582fa/src/lucky_cli/task.cr#L19-L30

This is a similar issue that I fixed for lucky exec by overriding print_help_or_call in the task.

https://github.com/luckyframework/lucky/blob/f78fec851478c794a344ef88e77f61542f78b448/tasks/exec.cr#L15-L18

Recap:
When executing `lucky watch --help` it is expected to show the help message from the options parser, but it shows the help message from `LuckyCli::Task`.

---
I think this is an api issue with LuckyCli::Task that should eventually be addressed, but in the meantime, this solves the immediate user experience issue.

**Comment by jwoertink** [comment]
I'm not sure I follow, could you clarify? Those args are for each task to have it's own help option. `lucky gen.model -h`. Are you saying that `lucky watch -h` doesn't work?

**Comment by bdtomlin** [comment]
Sorry, accidentally hit the submit button before finishing. I'm editing it now.

**Comment by bdtomlin** [comment]
@jwoertink, now I'm finished :P

**Comment by jwoertink** [comment]
Ah, I see. I think it might be a good time to start looking in to the task API. Right now it doesn't support args natively. Maybe by a nice refactor, we can add that in along with supporting OptionParser properly. Thanks for reporting!

**Comment by paulcsmith** [comment]
@jwoertink Yeah  I agree. Once we add in some kind of arg parser (it will likely use OptionParser under the hood) we can generate help docs automatically which would resolve this issue.

Thanks for reporting Bryan!
