### ISSUE TITLE
Resource generator should rename `form` to `operation`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#946]
https://github.com/luckyframework/lucky/blob/a3188c7b2f06a1e7f7f7840578c45bfd9f554a07/tasks/gen/templates/resource/pages/%7B%7Bfolder_name%7D%7D/new_page.cr.ecr#L2

Check the other pages in that folder too

**Comment by jwoertink** [comment]
Same here https://github.com/luckyframework/lucky_cli/blob/master/src/browser_app_skeleton/src/components/shared/field.cr#L6 

There's a few mentions of it.
