### ISSUE TITLE
Add --error-trace to lucky watch / lucky dev

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#947]
When running your app through `lucky dev`, there's no way to pass `--error-trace` currently. We need a way to proxy that down to [this command](https://github.com/luckyframework/lucky/blob/master/tasks/watch.cr#L210-L211).

We could have `lucky dev --error-trace` or maybe you just edit your Procfile.dev (which would probably need to happen anyway), and update `lucky watch --error-trace`.

**Comment by InstanceOfMichael** [comment]
any way to see stack traces before this is merged?

**Comment by jwoertink** [comment]
@InstanceOfMichael You can just boot your app with `crystal src/start_server.cr --error-trace`. You just don't get the nice compile watcher, but if you make a change, just kill the server and start back up manually.
