### ISSUE TITLE
Lucky::CookieOverflowError doesn't render the normal error page

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#949]
I've been running in to Lucky::CookieOverflowError a bit on my app. Not sure if it's my app specifically, but instead of rendering the exception page, it just renders plain text `500 Internal Server Error`. Need to figure out if this is always the case or not. If it is, we should make sure it's throwing the normal page.

**Comment by paulcsmith** [comment]
Might be because the cooke handler happens before the error handler in the middleware stack?

**Comment by jwoertink** [comment]
Ah, that could be the case.

**Comment by paulcsmith** [comment]
Yeah looks like a few things come before the ErrorHandler. I’d try moving it up the stack and see if that fixes it! Seems like it should work fine and may be what we should do for all new  projects

**Comment by jwoertink** [comment]
Yup. Moving that up a few spots does fix that. Should it be the first in the stack if that's the case?
```
      Lucky::ForceSSLHandler.new,
      Lucky::HttpMethodOverrideHandler.new,
      Lucky::LogHandler.new,
      Lucky::ErrorHandler.new(action: Errors::Show),
      Lucky::SessionHandler.new,
      Lucky::FlashHandler.new,
      Lucky::RouteHandler2.new,
```

**Comment by paulcsmith** [comment]
Yeah I think so, could you open a PR on LuckyCLI? If that is green then it is probably good to go. We may want to let it bake a bit before merging but I can’t think of a reason for it not to be first

**Comment by vlazar** [comment]
Some thoughts on organizing middleware http://twitchard.github.io/posts/2019-11-01-beware-middleware.html might be of interest (was mentioned in https://github.com/crystal-lang/crystal/issues/8423)

**Comment by skojin** [comment]
Is this issued should be closed?

**Comment by jwoertink** [comment]
Yeah, we can close this for now. Last time I got this error it was fine. Plus, it's easy to reopen issues if they show up again.
