### ISSUE TITLE
Disjointed logging with lots of requests

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#950]
If you have a page that takes a while to load, but also a bunch of async ajax calls on that page, you may see some disjointed logging in development where the calls come in at different times.

Something similar to this
```text
GET /favicon.ico
 ▸ Sent 200 (1.33ms)
 ▸ Sent 200 (721.66ms)
 ▸ Query   SELECT * FROM users

GET /api/reports
GET /dashboard
```

This is most likely because each request is done in it's own thread, and the logging is done on that thread. One solution could be to add a request ID to each log so you can match up which lines go to which request. 

ref: https://gitter.im/luckyframework/Lobby?at=5daab34be3646f24c75192ee

**Comment by jwoertink** [comment]
The new logger fixes this! 🌮 🎉  Good job @paulcsmith

**Comment by jwoertink** [comment]
actually I just checked with a different app and it still does it 😢  It doesn't seem to be as bad, but it's still a bit off.

We make a request to the home page, but then we have 2 asynchronous API calls to get data. It makes sense that they could come in at different times, but as you can see, there's 2 "Sent 200 Ok" under the last one, and no way to know which one belongs there and which belongs to the one above it.

Maybe we need a way for the log to know which request ID it belongs to, and then group them in their request ID. I think rails does something similar 🤔  We just create a new request ID and throw it in the header, then log to that fiber (I'm literally making stuff up at this point). Maybe @bcardiff  has some threading log knowledge to shine some light here?

```
web          | GET /home
web          |  ▸ Handled by Home::Index
web          |  ▸ Rendered Home::IndexPage
web          |  ▸ Sent 200 Ok (6.75s)
web          |
web          | GET /api/sites/network
web          |  ▸ Handled by Api::Network::Index
web          |
web          | GET /api/members/data
web          |  ▸ Handled by Api::Members::Data
web          |  ▸ Sent 200 Ok (720.96ms)
web          |  ▸ Sent 200 Ok (1.77s)
```

**Comment by paulcsmith** [comment]
@jwoertink I think this can be solved by adding `request_id` to the global context in a middleware. Then it will print the request id of each line.

This requires changes to the PrettyLogFormatter to also print the context data and then we can add a super simple `RequestIdMiddleware`. My thought is that it is configurable by Habitat and can be given a proc for setting the request id. It can be `nil` to disable it (I think this should be the default). or give it a Proc where you can generate a UUID, set it based on a header, or in dev use just the last 4 chars of a UUID so it is easier to match them up! `settings.generate_id = ->{  UUID.generate. }`

**Comment by jwoertink** [comment]
Yeah, I like that. I really like the pretty logs, so I'd hate to muddy them up, but having that configurable would be nice to at least see what goes where.

**Comment by bcardiff** [comment]
I think is either:

a) embracing a format that can allow interleaving multiple requests, or

b) having a backend that will serialize the entries. this will need to know when a request is effectively done. Maybe delayed logs can be flagged as so.

**Comment by paulcsmith** [comment]
My concern with buffering logs so they go out at once is then you don’t know when they actually went out unless there is a timestamp. So then you’d have to include a timestamp and check it to see when the actual request started :(

It may also be strange for people with long running requests to not see anything until the request is finished. 

Maybe we can experiment with it though or add it as an option. I think we do a short request ID that may help?

My thought is we try both. Start with the req ID and Then later do a log dump that does it at the end of the request in one big dump lol.

**Comment by jwoertink** [comment]
Almost none of my pages load in under 500ms lol 😂 (see both examples above). I don't see an issue with them being written in bulk. I think in production it shows the time which is fine. I don't think a timestamp is necessary in development. Let's start with a request ID, and that should be good to start
