### ISSUE TITLE
Problems with "with_defaults"

### ISSUE THREAD

**Issue by bdtomlin** [luckyframework/lucky#971]
It looks like there is some holes in the with_defaults API. Currently only named arguments are considered which causes some unexpected behavior.

**Example 1:**
```crystal
with_defaults class: "something" do |html|
    html.div "whatever"
end
```
**Expected:**
```html
<div class="something">whatever</div>
```
**Actual:**
```html
<div class="something"></div>
```
**Workaround:**
```crystal
with_defaults class: "something" do |html|
    html.div content: "whatever"
end
```
---
**Example 2:**
```crystal
with_defaults class: "something" do |html|
    html.div do
      text "whatever"
    end
end
```
**Expected:**
```html
<div class="something">whatever</div>
```
**Actual:**
```html
<div class="something"></div>
```
**Workaround:**
Unknown

**Comment by bdtomlin** [comment]
@jwoertink, I don't think there is any problem with the api, I just hit some bugs that caused some confusion for me. I actually have a pull request that fixes these issues coming shortly.

**Comment by jwoertink** [comment]
Right. I use the "clarify api" tag when something isn't intuitive meaning that we need to clean it up a bit. Not necessarily that the api has to change, but we just need to clarify how it should work better.
