### ISSUE TITLE
Column with Enum type

### ISSUE THREAD

**Issue by manveru** [luckyframework/lucky#976]
At the moment it seems pretty hard to have columns that use [ENUM](https://www.postgresql.org/docs/current/datatype-enum.html) while also mapping them to enums in Crystal in a type-safe way.

I tried following code: https://gist.github.com/manveru/b339952ae22b4050f795232bc620b68a
And it resulted in this error:

```
web    | 
web    | There was a problem expanding macro 'mapping'
web    | 
web    | Code in macro 'setup_db_mapping'
web    | 
web    |  1 | DB.mapping({
web    |      ^
web    | Called macro defined in lib/db/src/db/mapping.cr:60:3
web    | 
web    |  60 | macro mapping(properties, strict = true)
web    | 
web    | Which expanded to:
web    | 
web    |  > 246 |       
web    |  > 247 |         
web    |  > 248 |           @role = __temp_152.as(UserRole::Lucky::ColumnType)
web    |                            ^
web    | Error: can't cast Nil to UserRole
```

**Comment by paulcsmith** [comment]
Sorry I'm just now seeing this! We have a similar issue in Avram https://github.com/luckyframework/avram/issues/270
