### ISSUE TITLE
Raise helpful errors message in label_for

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#984]
https://github.com/luckyframework/lucky/blob/ed8d36658b7f83622dad09e81582575bc164c564/src/lucky/tags/input_helpers.cr#L4 but for the label_for method

**Comment by matthewmcgarvey** [comment]
This has been done https://github.com/luckyframework/lucky/blob/8d7bb5702d92e233c90ae29f743c7780450501af/src/lucky_avram/ext/lucky/label_helpers.cr#L1-L27
