### ISSUE TITLE
Generate crystal docs to github pages?

### ISSUE THREAD

**Issue by mdwagner** [luckyframework/lucky#988]
Is there any reason why we aren't/can't generate documentation (via `crystal docs`) and serving it up on github pages? As someone who is still new to the crystal language and its' libraries/frameworks, having to run `crystal docs` inside every library that doesn't have online documentation is a little annoying, especially if it can be added to the already existing `.travis.yml` for auto-deployment. I don't mind putting up a PR for this, just wanted to get some feedback first. Thanks.

**Comment by jwoertink** [comment]
This is definitely on the list to do. Our codebase needs a lot more internal docs to really make it worth it, but for sure this is on the roadmap.

**Comment by mdwagner** [comment]
@jwoertink is there a way to see that roadmap publicly? or is it internal?

**Comment by jwoertink** [comment]
I don't think there's anything written down unless @paulcsmith has something. It's mostly just been stuff discussed in the gitter chat, or what's already in the issues. 

related: https://github.com/luckyframework/lucky/issues/275

**Comment by paulcsmith** [comment]
Nothing written down, but we are trying to add/update docs comments. I would happily accept a PR now even if the docs aren't in perfect shape. It'd be a good kick in the butt to clean them up even more!

**Comment by mdwagner** [comment]
@paulcsmith thanks for merging! However, it looks like you forgot to add the GITHUB_TOKEN env var mentioned in the PR.

**Comment by paulcsmith** [comment]
D'oh. I completely missed that. Thanks for pointing that out. I'll add it

**Comment by mdwagner** [comment]
@paulcsmith Also, I'm not quite sure how to trigger a rebuild on Travis.

**Comment by mdwagner** [comment]
https://luckyframework.github.io/lucky/ :+1: :fireworks:

**Comment by paulcsmith** [comment]
@mdwagner Woo hoo! If you happen to have time and could do this for some of the other lucky repos like Avram and LuckyFlow that'd be awesome. But no pressure. I know the holidays can be a busy time :)

**Comment by mdwagner** [comment]
@paulcsmith That was plan! But yeah when I get some time I'll definitely make those changes.

**Comment by paulcsmith** [comment]
Wonderful! Thank you
