### ISSUE TITLE
Error: argument must have a default value when nilable needs property precedes non-nillable properties

### ISSUE THREAD

**Issue by wezm** [luckyframework/lucky#992]
I have a component:

```crystal
class Shared::LayoutHead < BaseComponent
  needs page_title : String
  needs app_js : Bool
  needs admin : Bool
  needs extra_css : String?
  # This is used by the 'csrf_meta_tags' method
  needs context : HTTP::Server::Context
  needs categories : CategoryQuery

  def render
    head do
      utf8_charset
      title "#{@page_title} – Read Rust"
      css_link asset("css/app.css"), data_turbolinks_track: "reload"
      js_link asset("js/app.js"), defer: "true", data_turbolinks_track: "reload" if @app_js

      if @admin
        css_link asset("css/admin.css"), data_turbolinks_track: "reload"
        js_link asset("js/admin.js"), defer: "true", data_turbolinks_track: "reload"
      end
      meta name: "turbolinks-cache-control", content: "no-cache"
      csrf_meta_tags
      responsive_meta_tag

      @categories.each do |category|
        tag "link", href: RssFeed::Show.with(category.slug).url, rel: "alternate", title: "Read Rust - #{category.name}", type: "application/rss+xml"
      end

      meta content: "Read Rust collects interesting posts related to the Rust programming language.", name: "description"
      css_link dynamic_asset(@extra_css), data_turbolinks_track: "reload" if @extra_css
    end
  end
end
```

This previously compiled on Lucky 0.18.0. On 0.18.2 the compiler reports this error. I'm using a picture here because useful information is lost without the colour and emphasised text.

<img src="https://user-images.githubusercontent.com/21787/71329238-eebdb480-2576-11ea-8e2f-9faa0b12e14d.png" alt="Screenshot from 2019-12-23 11-25-17" width="404">

The issue is [the addition of the inferred `nil` default value](https://github.com/luckyframework/lucky/pull/980) because now there is an argument with a default value that precedes ones without, which is not allowed (see [this test in the Crystal repo](https://github.com/crystal-lang/crystal/blob/1580298f62aee5e4664d87f8a890b0204baa09a7/spec/compiler/parser/parser_spec.cr#L1515)).

Before this change there was no default value on the `extra_css` parameter so it compiled ok. It's possible to work around the error by reordering the `needs` calls so that ones that are non-nil come first but this does not seem very intuitive. Plus, the error is extremely unhelpful as it does not point to the actual file where the error is happening. It wasn't until I discovered the `--error-trace` argument to the compiler that I was able to work out what was going on. This seems like it might be something that would trip up folks new to the framework. This is was the error is without `--error-trace`:

```
There was a problem expanding macro 'generate_needy_initializer'

Code in macro 'finished'

 1 | generate_needy_initializer
     ^
Called macro defined in lib/lucky/src/lucky/html_builder.cr:46:3

 46 | macro generate_needy_initializer

Which expanded to:

 > 35 |
 > 36 |
 > 37 |            @context : HTTP::Server::Context,
                   ^
Error: argument must have a default value
```

**Comment by jwoertink** [comment]
@wezm I've merged in this fix. If you find any cases where it still blows up, please reopen so we can work out the other cases. Thanks for reporting!

**Comment by wezm** [comment]
Awesome, thanks for the quick fix.
