### ISSUE TITLE
Nested save with alternative column name

### ISSUE THREAD

**Issue by wontruefree** [luckyframework/lucky#999]
I am trying to save a nested model that has an association with an alternative id.
```crystal
class User < BaseModel
end
```
```crystal
class Post < BaseModel
  table do
    belongs_to owner_id : User
  end
end
```
```crystal
class UserSave < User::SaveOperation
  has_one user : User
end
```

A have tried also putting this in before_safe and after_save but I have a not null on the DB tables.  Is there a way to do this?

**Comment by jwoertink** [comment]
I think you would want the  `Post` be `belongs_to user : User, foreign_key: :owner_id`. I think we're missing docs in the guides on doing the foreign_key stuff, but that's located https://github.com/luckyframework/avram/blob/master/src/avram/associations/belongs_to.cr#L2 

Not sure if that will fix this issue, but maybe give that a shot first?

**Comment by paulcsmith** [comment]
@wontruefree Did you get this working? If not, can you share a bit more info on what you are trying to do? I'm not sure I understand how the user has one user or what you'd expect it do. Would love to help get this figured out

**Comment by wontruefree** [comment]
I did I will close this.

**Comment by paulcsmith** [comment]
Awesome! Glad you got it working 🎉

**Comment by wontruefree** [comment]
Thank you for the help !!
